### ISSUE TITLE
Could not find package apigee/apigee-devportal-kickstart-project with stability dev.

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/apigee-devportal-kickstart-drupal#1]
When I run (following the README)
``` bash
./composer.phar create-project --stability dev --no-interaction apigee/apigee-devportal-kickstart-project portal
```
I see the error:
```
Could not find package apigee/apigee-devportal-kickstart-project with stability dev.
```

However when I run 
``` bash
./composer.phar create-project apigee/devportal-kickstart-project:8.x-dev portal --stability dev --no-interaction
```
..all is good.

**Comment by mikesson** [comment]
readme is incorrect (across composer, github and drupal), dash is to be replaced with underscore and without "-project" (composer [...] apigee/apigee_devportal_kickstart works for me, dev tag also detected)

**Comment by cnovak** [comment]
Created PR #5 to take care of incorrect README command issue reported by @laughingbiscuit.

@mikesson the [apigee/apigee_devportal_kickstart](https://packagist.org/packages/apigee/apigee_devportal_kickstart) project is the Drupal installation profile. If you run `composer create-project` against that repo you will not get the installation profile, Drupal core, and Drupal modules laid out properly.  The [apigee/devportal-kickstart-project](https://packagist.org/packages/apigee/devportal-kickstart-project) is the composer project template used to pull down everything in the proper file structure.

**Comment by epowelljr** [comment]
Getting the error below when using the apigee_devportal_kickstart.  I ran the composer command:

composer create-project apigee/devportal-kickstart-project:8.x-dev portal --stability dev --no-interaction

I also ran the composer command:
composer.phar create-project apigee/devportal-kickstart-project:8.x-dev portal --stability dev --no-interaction

Got the same error below:

<img width="800" alt="Screen Shot 2019-05-06 at 11 32 27 AM" src="https://user-images.githubusercontent.com/7342666/57239972-fda92400-6ff2-11e9-914a-1f5d8b45c679.png">


-Edgar
