### ISSUE TITLE
Apigee Edge connection error  - developer with <email> email address not found

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-devportal-kickstart-drupal#10]
After setting up the Developer Portal with the Kickstart distribution, I ran into another error configuring the connection to Apigee Edge.  The error in the logs says:

<img width="555" alt="screen shot 2019-02-28 at 3 13 30 pm" src="https://user-images.githubusercontent.com/20446683/53602535-58924b00-3b6c-11e9-9fef-fc1d4c8a4af9.png">

I was able to resolve the error by going to my user profile, clicking "edit" and then clicking "save," making no changes.

Just as a note, I did not run into this issue when doing an install of just Drupal 8, then installing the Apigee Edge module separately.

**Comment by kiranjyoth** [comment]
@jbennett13 Ive tried replicating this issue. Once private file system is correctly set (permissions, path etc in settings.php), and drupal creates a .htaccess file in that location, I didn't encounter this. 
Please add if there are any other steps to replicate it after setting file system, I can work towards resolving this issue.

**Comment by jbennett13** [comment]
There were no additional steps, per se.  After the file system path was set correctly and caches were cleared, I was still unable to get a connection to Edge.  That is, when I navigated to "MyApps," the connection error message was still there and no data was available.  Checking the log messages indicated the issue shown above in the screenshot.

This error flow only happened when installing Developer Portal on D8 using the Kickstart distribution.  I did not encounter this "developer with <email> not found" issue when installed D8 only, and then installed the Edge module.  Hope that helps.

**Comment by kiranjyoth** [comment]
@jbennett13 will explore ways to create private file system during install or throw exception for prompting the user to create one. Thanks!

**Comment by jacine** [comment]
Hello!  

This feature is not currently available in the installer, so this bug as reported no longer applies. However, this feature is planned and will be reworked in the near future.

Thanks,
Jacine

**Comment by jacine** [comment]
This feature is back and working in the latest release, so I think we can close this.  If you have any issues, please feel free to re-open or create a new issue.  Thanks!
