### ISSUE TITLE
Drupal 7 and 8 will be end-of-life in November 2021 and Drupal 9 will be released in 2020 so what are the plans to support Drupal 9 as Drupal 8 will no longer be supported after 2 years ?

### ISSUE THREAD

**Issue by mohit-wadhwa** [apigee/apigee-devportal-kickstart-drupal#100]

**Comment by cnovak** [comment]
@mohit-wadhwa luckily the update to Drupal 9 will be much easier than the upgrade to Drupal 8.  We do plan on having a Drupal 9 version of this profile.  Feel free to reopen this ticket if I did not fully answer your question.
