### ISSUE TITLE
Instructions for deploying to Pantheon

### ISSUE THREAD

**Issue by kscheirer** [apigee/apigee-devportal-kickstart-drupal#116]
I'm a little scared to post this cause I'm sure I did it the hard/wrong way, but I'd appreciate any feedback or improvements to this process @jacine.

# Initial D8 site

- On your Pantheon dashboard, create a new site, name it, and choose Drupal 8 as your CMS
- click "Deploy", wait for Pantheon to complete
- click to go back to your Dashboard
- click "install later" link to avoid installing Drupal yet

# Add Kickstart

- click "Git" to switch to git mode on your Pantheon dashboard
- clone locally, something like "git clone ssh://codeserver.dev.3b46e27a-c96f-48bb-a382-314e29b46c61@codeserver.dev.3b46e27a-c96f-48bb-a382-314e29b46c61.drush.in:2222/~/repository.git installtest"
- cd into your new directory
- "composer require apigee/devportal-kickstart-project:8.x-dev --update-with-all-dependencies" 
  - My install failed with "phpdocumentor/reflection-docblock (locked at 2.0.4)" preventing dependencies from being satisfied
  - Hacky solution: "rm composer.lock" then try again
- "git status" should show lots of new untracked files in modules/contrib/, profiles/contrib/, themes/contrib/, and vendor/

# Remove extra .git folders
Pantheon does not like .git files unless they are official submodules

- "find . -name ".git" -mindepth 2" to see git folders that have been added
- "find . -name ".git" -mindepth 2 | xargs rm -fr" to remove them
- "git add ."
  - You may see "warning: CRLF will be replaced by LF in..." various files, these are safe to ignore
  - unstage the following files with "git reset –- filename"
- git commit -am "adding kickstart profile and dependencies"
- git push

# Allow Icon files (thanks @jacine!)
Pantheon's default .gitignore will ignore icon files for MacOS reasons. There are necessary icons in the modules and themes used by this profile.

https://github.com/pantheon-systems/drops-8/blob/default/.gitignore#L48
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.gitignore#L92

- MacOS
  - sed -i '' '/Icon?/d' .gitignore
- "git add ."
- "git commit -am "remove icon from gitignore, add icon files"
- "git push"

# Install Profile

- Switch your repo to "SFTP" mode
- Visit your site's url, should take you to install.php
- After you choose a language, the Kickstart profile will begin installing
- Choose to install default content or not
- Switch repo back to "Git" mode

# Install missing library: swagger-ui
Swagger is installed to the vendor dir, but Drupal reports needing it at libraries/swagger-ui
- mkdir libraries
- ln -s vendor/swagger-api/swagger-ui libraries/swagger-ui

**Comment by cnovak** [comment]
@kscheirer thanks for putting together this info, we plan on reviewing this and getting back to you soon.

**Comment by jacine** [comment]
Just to add a quick update here for anyone looking to get started with Pantheon. The above method of setting things up is not recommended. 

## Step 1. Setup a Pantheon Instance via Terminus CLI

If you're looking to setup a Pantheon instance, you'll want to first figure out which setup you desire, from the 2 options below, and follow the guides linked below to get it setup:

1. [Github Pull Request Workflow with CircleCI](https://pantheon.io/docs/guides/build-tools/)
2. [Drupal 8 and Composer on Pantheon Without Continuous Integration](https://pantheon.io/docs/guides/drupal-8-composer-no-ci/)

As the above guides detail, you'll create a site using Terminus CLI, not the Pantheon Dashboard.  You'll want to get all the code in place, following all the steps, **except for the site installation**, until you get the kickstart code in place as well.

The end result of either of this step will result in some form of https://github.com/pantheon-systems/example-drops-8-composer.

## Step 2. Merge the Dependencies found in the [Kickstart composer project](https://github.com/apigee/devportal-kickstart-project-composer).

You'll need to manually merge in the requirements of the [Kickstart composer project](https://github.com/apigee/devportal-kickstart-project-composer):

1.  Require any missing packages referenced in the `composer.json` file, under [`"require"`](https://github.com/apigee/devportal-kickstart-project-composer/blob/8.x/composer.json#L15), such as `composer require apigee/apigee_devportal_kickstart`.
2. If there are any custom [`"repositories"`](https://github.com/apigee/devportal-kickstart-project-composer/blob/8.x/composer.json#L6) or [`"extra": { "patches" ... }`](https://github.com/apigee/devportal-kickstart-project-composer/blob/8.x/composer.json#L37), add those as well.  To  As of 7/1/19, there are none.

At the end of this step, you'll have a merged version of https://github.com/pantheon-systems/example-drops-8-composer and https://github.com/apigee/devportal-kickstart-project-composer.

## Step 3.  Push all the code Pantheon

Once you've installed all the Kickstart dependencies, and made any desired adjustments to Pantheon config files, push the code to Pantheon via Git.  Pantheon doesn't support Git submodules or Composer, so you will commit all package files, including the `vendor` directory, all contributed modules, etc. 

## Step 4. Install the site via Web Browser on Pantheon DEV instance

Do NOT use Terminus to install the Kickstart.  Find the DEV site URL from the Dashboard, after you push the code, and use a web browser to install it.  There are options available during the Kickstart Drupal installer, such as setting up an Edge connection, that you will want to configure during the installation.  Note:  You will need to switch the site to [STFP mode temporarily](https://pantheon.io/docs/guides/quickstart/connection-modes/) to run the installer.

**Comment by kscheirer** [comment]
I wrote out some step-by-step directions based on your comment @jacine: https://docs.google.com/document/d/1Rt5Br_7aeakAZAH9NN5Hr8ZyqMvM_se3oLvqRDlkR6w/edit?usp=sharing

It's a little shorter, and using terminus is definitely superior than clicking on the pantheon dashboard.
I think there is a way to automate a few of the steps using scripts, like the ::cut:: in .gitignore, see https://github.com/pantheon-systems/example-drops-8-composer/blob/master/scripts/composer/ScriptHandler.php::prepareForPantheon(). That should be fired by composer.json that comes with example-8-drops already, but I didn't dig into why that wasn't happening for me.

**Comment by jacine** [comment]
FYI, I added a comment on this: https://github.com/pantheon-systems/example-drops-8-composer/issues/156

**Comment by shadcn** [comment]
@jacine @kscheirer Can we close this issue? We can move the instructions from @jacine to a wiki. 

@kscheirer you can add your step-by-step directions to the wiki too so people can find it.

**Comment by kscheirer** [comment]
@arshad Which wiki?

**Comment by cnovak** [comment]
I also created documentation on [how to install Apigee Kickstart on Pantheon.io](https://gist.github.com/cnovak/38ed1026980b782c886bbd04b8a7f70f) which I used to set up test servers.  Check out pantheon-systems/kickstarter_portal/issues/2 for another option.

**Comment by jbennett13** [comment]
Should either/both of these docs  (Karl/Jacine's or Chris') be included in our Kickstart doc guide on Drupal.org?

**Comment by kiranjyoth** [comment]
@cnovak @jacine @kscheirer I have created a repo for installation on pantheon. I have tested this template and it works as expected. https://github.com/stratus-meridian/apigee-kickstart-drupal8-drops
Please let me know how it works for you.

**Comment by cnovak** [comment]
That is great to see @kiranjyoth, thanks!

**Comment by cnovak** [comment]
@jbennett13 I am not sure - Pantheon seemed to want people to request a demo site by clicking in "Free Consultation" button at the bottom of [this Pantheon created page about Apigee/Pantheon partnership](https://pantheon.io/product/apigee-pantheon-partnership). However I put together instructions so it is easier to setup a testing/development/eval site for myself since I need to have more control over the process and do not want to wait for manual configuration when I need to get a site up.

@giteshk or @arunz6161 may have more info.

**Comment by presfer** [comment]
Hi to all. Earlier, when it was Apigee KickStart 8.x-1.7, your instruction works fine, without any issues. But now, with 8.x-1.9, i get an error during installation all dependencies. Please, i need advise to resolve it.
![composer_issue](https://user-images.githubusercontent.com/40182537/72252232-9757b500-3607-11ea-90dc-8105254b6f18.JPG)

**Comment by shadcn** [comment]
@presfer `apigee/devportal-kickstart-project` is a project template. You should use it with `composer create-project`. Example:

`composer create-project apigee/devportal-kickstart-project:8.x-dev SITE_NAME --no-interaction`

**Comment by presfer** [comment]
@arshad, i need to add apigee kickstart project to Pantheon, thats why i trying to install all dependencies, based on instruction by @kscheirer.
![composer_issue_2](https://user-images.githubusercontent.com/40182537/72254607-46e35600-360d-11ea-8e20-0a9637a20e55.JPG)

**Comment by shadcn** [comment]
@presfer is this a new or existing site?

**Comment by presfer** [comment]
@arshad 
It's a new one.

I found a photo of my installation in the past, it was 29.11.19 and it was Apigee_KickStart 8.x-1.7(everything is fine, but now i have an issue during installation) 
![composer_issue_3](https://user-images.githubusercontent.com/40182537/72332738-3a213980-36c3-11ea-9715-698c35d52f64.JPG)

**Comment by cnovak** [comment]
@presfer I know that you can contact Pantheon and they can help you get a site up and running, just fill out the form at the end of the [Apigee Pantheon Partnership page](https://pantheon.io/product/apigee-pantheon-partnership).  They have a Kickstart upstream they will use to keep you site up to date.

I am not sure about @kscheirer 's doc above, maybe it no longer works? @kscheirer have you tried this way lately?

Two other options:
1. [Stratus Meridian Kickstart repo](https://github.com/stratus-meridian/apigee-kickstart-drupal8-drops)
2. [My instructions on getting kickstart up on Pantheon](https://gist.github.com/cnovak/38ed1026980b782c886bbd04b8a7f70f)

**Comment by cnovak** [comment]
I am going to close this issue for now, since Pantheon.io has it's [preferred approach of setting up a Kickstart site](https://pantheon.io/product/apigee-pantheon-partnership). 

Comment on ticket if something is missing.
