### ISSUE TITLE
Implement Custom Theming & Configuration for Rate Plan Detail page alongside DRUP-762

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#128]
This issue is for the custom theming and config that will be necessary to implement the Rate Plan detail page as designed. This issue may or may not end up relying on some aspects of DRUP-762 (potentially at field level).

**Comment by jacine** [comment]
Adding @arshad to the list of assignees, since he did a ton of work here already.

**Comment by jacine** [comment]
This is fixed by various PRs from @arshad and I.
