### ISSUE TITLE
Style the Monetization user profile pages, as designed for Kickstart

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#129]
Style the Monetization user profile pages, as designed for Kickstart

**Comment by shadcn** [comment]
PR (wip): https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/146

**Comment by shadcn** [comment]
PR merged: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/146
