### ISSUE TITLE
Re-work the Title Bar component to allow for a Buttons, either in place of, or in addition to the Font Awesome Icon

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#131]
Re-work the Title Bar component to allow for a Buttons, either in place of, or in addition to the Font Awesome Icon

**Comment by jacine** [comment]
This can't be done the way I was thinking because this would actually require content for rate plans, which we don't have.  I'm going to leave the Title bar component alone, and do this styling in #128, directly in the rate plan template.
