### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by epowelljr** [apigee/apigee-devportal-kickstart-drupal#136]
I installed the kickstarter 8.7.2 on a Redhat server. 
I'm getting the 404 Not Found error. This page can not be found on this server.

I get this error after clicking on all the pages of the website. The front page will display for the most part. Some of the image do not display on the frontpage. Also, I get the same error when clicking on login of sign. 

--Edgar

**Comment by jacine** [comment]
Hi @epowelljr,

@cnovak added some information that should be helpful in #106.

I also found this, which suggests that you may need to configure this outside of `.htaccess` itself: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/deployment_guide/s1-apache-config 

Hope it helps!
Jacine

**Comment by cnovak** [comment]
Here is that info again:
It sounds like an issue with your web server configuration with Drupal clean urls:
* [Fixing clean URL problems](https://www.drupal.org/docs/8/troubleshooting-drupal-8/fix-drupal-8-clean-urls-problems)
* [This thread has the same issue of links being 404s](https://groups.drupal.org/node/105954)

Let us know if you are still having issues.
