### ISSUE TITLE
 Style the Teams pages in the Apigee Kickstart theme

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#141]
This task includes:

- **Teams**: `/teams`
  https://projects.invisionapp.com/d/main/default/#/console/16939246/361490145/preview
- **Team Members** `/teams/team/members`
  https://projects.invisionapp.com/d/main/default/#/console/16939246/361490141/preview
- **Team Apps**: `/teams/team`
  https://projects.invisionapp.com/d/main/default/#/console/16939246/361490143/preview

## Related issues

- Consolidate M10n tabs: https://github.com/apigee/apigee-m10n-drupal/issues/120
- Text changes for "Team Members" vs "Members: https://github.com/apigee/apigee-edge-drupal/issues/216

### Teams

Page: `/teams`
Comps: https://projects.invisionapp.com/d/main/default/#/console/16939246/361490145/preview

This page is an "entity collection" view, which is a basic table, that doesn't provide any means of customization from a theme. The following designs require changes at module-level (not simply theme customizations).

1. **Change the team link in the first column to go `/teams/team/apps` instead of `/teams/team`**.
  The current behavior is to view `/teams/team` when clicking the link, which is the default entity view of a Team. Once on that page, you would click "Team Apps" to view the team's apps.  I think this could be a difficult change to make, and I'm not sure if bypassing the entity view page makes sense.  It might be better to find a way to display these on the View page directly?
  <img width="1179" alt="teams-to-team-apps" src="https://user-images.githubusercontent.com/60979/59052662-8834ab80-885d-11e9-808f-03af3373a43d.png">
  <img width="1055" alt="team-team-default" src="https://user-images.githubusercontent.com/60979/59052939-3f312700-885e-11e9-8640-9edc4973e3c0.png">

2. **Change the Operations Dropbutton to links with icons**. This is not currently customizable. Changes would need to be made either in Apigee Edge or the Kickstart enhancement module to achieve these results. Depending on what we do above, "Team Apps" and "Team Members" may end up needing to be removed from the list of links.
<img width="249" alt="Screen Shot 2019-06-06 at 2 20 30 PM" src="https://user-images.githubusercontent.com/60979/59056501-596f0300-8866-11e9-8849-8f4eb06a2ae3.png">

3. **Remove/hide the table headers, and implement a "Sort by" widget above the table** instead of clicking the headers themselves. This seems like a good task to place lower priority on, and get to when we have more time.

<img width="823" alt="table-header-sorts" src="https://user-images.githubusercontent.com/60979/59056821-09dd0700-8867-11e9-95e3-de78e4b15b3a.png">

<img width="1143" alt="table-headers-sort-by-widget" src="https://user-images.githubusercontent.com/60979/59056834-0ea1bb00-8867-11e9-98bf-8fa3e1481b5f.png">

### Team Members

4. The team members table currently contains 3 columns (name, roles, operations). The operations column is a Dropbutton with 2 options: "edit" and "delete". This page is an "entity collection" view, which is a basic table, that doesn't provide any real means of customization.

    The designs propose splitting the "operations" column into 2 columns, and showing the links normally. If we decide to make this change, we'll also need to decide whether it belongs in Apigee Edge or the Kickstart Enhancement module.

Current:
<img width="744" alt="Screen Shot 2019-06-06 at 1 31 43 PM" src="https://user-images.githubusercontent.com/60979/59053576-be732a80-885f-11e9-9fb9-aeb3e477c081.png">

Proposed:
<img width="1142" alt="Screen Shot 2019-06-06 at 1 34 45 PM" src="https://user-images.githubusercontent.com/60979/59053634-df3b8000-885f-11e9-8cbf-bd29be0830fb.png">

**Pros**

- Simplifies the appearance of table.
- Clearly communicates what can be done on this page.

**Cons**

- Could appear squished if member names and/or roles with long names are used, even on large screens.
- Takes up more space, and could potentially look bad, cause the need for scrolling on small devices.

**Comment by jacine** [comment]
Just updated the issue description here to contain a list of things to discuss.

**Comment by arlina-espinoza** [comment]
Comments:

- _1. Change the team link in the first column to go /teams/team/apps instead of /teams/team_: Although awkward, the team apps is probably why most people will be looking for on the teams, so landing here makes sense. @arshad Do you have any suggestions regarding _" It might be better to find a way to display these on the View page directly"_?
- _2. Change the Operations Dropbutton to links with icons:_ This is not needed.
- _3. Remove/hide the table headers, and implement a "Sort by" widget above the table_: Will implement.
- _4. Change team members table operations into columns:_ Keep current operations dropdown for the reasons stated above, and also because it might break if any other operations are added afterwards.

**Comment by shadcn** [comment]
@arlina-espinoza are we implementing these in Kickstart or Apigee Edge?

**Comment by arlina-espinoza** [comment]
As these are style changes they can be in Kickstart. Thanks @arshad :smiley:
