### ISSUE TITLE
Revert local action customizations to defaults

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#145]
In earlier versions of Kickstart comps, the button to add a new app on the "My Apps" page, the button text read: "Register New App".  This has been removed from newer versions, and also affects the Team app button.

The results of this issue should be:

- On `user/x/apps` the button should read "Add App"
- On `teams/x/apps` the button should read "Add Team App"

**Comment by shadcn** [comment]
Fixed in https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/147
