### ISSUE TITLE
When no sidebar present, blog pages still have a blank space to the left.

### ISSUE THREAD

**Issue by davemyb** [apigee/apigee-devportal-kickstart-drupal#149]
Updated Kickstart to the latest dev version and saw that sidebars were added to the regions and new code exists to add them to pages. Without any other changes, the included article nodes now have a blank region to the left on large screens. The article content should be full width when no sidebars are not present.

This is due to the "col-lg-8" class on the wrapper, which is assigned in node-article--full.html.twig, at line 42:
`    content_no_sidebar_col_classes: ['col-lg-8']`

Changing that to `col-lg-12` fixes the issue.

Adding sidebars still works with the above change in place.

**Comment by jacine** [comment]
Hi @davemyb, this isn't a bug and is not any different visually than in the previous version.  It is supposed to be `col-lg-8` when there are no sidebars.  Here's a screenshot with the code inspector showing that class.

<img width="1595" alt="Screen Shot 2019-06-11 at 7 13 33 PM" src="https://user-images.githubusercontent.com/60979/59313006-2e791a80-8c7d-11e9-8cf5-bf490eabf016.png">

If you'd like to make it full width, you're welcome to create a sub-theme, and change it.

Thanks,
Jacine
