### ISSUE TITLE
The website encountered an unexpected error. Please try again later. with Kickstarter

### ISSUE THREAD

**Issue by nswaich** [apigee/apigee-devportal-kickstart-drupal#156]
I am using a fresh install of Drupal with the Acquia Dev Desktop. Whenever I create a site using your kick-starter, I use composer and then Acquia to initialize the site. Everything seems to be working properly along with all the demo content. I am not yet associated with Apigee so I don't have credentials for Apigee connection settings. After some random amount of testing, usually 30 minutes to 3 hours, I run into an error saying "the website encountered an unexpected error. Please try again later". This has happened 5 times now on separate sites using this module and its dependencies.

**Additional context**
I installed the kickstarter using composer and then connected it to Acquia and skipped the step for entering Apigee credentials. 

**Version Info**
Drupal 8.7.1
Apigee Developer Portal Kick-start 8.x-1.1 
No other modules were installed outside of the dependencies installed by composer.
The watchdog log is attached below:
%type: @message in %function (line %line of %file).

[watchdog-log.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/3302740/watchdog-log.txt)

**Comment by jacine** [comment]
Hi @nswaich!

Thanks so much for this report.  Your watchdog log helped us track down a bug.  I've posted a PR with a fix, in #158 that should resolve the issue.

Thanks!
Jacine
