### ISSUE TITLE
Medial oEmbed Warning

### ISSUE THREAD

**Issue by epowelljr** [apigee/apigee-devportal-kickstart-drupal#163]
**Describe the bug**
What is causing this and what should be done to remove the warning?

<img width="1313" alt="Screen Shot 2019-06-20 at 7 10 31 PM" src="https://user-images.githubusercontent.com/7342666/59888909-70961080-938f-11e9-9d50-0d7273298089.png">

**Expected behavior**

**Screenshots**

**Additional context**

**Version Info**
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

**Comment by jacine** [comment]
Hi @epowelljr!

This isn’t a bug. It’s a warning, and unfortunately you cannot suppress it, [yet](https://www.drupal.org/project/drupal/issues/2962753). It’s coming from Drupal core’s media module. If you click the link in that message there is more information.

In short, it has to do with the video media entity which allows you to embed YouTube (and other oEmbed) videos. Kickstart does not ship with any video content, so unless you add some there is no worry at all.  And the warning is just about being careful to only embed content from trusted providers, as iframes can potentially be unsafe.

Hope that helps!
Jacine
