### ISSUE TITLE
Error when Registering Users in the Apigee Dev Portal

### ISSUE THREAD

**Issue by epowelljr** [apigee/apigee-devportal-kickstart-drupal#165]
I having issues when trying to register user in the Apigee Dev Portal.

Attached is the errors from the Report Status Log.
<img width="1282" alt="Screen Shot 2019-06-21 at 8 45 53 PM" src="https://user-images.githubusercontent.com/7342666/59957407-1d42c180-9466-11e9-8fc7-6b7b06362ac4.png">

**Comment by jacine** [comment]
Hi @epowelljr,

This is unrelated to Kickstart. Seems like you’ve created a custom field, for a phone number, and you’re trying insert and invalid value? This type of thing is not something we’re really able to help with here, but you might want to try using the telephone field type that ships with Drupal core (there is a module you can enable).

Thanks,
Jacine

**Comment by epowelljr** [comment]
Excellent!
Thank you.

**Comment by jacine** [comment]
You’re welcome! 🙂
