### ISSUE TITLE
Can I install this on an existing Drupal multisite as a profile without core?

### ISSUE THREAD

**Issue by prophet108** [apigee/apigee-devportal-kickstart-drupal#166]
Can I install this on an existing Drupal multisite as a profile on a standard 8.7 core?

**Comment by shadcn** [comment]
Hi @prophet108 

If this is a new site on your multisite setup, then you can pull in the kickstart profile and use that to install your new site.

If this is an existing site, you cannot use this profile. You should install the [Apigee Edge](https://www.drupal.org/project/apigee_edge) and [Apigee Monetization](https://www.drupal.org/project/apigee_m10n) modules instead.

`composer require drupal/apigee_m10n` should pull in the module and dependencies.

**Comment by prophet108** [comment]
Thanks for your reply. This would be a new site on our multisite setup. I can manually install this profile but Is there a way to add it using composer? The kickstart as-is has some assumptions in the composer.json file that don't work in our Acquia account including:

"installer-paths": {
      "web/core": [
        "type:drupal-core"
      ],

and 

"require": {
    "php": "^7.1",

The demo is a great starting point and I just want to know whether I can use it or do I need to try to replicate it myself using the kickstart modules and theme. Thanks again.

**Comment by cnovak** [comment]
I am thinking we can remove both these sections from our composer.json since the [apigee/devportal-kickstart-project-composer](https://github.com/apigee/devportal-kickstart-project-composer) project should have these requirements.  Need to verify.

**Comment by prophet108** [comment]
I am excited about the possibility of being to manage this as a profile with composer. Thank you for your work on this.

Looking at your composer.json file, there are more entries that would need to be removed in order to have it manage only the bare necessities relating to the profile. For example, all of the following which reference the location "web" since Acquia uses "docroot", etc. 

"installer-paths": {
      "web/core": [
        "type:drupal-core"
      ],
      "web/libraries/{$name}": [
        "type:drupal-library"
      ],
      "web/modules/contrib/{$name}": [
        "type:drupal-module"
      ],
      "web/profiles/contrib/{$name}": [
        "type:drupal-profile"
      ],
      "web/themes/contrib/{$name}": [
        "type:drupal-theme"
      ]
    },

**Comment by jacine** [comment]
I have a PR up for this that could use some additional reviews: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/203

**Comment by jacine** [comment]
Fixed by #203.

**Comment by prophet108** [comment]
I tested this and it works perfectly! Thank you.
