### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by kscheirer** [apigee/apigee-devportal-kickstart-drupal#178]
**Describe the bug**
During profile install, in the initial monetization step, big red warning appears

**To Reproduce**
1. Follow https://gist.github.com/jacine/4abe1ddcd94a1bae838a648e5dac4ffa
2. Using browser, begin install
3. Get to `Configure Monetization` step
4. Sometimes seen on `Setup monetization` step instead
5. Unfortunately, this is not consistently reproducible - may have to do with a call to Edge failing intermittently and not retrieving currency list.

**Expected behavior**
No error

**Screenshots**
<img width="772" alt="Screen Shot 2019-07-03 at 3 26 49 PM" src="https://user-images.githubusercontent.com/283628/60628671-5bfe4300-9da7-11e9-8379-3cd29239321b.png">

**Additional context**
`count()` now throws a warning if it does not receive a countable, see https://www.php.net/manual/en/migration72.incompatible.php. Drupal has generally dealt with this by not using count() to test for existence, instead using empty(). The D7 issue is https://www.drupal.org/project/drupal/issues/2885610 and an example patch is https://www.drupal.org/files/issues/2018-04-21/drupal-7-count-function-deprecation-fixes-2885610-19.patch.

**Version Info**
apigee/apigee-client-php                 2.0.3        
apigee/apigee_devportal_kickstart        1.2.0       
drupal/apigee_edge                       1.0.0       
drupal/apigee_m10n                       1.0.0-rc1    
drupal/core                              8.7.3

**Comment by kscheirer** [comment]
Not sure what the expected behavior should be if the currency call fails. We can avoid the error, but the currency checkboxes wont appear, and the missing settings are an error on the Status Report page. Is it possible for an Org not to have any currencies configured?

**Comment by shadcn** [comment]
Seems to be an issue when there are no supported currencies. Nice catch @kscheirer. I'll send a PR.
