### ISSUE TITLE
Close "x" button on messages are mis-aligned when message is longer than single line.

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#181]
**Describe the bug**
Placement of close button is inconsistent and outside of the box in some cases.

**Expected behavior**
Close button should be aligned at the top right, consistently.

**Screenshots**
It is shown in the error in this screenshot, though the close button actually outside the box when pre tags (i think) are in the message: 

![example of single and multiline errors](https://user-images.githubusercontent.com/60979/60828212-e0720c80-a17f-11e9-890a-fe5db5218b32.png)
![example of error with code](https://user-images.githubusercontent.com/60979/60287820-d5e28800-98e0-11e9-8139-714d78d8d537.png)

**Comment by shadcn** [comment]
This is a Radix issue btw. It was fixed. I'll tag a new release this week.

**Comment by jacine** [comment]
Nice!!! Thanks @arshad!

**Comment by jacine** [comment]
Removed the 8.x-1.3 milestone, since this is being fixed in Radix, and will be in the next release.  I'll leave this open until that release happens.

**Comment by shadcn** [comment]
`apigee_kickstart` is overriding the Radix template for alert. I pushed a fix for it in #235
