### ISSUE TITLE
Checkbox elements that contain a description need work

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#186]
**Describe the bug**
When a checkbox has a label, description and asterisk, it doesn't look right.

**To Reproduce**
1. Log in with a newly created developer account.
2. Click on a rate plan 
3. Scroll down to the purchase form.
4. Note that everything is squished together and the asterisk is misplaced.

**Expected behavior**
Asterisk needs to be at the top right of the label, and description should be on a new line.

**Screenshots**
![checkbox-with-asterisk-label-description-looks-bad](https://user-images.githubusercontent.com/60979/60837858-4ddd6780-a197-11e9-9329-c6cee7cb7960.png)

**Comment by shadcn** [comment]
Fixed by #201
