### ISSUE TITLE
Table <td> alignment issue noticed on Payment methods page

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#188]
**Describe the bug**
`<td>` alignment is inconsistent, I think partially because of `.btn-link` / operations.  I just ran into this somewhere else that I cannot recall ATM, but we should fix this globally if we can.

**To Reproduce**
1. Log in and go to "Payment methods" page.
2. Add one or more payment methods.
3. Notice the the `<td>` elements are not aligned consistently.

**Expected behavior**
Should probably all align top vertically?  

**Screenshots**
<img width="1395" alt="payment-methods-table-styling-off" src="https://user-images.githubusercontent.com/60979/60844307-e5968200-a1a6-11e9-9477-a6c0a86fdf13.png">

**Comment by shadcn** [comment]
Looks like commerce is replacing dropbuttons with normal links. See `\Drupal\commerce_payment\PaymentMethodListBuilder::buildOperations`.

We could go back to dropbutton? This looks cleaner but might still need some alignment fixes.

![Payment_methods___Apigee_Inc](https://user-images.githubusercontent.com/124599/60892281-f828be00-a26f-11e9-92ce-15d0be2711db.jpg)

**Comment by jacine** [comment]
Hmm... 🤔 What do you think the odds of them changing this in the future are?  Looks like this is a standard, rigid entity list, that can barely be manipulated at all, so it may be safe...

I guess another option is NOT to use `.btn-link` and use/create a button style that looks like this, e.g. `btn-tertiary`?

**Comment by shadcn** [comment]
> I guess another option is NOT to use `.btn-link` and use/create a button style that looks like this, e.g. `btn-tertiary`?

Let's see if we see this again then we can add a new `.btn-tertiary`.

For now, I removed the padding with the buttons. Let me know what you think.

**Comment by jacine** [comment]
Fixed by #199.

**Comment by jacine** [comment]
> > I guess another option is NOT to use `.btn-link` and use/create a button style that looks like this, e.g. `btn-tertiary`?
> 
> Let's see if we see this again then we can add a new `.btn-tertiary`.
> 
> For now, I removed the padding with the buttons. Let me know what you think.

Yes, this works!
