### ISSUE TITLE
Add requirement module to allow easier setup if m10n is enabled after install

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#233]
The end result of enabling Monetization in Kickstart is different depending on the way you install it:

- **Site install** (feature complete, highly recommended): Initial Apigee Kickstart installation, when performed in a browser, e.g. `https://localhost/core/install.php`, where Monetization features are configured as one of the installation steps.
  - Feature complete
  - Ability to configure your commerce store, pre-filled with Apigee organization details.
  - "Add credit" Product type, variant type, and variant created for you.
  - Supported in Edge currencies presented as options for you.
  - Products created based on those selected currencies, configured to work with "Add Credit" features out of the box.
  - Entity displays/fields for Product & Add Credit customizations/features.
  - Customizations to various Commerce module views.
  - Customizations to Apigee Monetization entity displays.
  - Custom theming support in Apigee Kickstart theme for the Entity Displays & Commerce views overrides.

- **Module install**: Apigee Kickstart Portal is already installed, and *Apigee Kickstart Monetization* module is enabled on `/admin/modules`.
  - "Add credit" Product type, variant type, and variant created for you.
  - Entity displays/fields for Product & Add Credit customizations/features.
  - Custom theming support (not as complete as site-install?).  Looking to improve this in #232.

The reason for this is simply because of features available in Drupal, and one being designed to be interactive and one not.  When installing the profile, you have the ability to create installation steps (tasks) and offer configuration options, accept user input, and evaluate and act on it.  When enabling a module, you don't have any of that.

Because of the way Monetization features are typically handled at Apigee, as an Edge add-on, it's common for Monetization to be added at a later date.   At this point, if the a portal has already been installed, then the *module-install* is the only option, and it's less feature complete.

It would be great if we could find a way to achieve the same end result, whether enabled at time of installation or after a portal installation already exists.

**Comment by jacine** [comment]
Just wanted to note 2 issues found during this analysis that should be resolved here:

- `createPaymentGateway()` is unused should be removed.
- a configuration file is not properly named:

```diff
- apigee_devportal_kickstart/config/optional/apigee_m10n_add_credit.config.info.yml
+ apigee_devportal_kickstart/config/optional/apigee_m10n_add_credit.config.yml
```

**Comment by shadcn** [comment]
We are moving this to the module. See https://github.com/apigee/apigee-m10n-drupal/issues/190

**Comment by shadcn** [comment]
This is now all handled in the contrib modules (see apigee/apigee-m10n-drupal#190). I'm going to close this issue. Feel free to reopen if not fixed.
