### ISSUE TITLE
Document process for changing emails generated by the D8 portal

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-devportal-kickstart-drupal#236]
Document steps for customizing the D8 portal to:
1.  Trigger emails on App creation or approval
2.  Send registration emails

This should be tested to see if steps relevant to an install using the Kickstart distribution differ from D8 Edge documentation.  Docs may be more relevant in the Edge doc guide.

**Comment by kscheirer** [comment]
1. We don't have any Rules support afaik to react to these events, so this would require custom code.

2. You can configure registration emails at "Configure" => "People" => "Account settings" or `/admin/config/people/accounts` in the set of vertical tabs at the bottom.

**Comment by jbennett13** [comment]
Added a few additional details to https://www.drupal.org/docs/8/modules/apigee-edge/configure-developer-registration.
