### ISSUE TITLE
Document the steps for adding custom attributes on Apps

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-devportal-kickstart-drupal#237]
Document the steps for adding custom attributes on Apps (now fields in Drupal).  Check with Gitesh for more detail.

**Comment by kscheirer** [comment]
- Install Kickstart
- Configuration => Apigee Edge => Apps => Developer Apps, then tab Manage Fields or "/admin/config/apigee-edge/app-settings/developer-apps/fields"
- (+) Add Field
- Follow field configuration steps. click save
- Click "Manage Display" tab
- Click "Collapsible card" sub-tab
- Drag your field from the "Disabled" section into the top section
- Save

The new field will be created as a custom attribute on all Apps. It will appear on the app creation form. It will also appear on the app's Details tab. If you wish for a private field that is not displayed there, you can skip adding it on the "Manage Display" tab

**Comment by jbennett13** [comment]
Added a few notes to the existing Edge module documentation to highlight 1) that this can configuration can be used to add custom attributes and 2) that the configuration of these fields is in a slightly different place in a Kickstart portal.
