### ISSUE TITLE
Documentation Request: Explain the options for  "Key provider" under advanced settings

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#246]
**Is your feature request related to a problem? Please describe.**
On the Apigee edge connection page, under "Advanced Settings" (admin/config/apigee-edge/settings), there are 5 options on "Key Provider" dropdown. Please document each option.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
Screenshot below
<img width="340" alt="Screen Shot 2019-08-08 at 1 57 55 PM" src="https://user-images.githubusercontent.com/4381612/62737514-d2184a00-b9e4-11e9-87a4-295d4c0cab82.png">

**Comment by shadcn** [comment]
@arunz6161 This functionality is provided by Apigee Edge. Should we fix this in Edge instead?

**Comment by arunz6161** [comment]
@arshad you are right. @cnovak has created one in edge : https://github.com/apigee/apigee-edge-drupal/issues/256
