### ISSUE TITLE
Kickstart install with monetization option errors out

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#254]
**Describe the bug**
After you configure a monetized org during kickstart installation through web ( i.e by navigating to core/install.php), kickstart recognizes that the enabled org is monetized and adds monetization configuration steps. But this errors out right away 

**To Reproduce**
1. Install kickstart by running the following command:
composer create-project apigee/devportal-kickstart-project:8.x-dev MY_PROJECT --no-interaction

2. When prompted to enter Apigee edge credentials, enter that of a monetized org.
3. You will see the attached error

**Expected behavior**
Install should complete successfully. 

**Screenshots**
<img width="1166" alt="Screen Shot 2019-08-21 at 4 46 14 PM" src="https://user-images.githubusercontent.com/4381612/63476403-8d090480-c435-11e9-85db-68ad8d32077e.png">

**Additional context**

**Version Info**
Latest kickstart version 8.7.6

**Comment by arunz6161** [comment]
Arun to provide mint org credentials to reproduce the issue.

**Comment by arlina-espinoza** [comment]
@arunz6161 I could not replicate the issue with the latest Kickstart, Edge and M10n with the provided organization. However when testing with another of the orgs provided, I did find that if an organization did not have any currencies setup then a similar error would be displayed:

![Screenshot_2019-09-06 Setting up monetization Apigee Developer Portal Kickstart](https://user-images.githubusercontent.com/4062676/64567264-b28a7f00-d30c-11e9-98ec-1b95b0c9f297.png).
