### ISSUE TITLE
Add logo to Customizer

### ISSUE THREAD

**Issue by kscheirer** [apigee/apigee-devportal-kickstart-drupal#255]
I use the Customizer frequently, and it's very useful, thanks! I'd like to be able to change the theme's Logo as well from this window.

Currently this is available in the theme settings, it would be convenient to have it right on the customizer as well.

**Comment by jacine** [comment]
I don't think this belongs in Customizer, which is literally an API for CSS Variables.  

If we want to do this, it should be a separate custom module, and ideally a contrib module, whose sole purpose is to edit theme settings (as a whole) using the **Settings Tray** module.

One thing that would be nice to add in customizer, is the ability to set a max width and height for the logo.  We have defaults in place for this, but they don't work well with every logo size as I've recently learned.

**Comment by cnovak** [comment]
Closing as it is not a feature to add to Kickstart, but if you create this module let us know and we can incorporate it.
