### ISSUE TITLE
Custom Developer App attributes do not display in App details tab

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-devportal-kickstart-drupal#256]
**Describe the bug**
If I add a custom attribute to the Developer App entity using the steps below, the field does get added to the App Creation form, as expected.  However, it does not display on the individual app "detail" tab even if content has been entered for the custom attribute field for that app.

Steps to replicate:
- Install Kickstart
- Configuration => Apigee Edge => Apps => Developer Apps, then tab Manage Fields or "/admin/config/apigee-edge/app-settings/developer-apps/fields"
- (+) Add Field
- Follow field configuration steps
- The new field will be created as a custom attribute on all Apps. It will automatically appear on the app creation form.
- Navigate to the Apps page, select an App, and then click the "Details" tab.  

BUG
The new attribute field does not appear on the "Details" tab as a potential attribute when viewing an individual app on the "Apps" page. 

The new field does appear when editing an existing app, at user/[uid]/apps/[appname]

**Expected behavior**
In order to be consistent with similar behavior using Drupal 7 modules, the field should display on the individual app detail page.

**Comment by kscheirer** [comment]
Adding a field correctly creates a custom attribute
<img width="1161" alt="Screen Shot 2019-08-29 at 12 11 40 PM" src="https://user-images.githubusercontent.com/283628/63969270-5eeb7c00-ca56-11e9-9012-fbd40abbfe94.png">

Field is automatically added to display
<img width="940" alt="Screen Shot 2019-08-29 at 12 12 04 PM" src="https://user-images.githubusercontent.com/283628/63969307-7165b580-ca56-11e9-9e42-d2e2f945ca86.png">

Field is displayed in "Details" tab when viewing app entity directly (note url)
<img width="1166" alt="Screen Shot 2019-08-29 at 12 12 57 PM" src="https://user-images.githubusercontent.com/283628/63969354-89d5d000-ca56-11e9-864c-d8af01e9b218.png">

Field is *not* displayed on the Apps page view, this is the bug.
<img width="1155" alt="Screen Shot 2019-08-29 at 12 12 34 PM" src="https://user-images.githubusercontent.com/283628/63969393-a1ad5400-ca56-11e9-9112-5d5a1f34fe81.png">

**Comment by kscheirer** [comment]
@jacine pointed out that the field must be added to the "collapsible card" view mode, then it works fine. So there's no bug, this can be handled with documentation.

**Comment by samhaldia** [comment]
Adding a Field Name like FirmId doesnt allow it complaints saying only Lowercase letters are allowed in machine name.
Is there any fix or way out for this?
