### ISSUE TITLE
Can we document steps for nginx in the Single Sign-On (SSO) via SAML guide

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-devportal-kickstart-drupal#261]
The documentations [here](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/integrate-simplesamlphp-authentication) describes the steps to configure simplesamlphp with Apache.

Could we add instructions for nginx since a lot on-premises customers use it.

**Comment by kscheirer** [comment]
Basically step 6 from https://community.apigee.com/articles/60901/sso-integration-via-saml-with-developer-portal-for.html:
```
location ^~ /simplesaml {
  index index.php index.html index.htm;
  alias /opt/apigee/apigee-drupal/wwwroot/private/simplesamlphp/www;
    location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
    include /opt/nginx/conf/fastcgi_params;
    fastcgi_pass 127.0.0.1:8888;
    fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
    fastcgi_param PATH_INFO $pathinfo if_not_empty;
  }
}
```

The above code is assuming paths used by Apigee OPDK

**Comment by phdhiren** [comment]
Documentation updated
