### ISSUE TITLE
Unable to retrieve Analytics, Always getting page not found

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-devportal-kickstart-drupal#268]
I am using kickstart
using composer
<img width="473" alt="pagenot found" src="https://user-images.githubusercontent.com/4405193/65265377-cf7a3b80-dade-11e9-9847-9d28cbc69763.PNG">

After apigee edge connection setup Below are working 1. Apps 2. Products 3. Catalogs
Not working is

Analytics. whenever i search for analytics its showing me page not found. Sometimes its showming me no errors other than page not found sometimes i got as error on [transaltion.](url)

**Comment by kbielawiec** [comment]
From Salesforce ticket: 

The following error is also seen on the site. I was able to reproduce this by reverting to an older version prior to [commit 3e25453 in apigee/apigee-edge-drupal](https://github.com/apigee/apigee-edge-drupal/commit/3e2545350f0abbc0f0a64d0572004eddf775c7e2). I have not been able to reproduce the page not found error.

`Error: Call to undefined method Drupal\apigee_edge\Entity\DeveloperApp::hasTranslation() in Drupal\quickedit\QuickEditController->metadata() (line 150 of /app/portal/web/core/modules/quickedit/src/QuickEditController.php) #0 [internal function]: Drupal\quickedit\QuickEditController->metadata(Object(Symfony\Component\HttpFoundation\Request)) #1 /app/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #2 /app/portal/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #3 /app/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #4 /app/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #5 /app/portal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #6 /app/portal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /app/portal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /app/portal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /app/portal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /app/portal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /app/portal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /app/portal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /app/portal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /app/portal/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /app/portal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 {main}.`

**Comment by mxr576** [comment]
Provided some input here: https://github.com/apigee/apigee-edge-drupal/issues/262

**Comment by arlina-espinoza** [comment]
This is an apigee_edge issue, following up in:
https://github.com/apigee/apigee-edge-drupal/issues/262

:)
