### ISSUE TITLE
Kickstart profile hides actual username, hard to connect to REST API

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#270]
## Description
The current release 1.5.0 hides the username from the system, and must autogenerate it in the background.  This makes it very hard to use the [Expose REST APIs to interact with API Docs](https://www.drupal.org/docs/8/modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs#comment-13282168) instructions since the `basic_auth` module uses the username to authenticate.  The username is hidden in the edit user form and shown in the view user profile incorrectly (displays **First Name** **Last Name**)

## To Reproduce
1. Create a new user with **First Name** "Test", **Last Name** "User", **Email** test@example.com".
2. View the user's profile page, the username will be 
<img width="484" alt="user-view" src="https://user-images.githubusercontent.com/613093/66067338-385eac00-e500-11e9-9585-fbe9a457ea84.png">

### Option A: Username and password can be used 
1. The username would be properly displayed
2. The username would be chosen during registration
3. The user could use username or password to log in

### Option B: Username is not used in system
1. The system does not depend anywhere on username.

**Comment by kscheirer** [comment]
Yeah, there's the account `name` vs (`first_name` + `last_name` fields). In some cases we're overriding the templates to display the friendlier "first last". We used to use https://www.drupal.org/project/realname to catch most instances of user name display, I havent evaluated its status for D8.

**Comment by shadcn** [comment]
@cnovak @kscheirer PR ready for review: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/274

**Comment by kscheirer** [comment]
This fix looks good, user name field should display user name field :) I notice on the `/admin/people` page, the `Username` column is displaying first+last instead of the typical account name, is that ok @cnovak ?

<img width="1370" alt="Screen Shot 2019-10-10 at 10 29 50 AM" src="https://user-images.githubusercontent.com/283628/66592026-117c2780-eb49-11e9-9771-96b59006fea8.png">

**Comment by cnovak** [comment]
Nice catch @kscheirer , looking into this.

**Comment by arunz6161** [comment]
Revisit this after #280 is done and ensure kickstart is not overwriting username.
