### ISSUE TITLE
Uninstalling Forum module breaks main menu

### ISSUE THREAD

**Issue by elibyrd** [apigee/apigee-devportal-kickstart-drupal#276]
**Describe the bug**
The installation profile adds a Forum link to the main menu that cannot be deleted. If the Forum module is uninstalled, any page that would display this menu link (by default, all non-admin pages) will white screen. The administrative page for whatever menu houses this link (by default, Main Navigation) will also white screen, making it impossible to disable the menu link without first reinstalling the Forum module.

If the menu link was disabled before uninstalling the Forum module, the administrative page for its menu is still inaccessible.

**To Reproduce**
1. Uninstall the Forum module
2. Go to Admin -> Structure -> Menus
3. Edit the Main Navigation menu (or whichever menu you've place the Forum link)
4. See whitescreen error
5. Go to Admin -> Reports -> Recent log messages to see exact error message: _Symfony\Component\Routing\Exception\RouteNotFoundException: Route "forum.index" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName()_

**Expected behavior**
Ideally, uninstalling the Forum module would delete this menu link. If that is impossible, prevent uninstalling the Forum module with an appropriate message.

**Additional context**
Some developer portals will not host any forum content and therefore would want to uninstall the Forum module.

**Version Info**
Drupal 8.7.8
apigee/apigee_devportal_kickstart 1.5.0 (according to composer)

**Comment by arunz6161** [comment]
@elibyrd Thanks for logging this bug with relevant information. We will triage this in the next sprint and update soon.

**Comment by shadcn** [comment]
@elibryd we have a fix for this here: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/279. We are going to review this now.
