### ISSUE TITLE
Document migration steps

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#280]
Migration tool is ready to be released. We need to document the steps mentioned on https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/269

**Comment by jbennett13** [comment]
Draft for review and comment: https://docs.google.com/document/d/1yQ4U1Qe6Vl5XjuhFu93q4V6g3CL15qCepS8cH7M7WiU/edit?usp=sharing

**Comment by jbennett13** [comment]
Updates published:  https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/migrate-drupal-7-developer-portal-entities
