### ISSUE TITLE
"Enable demo content" screen is unreadable in black

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#282]
**Describe the bug**
<img width="942" alt="Screen Shot 2019-11-06 at 12 45 16 PM" src="https://user-images.githubusercontent.com/613093/68336718-d0b5f680-0093-11ea-8997-ef769ec992f7.png">

**To Reproduce**
1. Run through install process

**Version Info**
8.x-1.x and some versions lower

**Comment by kford** [comment]
Confirming same as of today

**Comment by shadcn** [comment]
I just started seeing this too. This is happening on the monetization step for me.
