### ISSUE TITLE
Display expired credentials

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-devportal-kickstart-drupal#287]
PR https://github.com/apigee/apigee-edge-drupal/pull/290 was merged. We need to update kickstart to show expired credentials on the Apps listing page.

See also https://github.com/apigee/apigee-edge-drupal/issues/156

**Comment by arlina-espinoza** [comment]
@arshad Would a fix for this require a new release of `apigee_edge` module that includes https://github.com/apigee/apigee-edge-drupal/pull/290?

**Comment by shadcn** [comment]
@arlina-espinoza Yes. This depends on https://github.com/apigee/apigee-edge-drupal/pull/290
