### ISSUE TITLE
Search results not showing API docs

### ISSUE THREAD

**Issue by kiranjyoth** [apigee/apigee-devportal-kickstart-drupal#289]
**Describe the bug**
API Docs from API Catalog entity are not indexed by core search. 

**To Reproduce**
1. Fresh install of Apigee Developer portal Kickstart
2. Click on 'search input'
3. Add keyword 'payment'
3. Perform search
4. Results not showing the API docs for the keyword payment

**Expected behavior**
When performing global search, results should also include API docs.

**Screenshots**
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1490213/69752122-67ab2700-1105-11ea-82ac-506a75b2e6ea.png">

**Additional context**
I tried Search API and it provides a way to index content and the fields in this entity type. Just wondering if we could extend this entity to be included in global search by default. 

**Version Info**
drupal/core                                        8.7.10 
drupal/apigee_api_catalog                1.0.0
drupal/apigee_edge                           1.2.0

Thank you!

**Comment by shadcn** [comment]
@kiranjyoth The default search shipped with Kickstart indexes Node entity types only. AFAIK there's no immediate plan to support search for custom entities out of the box. 

Suggestion: The [Search API](https://www.drupal.org/project/search_api) module might help with this.

**Comment by kiranjyoth** [comment]
@arshad Thanks! We've are using Search API for now and it works as needed.
