### ISSUE TITLE
Verify compatibility with Drupal 8.8.0

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-devportal-kickstart-drupal#291]
Drupal core 8.8.0 was released on 12/04. We should check for compatibility with it, and work all the possible config changes from the standard profile into the kickstart config, and re-export default content.
Note: from reading the release notes, it sounds like the admin media config (views) has probably changed, for example.

**Comment by shadcn** [comment]
Thanks @arlina-espinoza I'm going to start looking into this.

**Comment by cnovak** [comment]
Need to also look into #295 to close this issue.

**Comment by cnovak** [comment]
The instructions for upgrading to Drupal core 8.8.0 has been updated w/more clear instructions:

> If you have the contributed Pathauto module enabled, you must update to the latest version of Pathauto before or at the same time as you update to Drupal 8.8.0.

This means we do not have to worry about people needing to upgrade to pathauto 1.6 , and in a separate step upgrading to Drupal 8.8.0 any more.

**Comment by shadcn** [comment]
This is done. Just need a new release now.
