### ISSUE TITLE
Drupal 8.8.0: Warning message about media module image style

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#295]
**Describe the bug**
On the status page as of Drupal 8.8.0, there is a warning message saying:
> The default display for the Image media type is not currently using an image style on the Image field. Not using an image style can lead to much larger file downloads. If you would like to change this, add an image style to the Image field.

Can we fix this for users automagically, or at least document what image style to use?

**To Reproduce**
1. Upgrade Kickstart to Drupal core 8.8.0 using Apigee Edge PR https://github.com/apigee/apigee-edge-drupal/pull/305
2. Go to **Reports > Status report** in admin toolbar 
3. View message:

<img width="671" alt="Screen Shot 2019-12-12 at 4 29 22 PM" src="https://user-images.githubusercontent.com/613093/70759963-fa9ab280-1cfc-11ea-89c5-b8741e77c7bd.png">

**Version Info**
Kickstart 8.x-1.7, with Apigee Edge https://github.com/apigee/apigee-edge-drupal/pull/305

**Comment by arlina-espinoza** [comment]
I'm thinking perhaps just a configuration export from 8.8.0 would fix it, but we'd need to test.

**Comment by arlina-espinoza** [comment]
Note: We are using image styles/responsive images via View modes for everything, even hero images, so technically that warning isn’t actually a problem. So, we can basically do the same thing core did, to set the default display to use Large, and that should fix it.
(Thanks to @jacine!)
