### ISSUE TITLE
Apigee Developer portal kick start not displayed correctly in IE 10 or IE 11 (With default Kick start theme enabled)

### ISSUE THREAD

**Issue by robinvaughan** [apigee/apigee-devportal-kickstart-drupal#296]
**Describe the bug**

I have followed the exact steps listed as below - 

> The following command will download Drupal core, the Apigee Developer Portal Kickstart profile, and their dependencies, into the MY_PROJECT directory:
> 
> composer create-project apigee/devportal-kickstart-project:8.x-dev MY_PROJECT --no-interaction
> The actual web root will be MY_PROJECT/web. You will need to point your web server to serve that directory. Then, visit the site in a web browser, and you'll be redirected to core/install.php, where you can run the installer like any Drupal site installation. Running the installation via web browser is recommended for the best experience.

Once the set up was installed I can see the default "Apigee Kickstart 8.7.10 (default theme)" is enabled with few default demo contents. The theme is rendered correctly and show the demo contents on Mozilla and Chrome but on IE 10 and IE 11 the contents are not getting rendered correctly.

**To Reproduce**

Install the Apigee Drupal DEV portal using composer and open the home page in IE 10 or IE 11. As you can see in the Home page screen shot the Navigation is broken, its not sticky, the back ground is missing, the block at the bottom of Home page the image is not displayed correctly etc.

**Expected behavior**
The default - "Apigee Kickstart 8.7.10 (default theme)" should render the Navigation, layouts etc correctly in IE 10 and IE 11.

**Screenshots**
![image](https://user-images.githubusercontent.com/22614059/71027217-cc6c0700-2130-11ea-91fa-36b0e8505f5b.png)

![image](https://user-images.githubusercontent.com/22614059/71027244-de4daa00-2130-11ea-956c-9b5ebe7f9dfe.png)

![image](https://user-images.githubusercontent.com/22614059/71027282-ee658980-2130-11ea-9368-367dc53ee66f.png)

**Additional context**
---

**Version Info**
Apigee Kickstart 8.7.10

**Comment by robinvaughan** [comment]
I still can not believe that such an awesome distribution can have such a kind of Bug for IE 11, not sure if I am missing some action which needs to be taken that would in turn fix the theme layout issue on Internet explorer but if any one can help me on that it would be very helpful and deeply appreciated.

The thing is the default theme - "Apigee Kickstart 8.7.10 " works fine on Mozilla , chrome perfectly but not on IE 10, IE 11 and also there are some minor glitches on Microsoft Edge browser.

**Comment by robinvaughan** [comment]
I again installed one more Fresh APIGEE Drupal kick start distribution with No Demo contents this time using Composer and just default configurations after that this is what I can see on Mozilla - 

![image](https://user-images.githubusercontent.com/22614059/71028154-c1b27180-2132-11ea-9e4e-3736b4dc2fba.png)

And this is how the home page gets rendered in IE 11 - 

![image](https://user-images.githubusercontent.com/22614059/71028201-dbec4f80-2132-11ea-98f3-163150e300a0.png)

**Comment by shadcn** [comment]
@robinvaughan I created a PR here for IE 11 support. Can you test and let me know if this works?

**Comment by robinvaughan** [comment]
Hello @arshad ,

Thanks a ton for your help on this. Well on IE 11 its looking almost perfect now. Let me tell you what I have done to start with .. I have copied and replaced this folder - "themes/custom/apigee_kickstart" at my local set up with the one from your Branch - https://github.com/arshad/apigee-devportal-kickstart-drupal/tree/296-add-ie11-ponyfill 

After that I cleared the cache. I tested first on IE 10/IE 11 without **logging in (Anonymous User)** and I can see that all the pages are coming fine except this one page. When I see the API listing page - /apis I see this on IE 11 - 

![image](https://user-images.githubusercontent.com/22614059/71165131-5376c780-2276-11ea-9e2e-23d25ff4746e.png)


But when I see the same page - /apis on IE 10 (I have changed it using Emulator in IE 11 to IE 10) it comes fine, see below - 

![image](https://user-images.githubusercontent.com/22614059/71165315-a9e40600-2276-11ea-9e21-fae282860221.png)

**Comment by robinvaughan** [comment]
Another thing I noticed is when I login as Admin on Local vanilla kick start portal with your new changes. I can see that the old issue again pops out in both IE 10 and IE 11 with CSS and JS aggregator switched on as below - 

![image](https://user-images.githubusercontent.com/22614059/71165787-7b1a5f80-2277-11ea-8e37-99aa5692242d.png)

Once the CSS and JS aggregator are checked I see the Home page on IE 10 and IE 11 as below -

![image](https://user-images.githubusercontent.com/22614059/71165878-9edda580-2277-11ea-893b-6db8676f16a5.png)
![image](https://user-images.githubusercontent.com/22614059/71165909-ad2bc180-2277-11ea-971b-7c8a5e356af8.png)

And there seems to be some JS error due to which the POP out Admin menu stops working. Strage part is when I disable the CSS/JS aggregation from the Performance page then again things start to work on IE 10 and IE 11 as logged in with my Admin account.

So with  **CSS/JS aggregation switched off** from the Performance page I again checked on IE 10 and IE 11 with my Admin login - 
![image](https://user-images.githubusercontent.com/22614059/71166136-157aa300-2278-11ea-84f3-2e6a29468155.png)

Things start to come back to normal after this on IE10/IE11 - 
![image](https://user-images.githubusercontent.com/22614059/71166247-4c50b900-2278-11ea-802f-990fd1786a0c.png)

But the API listing page still works only in IE 10 and not in IE 11 even when you are logged in as Admin.

Am I on the right track or we need to implement your new changes in a different way over our Local set up , Please let me know.

**Comment by shadcn** [comment]
@robinvaughan Thanks for the detailed write-up. I'm going to look into the aggregation issue.

**Comment by robinvaughan** [comment]
@arshad .. are you also facing the aggregation issue at your end when you login as Admin on vanilla Kickstart distribution with you new changes on IE 10 and IE 11?

**Comment by shadcn** [comment]
@robinvaughan Yes. I've been able to reproduce it. I'm looking into it now.

**Comment by shadcn** [comment]
@robinvaughan OK fixed it. You can test again. This should also take care of the APIs page as well.

![Dashboard](https://user-images.githubusercontent.com/124599/71188876-399bab80-229b-11ea-9d9f-5389bf2c66f7.jpg)

**Comment by earth2marsh** [comment]
Just a note based on the topic... **IE10 support is not in scope** for this project as Microsoft's support window is closing in Jan, 2020: https://support.microsoft.com/en-us/help/4488955/support-ending-for-internet-explorer-10

Drupal itself dropped support with 8.4.x: https://www.drupal.org/node/2897971

**Comment by robinvaughan** [comment]
Hello @arshad, I tested again today and Yes this issue related to CSS/JS not working on IE 11/10 when user logs in with Admin Account and CSS/JS aggregation is turned on is - FIXED.

Thanks again for your fix.

How ever the API page still DO NOT show up correctly in IE 11 as you can see below - 

![image](https://user-images.githubusercontent.com/22614059/71304297-cd2fc200-23ea-11ea-85f5-bf368d1df631.png)

I tested with Admin login and also as Anonymous user but in both cases I see same output on API page as above in IE 11.

The strange part is this API page comes fine in IE 10 though its not supported version as I can see in the note above by - @earth2marsh

**Comment by robinvaughan** [comment]
Hello @arshad,

Just a small update. If I add this one line in the file you see below - 

![image](https://user-images.githubusercontent.com/22614059/71355462-1d528400-25a5-11ea-9ecd-2d2cb1bf2875.png)


The API's listing page comes fine on IE 11 as you can see below - 

![image](https://user-images.githubusercontent.com/22614059/71355524-5c80d500-25a5-11ea-95bf-c01861fc61fd.png)


Having done that we are good to go with all the changes that we have done till now, just thought to inform you.

Thanks,
Robin Vaughan

**Comment by shadcn** [comment]
@robinvaughan This worked. I added the fix. We're going to merge the PR and create a new release soon. Thank you for your help testing this. IE support is a big win.

**Comment by robinvaughan** [comment]
Thanks a lot @arshad ! :)
