### ISSUE TITLE
Why Apigee Kickstart custom theme 8.7.6 not highlighting the form fields with Red color upon custom or Default validation error?

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#299]
**Describe the bug**
Originally posted on Apigee community: https://community.apigee.com/questions/78019/why-apigee-kickstart-custom-theme-876-not-highligh.html

------------------------------------------------
I am working on Drupal 8 Developer portal, and I have enabled Apigee Kickstart 8.7.6 theme.

I have altered the user registration form by adding some custom fields and also I have added some custom validation on the form, but the problem is that it is not highlighting all fields red and also not showing error message in red color.

The another issue with Apigee profile default validation is that it is not highlighting all empty fields but showing only first field as required and if we enter value for the first field then it is highlighting 2nd empty field and if we enter 2nd value then it is highlighting only 3rd field and so on.

How I can bring this behavior back to default(ilke Bartik theme) where all fields with error will be marked red and also all fields should highlighted in the first go and should not show error one by one field.

Please suggest some way to resolve this issue.

------------------------------------------------

**To Reproduce**
**Expected behavior**

**Screenshots**

**Additional context**

**Version Info**
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

**Comment by shadcn** [comment]
@arunz6161 I pushed a fix for this https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/301

This can be part of the 8.x-1.9 release.
