### ISSUE TITLE
Install error on aws EC2 with php 7.3

### ISSUE THREAD

**Issue by kbielawiec** [apigee/apigee-devportal-kickstart-drupal#304]
Receiving the following error when installing kickstart on aws EC2 with php 7.3

`[devportal www]$ php composer.phar create-project apigee/devportal-kickstart-proje ct:8.x-dev devportal --no-interaction
Installing apigee/devportal-kickstart-project (8.x-dev 6266932b07abe4c23a746a7e9414c2fcf536bee9)
- Installing apigee/devportal-kickstart-project (8.x-dev 6266932): Cloning 6266932b07
Created project in devportal
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

ext-mbstring
ext-bcmath
drupal/core ^8.6
easyrdf/easyrdf ^0.9
drupal/commerce ^2.13

sudo yum install php-pear php7.3-curl php7.3-dev php7.3-gd php7.3-mbstring php7.3-zip php7.3-mysql php7.3-xml

Problem 1
- easyrdf/easyrdf 0.9.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.1 requires ext-mbstring * -> the requested PHP extension mbstring is miss ing from your system.
- easyrdf/easyrdf 0.9.0-rc.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.0-rc.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.0-rc.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.0-rc.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.0-rc.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
- easyrdf/easyrdf 0.9.0 requires ext-mbstring * -> the requested PHP extension mbstring is miss ing from your system.
- drupal/commerce 2.14.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
- drupal/commerce 2.15.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
- drupal/commerce 2.16.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
- drupal/commerce 2.x-dev requires ext-bcmath * -> the requested PHP extension bcmath is missin g from your system.
- drupal/commerce 2.13.0 requires drupal/core ^8.6 -> satisfiable by drupal/core[8.6.0, 8.6.0-a lpha1, 8.6.0-beta1, 8.6.0-beta2, 8.6.0-rc1, 8.6.1, 8.6.10, 8.6.11, 8.6.12, 8.6.13, 8.6.14, 8.6.15, 8.6.16, 8.6.17, 8.6.18, 8.6.2, 8.6.3, 8.6.4, 8.6.5, 8.6.6, 8.6.7, 8.6.8, 8.6.9, 8.7.0, 8.7.0-alpha1 , 8.7.0-alpha2, 8.7.0-beta1, 8.7.0-beta2, 8.7.0-rc1, 8.7.1, 8.7.10, 8.7.11, 8.7.2, 8.7.3, 8.7.4, 8. 7.5, 8.7.6, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8 .x-dev, 8.9.x-dev].
- drupal/core 8.6.0 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.0-alpha1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9. 0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.0-beta1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0 , 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.0-beta2 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0 , 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.0-rc1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.10 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.11 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.12 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.13 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.14 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.15 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.16 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.17 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.18 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.2 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.3 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.4 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.5 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.6 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.7 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.8 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.6.9 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0-alpha1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9. 0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0-alpha2 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9. 0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0-beta1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0 , 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0-beta2 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0 , 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.0-rc1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.10 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.11 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9 .0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.2 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.3 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.4 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.5 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.6 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.7 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.8 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.9 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.7.x-dev requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.0 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.0-alpha1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9. 0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.0-beta1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0 , 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.0-rc1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.1 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9. 0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.8.x-dev requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- drupal/core 8.9.x-dev requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].
- Installation request for drupal/commerce ^2.13 -> satisfiable by drupal/commerce[2.x-dev, 2.1 6.0, 2.15.0, 2.14.0, 2.13.0].

To enable extensions, verify that they are enabled in your .ini files:
- /etc/php.ini
- /etc/php.d/10-opcache.ini
- /etc/php.d/20-bz2.ini
- /etc/php.d/20-calendar.ini
- /etc/php.d/20-ctype.ini
- /etc/php.d/20-curl.ini
- /etc/php.d/20-dom.ini
- /etc/php.d/20-exif.ini
- /etc/php.d/20-fileinfo.ini
- /etc/php.d/20-ftp.ini
- /etc/php.d/20-gd.ini
- /etc/php.d/20-gettext.ini
- /etc/php.d/20-iconv.ini
- /etc/php.d/20-json.ini
- /etc/php.d/20-mysqlnd.ini
- /etc/php.d/20-pdo.ini
- /etc/php.d/20-phar.ini
- /etc/php.d/20-posix.ini
- /etc/php.d/20-shmop.ini
- /etc/php.d/20-simplexml.ini
- /etc/php.d/20-sockets.ini
- /etc/php.d/20-sqlite3.ini
- /etc/php.d/20-sysvmsg.ini
- /etc/php.d/20-sysvsem.ini
- /etc/php.d/20-sysvshm.ini
- /etc/php.d/20-tokenizer.ini
- /etc/php.d/20-xml.ini
- /etc/php.d/20-xmlwriter.ini
- /etc/php.d/20-xsl.ini
- /etc/php.d/30-mcrypt.ini
- /etc/php.d/30-mysqli.ini
- /etc/php.d/30-pdo_mysql.ini
- /etc/php.d/30-pdo_sqlite.ini
- /etc/php.d/30-wddx.ini
- /etc/php.d/30-xmlreader.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`

**Comment by shadcn** [comment]
@kbielawiec It looks like you're missing `mbstring`. Can you run `php -m` and check if you have `mbstring` extension enabled?

![php-mbstring](https://user-images.githubusercontent.com/124599/73151385-7e113700-40e4-11ea-915d-29046c458ab2.gif)

**Comment by cnovak** [comment]
If you are missing mbstring, you should be able to use Yum to install: `sudo yum install php-mbstring`

**Comment by kscheirer** [comment]
It does look like mbstring and bcmath extensions are missing. But from the above, it looks like `sudo yum install ... php7.3-mbstring ...` was executed, which *should* install mbstring. Could be that they need to be enabled manually in php.ini.

You could also add them to composer.json, like https://github.com/thephpleague/climate/pull/110/files. I think that should work as well, but did not test this.

**Comment by cnovak** [comment]
Missed that @kscheirer, but the Yum command listed above seems to be inside the output of composer. @kbielawiec make sure/confirm that:
1. mbstring is installed on your system via Yum
2. `php -m` command @arshad listed above displays mbstring

If #2 does not verify mbstring extension is not installed in PHP, make sure to enable the extension To enable extensions, verify that they are enabled in your `/etc/php.ini` config file as the output you gave suggests.

**Comment by shadcn** [comment]
@kbielawiec Did you figure this out?

**Comment by cnovak** [comment]
Closing issue
