### ISSUE TITLE
Document Kickstart having monetization added

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#310]
Kickstart will now install monetization if you use a monetized enabled org. However, there isn't any documentation about this.

If you have a monetization enabled org, when you install Kickstart it will ask if you want to install Monetization.

**Comment by shadcn** [comment]
Here's a start https://www.drupal.org/docs/8/modules/apigee-monetization/enable-the-apigee-monetization-add-credit-module#step-1-install-the-required-monetization-and-commerce-modules

**Comment by cnovak** [comment]
I updated the issue to be more clear - this issue is to update the Kickstart project page (maybe) and documentation so that it is clear that Kickstart can enable monetization for you.

Things to document:

1. Need to make it clear that Kickstart can set up monetization for you. I talked to someone that did not realize this feature is part of Kickstart. Might be good to mention on project page summary.
2. What do you need to do to get Kickstart to enable monetization? Do you just need a monetized org? I believe you also need to have commerce module installed since Kickstart does not have commerce in it's composer.json. Or is it that you need to add commerce only if you want add credit to be configured? 
3. We should point out that if you [install Kickstart using our instructions](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-installation-instructions), the `composer create-project command` will create a main composer.json file that has [monetization and commerce installed](https://github.com/apigee/devportal-kickstart-project-composer/blob/8.x/composer.json#L20). If you are not using monetization, you can run `composer remove drupal/apigee_m10n drupal/commerce` to remove the unneeded modules.

**Comment by cnovak** [comment]
@arshad can you give details on the logic in Kickstart install for question #2 above?

**Comment by shadcn** [comment]
If you want to set up **monetization only**, you need:

1. A monetized organization (this is determined automatically during Kickstart installation based on the connection information provided). If Kickstart finds a monetized organization during installation it will prompt if you want to enable monetization.

If you want **monetization** and **add credit**, you need:
1. A monetized organization.
2. The commerce and address module dependencies (which comes out of the box if you install Kickstart using the composer project, as noted in 3 above).

See also: `https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/8.x-1.x/src/Installer/ApigeeDevportalKickstartMonetization.php`

**Comment by jbennett13** [comment]
Draft of proposed changes to Kickstart and Monetization docs and project pages attached for review:  https://docs.google.com/document/d/1TU3Vwwb_pe6pAv_6X_na96BCAdbiYtl7PdK-Y1bpLsk/edit?usp=sharing

Will this also resolve #330?

**Comment by jbennett13** [comment]
Updates published:  https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/enable-monetization (and elsewhere)
