### ISSUE TITLE
Reduce the size of the default images for the content created during install process

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-devportal-kickstart-drupal#311]
The images used on the content created during the install process are huge.
We should reduce the size of these files. 

nasa-89116-unsplash.jpg is 6 MB

These sizes are causing the image styles to fail at times, especially on local machine which has memory_limit set to 128M

**Comment by arunz6161** [comment]
@giteshk can we consider increasing memory_limit ? We fear that making this change might result in a poor demo experience for others using different screens.

**Comment by giteshk** [comment]
@arunz6161 totally agree we want to the experience to be good. But a 5 MB image file is a bit much. 

Direction is find a good happy medium. :)

**Comment by cnovak** [comment]
@arshad make sure to check out @jacine 's notes on this: https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/317#issuecomment-583201184

**Comment by shadcn** [comment]
Thanks @jacine that was really helpful.

So based on the notes here (https://gist.github.com/jacine/cb11830d71f93f3c4d178eddc2cf4ab8) I think we should keep the hero images as is but we can resize the cards and articles ones (nasa pictures). 

Right now they are 5k+px wide (we have one at 8k+) and the largest we use is at 2190px for a 3x screen.
