### ISSUE TITLE
Avatar used for users is fuzzy

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#316]
If you go to `/forum/security-tokens-documentation` the avatar looks lo res, can we put a better one in?
<img width="660" alt="avatar" src="https://user-images.githubusercontent.com/613093/73987092-2f3d7b80-48f4-11ea-8ac6-6588c8a09459.png">

**Comment by shadcn** [comment]
This can be closed as duplicate of https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/311 (We're handling all images there)
