### ISSUE TITLE
Installation scripts for Apigee Kickstart for private cloud

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-devportal-kickstart-drupal#318]
**Is your feature request related to a problem? Please describe.**
To install the Apigee kickstart on private cloud install today we have to manually follow through a huge list of steps documented [here](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud)

There is always a possibility of human error. 

**Describe the solution you'd like**
Can we automate these steps with a scripts that can help expedite the install.

**Comment by Abdul-Kinadiyil** [comment]
Any update on the planned release date for the scripts?

**Comment by cnovak** [comment]
Hello @Abdul-Kinadiyil , we have scripts now and are currently going through a review in order to get them open sourced. I hope to have this out in about 2 weeks as a beta.

**Comment by cnovak** [comment]
We have now released [Ansible install scripts to speed up installation of Drupal 8](https://github.com/apigee/devportal-kickstart-drupal-ansible-installer), check it out and add any issues or questions in the issue queue.
