### ISSUE TITLE
CSS for FAQs creates extra bottom border when <li> is used in FAQ body

### ISSUE THREAD

**Issue by jemisonf** [apigee/apigee-devportal-kickstart-drupal#322]
**Describe the bug**
When you add an FAQ with an html list in the body, the preview on the `faqs` page adds a thin gray border to the bottom of the last element of the list. I'm pretty sure the issue is this CSS selector:

```scss
li:last-child {
  border-bottom: solid 1px $gray-300;
}
```

From [here](https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/eb4836a4417c1616649a0c00f2ed7e034221036c/themes/custom/apigee_kickstart/src/sass/page/_page.faq.scss), which iirc could be changed to `> list:last-child` to only select `<li>` elements that are direct children of the `.item-list` element.

**To Reproduce**
1. Create an FAQ with the following body: 
  ```html
  <ol>
  	<li>hello</li>
  </ol>
```
2. Navigate to the `/faq` page

**Expected behavior**
Lists should display with a clear background and no border elements.

**Screenshots**
<img width="1147" alt="Screen Shot 2020-02-21 at 2 53 29 PM" src="https://user-images.githubusercontent.com/28904930/75078252-fdaedd80-54b9-11ea-86fe-665f0ce55b44.png">

You can see the underline under "hello" in the screenshot.

**Additional context**

**Version Info**
```
apigee/apigee-client-php                 2.0.4        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.9.0        A fast demo and starting point for Apigee Developer Portals.
```

**Comment by shadcn** [comment]
@jemisonf This is an awesome bug report. I pushed a fix for it. We'll review and merge: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/324

Thank you.

**Comment by jemisonf** [comment]
Thanks @arshad! Really appreciate the quick follow-up. I'll keep an eye out for the fix in the next release.
