### ISSUE TITLE
FAQ contents are not toggling properly in IE browser

### ISSUE THREAD

**Issue by mrdhanasekaran89** [apigee/apigee-devportal-kickstart-drupal#337]
Hi Team,

I am using Drupal 8 Apigee distribution in my project and noticed that FAQ contents are not toggling properly and by default, all the Q&A are in opened. 

Click on FAQs in the top menu.

Expected behavior: (Answer should be closed by default)
![image](https://user-images.githubusercontent.com/50447235/76731409-63be1600-6783-11ea-9e2c-1bd8372d7778.png)

Issue Screenshots: (by default Answers are opened)
![image](https://user-images.githubusercontent.com/50447235/76731295-193c9980-6783-11ea-8344-64a93b4762e9.png)

Kindly fix the issue and let me know once done.

Thanks
M.Dhanasekaran

**Comment by shadcn** [comment]
@mrdhanasekaran89 thanks for the report. Which IE version is this?

**Comment by mrdhanasekaran89** [comment]
Hi arshad,

I am facing this issue in IE 11.

**Comment by mrdhanasekaran89** [comment]
Team, any update on this issue?

**Comment by shadcn** [comment]
@mrdhanasekaran89 I’m looking into this today. I’ll let you know.

**Comment by shadcn** [comment]
@mrdhanasekaran89 I created PR #341 with a fix. 

![apigee-kickstart-faq-ie-11](https://user-images.githubusercontent.com/124599/77147634-21f4de80-6aa7-11ea-82ef-66e6acd569a8.gif)

**Comment by mrdhanasekaran89** [comment]
Hi arshad, Thanks for spending your time on this. Its working fine.

**Comment by mrdhanasekaran89** [comment]
Hi @arshad ,

I have taken latest copy of Apigee distribution through composer command. But still FAQs page issue is not fixed in IE browser. Is the code merged with Master branch?

Please confirm.

Thanks
M.Dhanasekaran

**Comment by shadcn** [comment]
@mrdhanasekaran89 The code has been merged but we have not made a new release yet. 

You could apply the fix temporarily as a patch.

1. Install `composer-patches`:

```
composer require cweagans/composer-patches
```

2. Add the following under `extra` in your root `composer.json` file:

```
    "patches": {
      "apigee/apigee_devportal_kickstart": {
        "Add core details polyfill and fix style": "https://patch-diff.githubusercontent.com/raw/apigee/apigee-devportal-kickstart-drupal/pull/341.patch"
      }
    },
```

3. Apply the patch.

```
composer install
```

Clear your cache and you should be ready to go.

When we tag a new release, it will tell you the patch no longer applies. You should be able to safely remove it from your `composer.json` file.
