### ISSUE TITLE
Add Hero Image dimensions as help text

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-devportal-kickstart-drupal#343]
The Hero Image on the homepage does not have a recommendation for dimension. Would be nice to have a help text which says what dimensions to expect.

![Screen Shot 2020-03-24 at 5 37 47 PM](https://user-images.githubusercontent.com/6208023/77479559-68737180-6df6-11ea-9a91-44c526e2c9a5.png)

**Comment by cnovak** [comment]
@giteshk do you remember what issue you saw w/different image sizes? This image should be responsive and work correctly w/any size.
