### ISSUE TITLE
SAML configuration removes Drupal core

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#355]
The [SAML Integration instructions](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/integrate-simplesamlphp-authentication) documentation removed Drupal core.

On executing the command composer require drupal/simplesamlphp_auth:3.x-dev drupal/simplesamlphp_custom_attributes --prefer-dist
Using version ^1.1 for drupal/simplesamlphp_custom_attributes
It gives below output and deletes the core folder

./composer.json has been updated
Removing package drupal/better_exposed_filters so that it can be re-installed and re-patched.
  - Removing drupal/better_exposed_filters (3.0.0-alpha6)
Deleting web/modules/contrib/better_exposed_filters - deleted
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (8.8.5

_Originally posted by @samhaldia in https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/234#issuecomment-614380545_

**Comment by cnovak** [comment]
@samhaldia I tried replicating your issue, but did not see your issue:

```
composer create-project apigee/devportal-kickstart-project:8.x-dev kickstart-saml
cd kickstart-saml
composer require drupal/simplesamlphp_auth:3.x-dev
```
After these commands, my core dir is intact:

```
% cd kickstart-saml
% ls
INSTALL.txt		example.gitignore	robots.txt		web.config
README.txt		index.php		sites
autoload.php		modules			themes
core			profiles		update.php
% ls core
CHANGELOG.txt			composer.json			modules
COPYRIGHT.txt			config				package.json
INSTALL.mysql.txt		core.api.php			phpcs.xml.dist
INSTALL.pgsql.txt		core.libraries.yml		phpunit.xml.dist
INSTALL.sqlite.txt		core.link_relation_types.yml	postcss.config.js
```
Are these the steps?

**Comment by arunz6161** [comment]
We are unable to reproduce the issue. Please reopen if you have more details.
