### ISSUE TITLE
Always show monetization step during install

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#356]
## Description

A user was testing monetization installing w/Kickstart and was never prompted for monetization even though she is connecting to a mint enabled org. We did not know why Monetization was not being installed with the installer.  We figured out that the monetization module was not part of her project because it was an older main composer file for Kickstart which did not have the Monetization module.

@arlina-espinoza pointed out that the root composer file must include the "drupal/apigee_m10n" and "drupal/commerce" packages.

# Solution
We should always show the monetization panel during installation when the org is a m10n enabled org. It could show the m10n configuration disabled and reason why so user knows this exists and they are not getting all features.

**Comment by shadcn** [comment]
I pushed a PR with a fix: https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/368
