### ISSUE TITLE
Documentation incorrect about how to get monetization installed?

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#357]
Our [installation instructions about Kickstart](https://www.drupal.org/node/3058326#s-installation-instructions) says you need monetization module installed for monetization to be installed during the Kickstart Install.  However, @arlina-espinoza said:
> the root composer file must include the "drupal/apigee_m10n" and "drupal/commerce" packages.

@arlina-espinoza can you verify this, and if so @jbennett13 can you update docs?

**Comment by jbennett13** [comment]
Chris - could you point to which part of the install instructions you are referring to?  I thought we had clarified in the docs that the **composer create** command uses the correct root composer file (containing the m10n and Commerce packages), and that you would only have to add or require M10n if you were using your own composer file and wanted to add M10n later.  I may just be missing a section that is unclear...

**Comment by cnovak** [comment]
Here is the page:
https://www.drupal.org/node/3058326#s-installation-instructions

> If you are installing Kickstart for use with a Monetization-enabled Apigee org and you are using the latest version of the apigee/devportal-kickstart-project in your main composer file, the installer prompts you to enable Monetization.
> 
> If you enter connection details for a Monetization-enabled Apigee org and you are not prompted to enable Monetization, see updating your main composer file to confirm you are using the latest version of Kickstart.
> 
> If you are using your own composer file and you want to enable Monetization, use the following command to add apigee_m10n to your project before running the web base installer:
> 
> composer require drupal/apigee_m10n --optimize-autoloader
> 
> The “--optimize-autoloader” flag is optional in the above command.

**Comment by arlina-espinoza** [comment]
@cnovak @jbennett13 If user is using their own composer then yes, they need to require apigee_m10n _and_ drupal/commerce. So I'd suggest to update the section with the following:


>If you are using your own composer file and you want to enable Monetization, use the following command to add apigee_m10n and drupal/commerce to your project before running the web base installer:
>
>composer require drupal/apigee_m10n drupal/commerce:"^2.16" --optimize-autoloader
>
>The “--optimize-autoloader” flag is optional in the above command.

**Comment by jbennett13** [comment]
Updated this section to clarify possible scenarios when installing with a M10n-enabled org:  https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-installation-instructions
