### ISSUE TITLE
Getting JS error on Nav toggle click event in Mobile view 

### ISSUE THREAD

**Issue by SajithAthukorala** [apigee/apigee-devportal-kickstart-drupal#372]
After  Updating apigee/apigee_devportal_kickstart (1.12.0 => 1.14.0): Getting JS error on home page and not working Nav toggle as expected in mobile .

The hamburger menu is not working on mobile phones and Tablets.
Observed in iPhone 11 Pro, iPhone 11, Galaxy S10, Galaxy tab S6, iPad Pro 11 

Chrome
![Screenshot from 2020 05 28 15 04 09 png PNG Image 1920 × 1080 pixels Scaled 85 ](https://user-images.githubusercontent.com/7125840/83125072-9e81ea00-a0f4-11ea-9d71-077980d74bde.png)

Firefox
![Screenshot from 2020 05 28 15 02 34 png PNG Image 1920 × 1080 pixels Scaled 85 ](https://user-images.githubusercontent.com/7125840/83125088-a6da2500-a0f4-11ea-898e-14db4b2e28d3.png)

**Comment by shadcn** [comment]
Bug confirmed. Looking into it.

**Comment by shadcn** [comment]
I pushed a PR to fix this. We should be tagging a new release soon. If you can't upgrade right away, you can fix this regression by updating `jquery` in your theme. `npm i jquery -D` should do it.

**Comment by cnovak** [comment]
@SajithAthukorala thanks for reporting this, the 1.15 release just went out with this fix.

**Comment by SajithAthukorala** [comment]
Thanks for the fix @arshad  @cnovak  , we downgrade the versions since we had to do immediate release , will update you guys !!! thanks again for the quick response
