### ISSUE TITLE
Question on SAML

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#373]
We are trying to do Single Signon with SAML. followed this following process

https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/integrate-simplesamlphp-authentication

While testing the URL. It is giving the Permission Access Denied issues. Can any one suggest

**Comment by kiranjyoth** [comment]
@pradeepgorle13 the documentation pages show how you can configure web server if its **Apache**. Configuring **Nginx** is a bit more involved. Please look at this community post https://community.apigee.com/questions/44115/sso-integration-via-saml-with-developer-portal-417.html?childToView=50268#answer-50268
The master process for php-fpm has no unix socket by default. In this case you have to use your localhost and port. 
Hope that helps!
