### ISSUE TITLE
Customization of API docs page

### ISSUE THREAD

**Issue by KNSivagami** [apigee/apigee-devportal-kickstart-drupal#375]
We need to do some customisation in the API doc page of the new kickstart module like old drupal 7 portal.

we need something like below

![image](https://user-images.githubusercontent.com/62534689/83235640-d39f4280-a1af-11ea-84cb-f309a1fb9db5.png)

In drupal 7 we configured in taxonomy-> smartdocs model. 
In kickstart it cannot be aligned in tab accordingly.

It is showing 
![image](https://user-images.githubusercontent.com/62534689/83235741-fdf10000-a1af-11ea-8da7-210ba061d20c.png)

Kindly help how to change the page view

Thanks in Adavnce

-- SIvagami

**Comment by kiranjyoth** [comment]
@KNSivagami Are you using 8.1.x or 8.2.x of the module **apigee_api_catalog** ?
This requires custom templating of custom entity / node type. 
For 8.1.x your naming convention will be something like **apigee-entity--apidoc--full.html.twig** 
and if its 8.2.x, 
Here is a link to naming conventions https://www.drupal.org/docs/theming-drupal/twig-in-drupal/twig-template-naming-conventions#s-nodes
Once you theme this template to your design, you will get closer to your original design. Hope that helps!

**Comment by KNSivagami** [comment]
Hi Jyothi

My Api catalog version is version: '8.x-1.2'
project: 'apigee_api_catalog'
Drupal is 8.3

Let me know how to proceed

Thanks,
Sivagami

**Comment by kiranjyoth** [comment]
@KNSivagami Documentation here shows you basic customization of your portal. https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/customize-your-developer-portal

But for your use case, you may need to create a sub-theme from kickstart theme. 
follow instructions here to start creating a sub-theme
https://github.com/apigee/apigee-devportal-kickstart-drupal/tree/8.x-1.x/themes/custom/apigee_kickstart#creating-an-apigee-kickstart-sub-theme

Once done you will need create or add your custom style sheets to your new sub-theme. 
Follow templating conventions provided here https://www.drupal.org/docs/theming-drupal/twig-in-drupal/twig-template-naming-conventions#s-nodes to theme your node / page templates.

**Comment by cnovak** [comment]
Thanks @kiranjyoth for answering, will close ticket but add comments if anything else is needed.
