### ISSUE TITLE
Custom Theme/Layout

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#380]
Hi Guys,

Do we have any proper documentation to create a Custom theme/Layout? We were able to get the Drupal 8(with Apigee Kickstarter) approved. Need some help on getting it started.

Thanks.,
Pradeep

**Comment by cnovak** [comment]
Hello Pradeep, we have some info on [how to subtheme Kickstart in our README](https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/6dd58a1e93e9d06536b2c79313a93b863610b0e7/themes/custom/apigee_kickstart/README.md#creating-an-apigee-kickstart-sub-theme) which should be able to help you. There is also [documentation on Drupal.org on theming](https://www.drupal.org/docs/theming-drupal). Let us know if you need any more info.

**Comment by pradeepgorle13** [comment]
Thanks Chris, Will definitely let you know.
