### ISSUE TITLE
Local Workspace Setup and Theming

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#383]
I was going through the last answer regarding the themes (how to start it and work on it). Below is the reference 
https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/380
But I realized that we need to have a local setup on our desktop for this. Or Do you suggest any other easy way to edit any current theme(apigee_devportal_kickstart) or create a new theme.
Any step by step document will be of great help as i am very new to Drupal 8 and trying to get it to my organization.
Required:
1. Step by Step document for the Local workspace setup for new Drupal Developers.
2. Step by Step document for creating a theme from base and adding modules accordingly for Developer Portal.
3. Step by Step document for adding features to the current default theme(Apigee Kickstart 8.9.0).

Can you please help me out in this.

Thanks.

**Comment by cnovak** [comment]
You might want to check out [Lando](https://docs.lando.dev/config/drupal8.html), here is an [article about getting started with Lando for local development](https://bhooraj.com/technology/development-evironment-for-drupal-8-with-lando/).

For theming, [check out my earlier post on theming resources](https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/380#issuecomment-641513954). 

To add features, you will need to create your own custom module that creates functionality or hooks into events to make modifications. [Here is a tutorial on Drupal 8 hooks].(http://www.drupal8.ovh/en/tutoriels/193/create-a-simple-module-to-use-drupal-8-hook-system)

There are a lot of resources out there:
* Google searches will bring up sites and blogs with tutorials and help
* [Drupal.org has documentation](https://www.drupal.org/documentation) to help you get started
* There are [books written about Drupal 8 development and theming](https://www.google.com/search?q=drupal+8+custom+development+theming+book&sxsrf=ALeKk02AEePV8bEL-siNjZPNI2gHcTPH4g:1592325450163&source=lnms&tbm=shop&sa=X&ved=2ahUKEwiwk8vG4obqAhX0KDQIHRt_A0oQ_AUoBHoECA0QBg&biw=1665&bih=1178)
* You can subscribe to learning sites such as [drupalize.me](https://drupalize.me)
* You can also [find a company to engage with to help you get started with your project](https://www.drupal.org/drupal-services). You can also talk to your Apigee client manager to get recommendations on partners that specialize in Apigee Developer portals.
