### ISSUE TITLE
Getting the Products to be displayed even without logging

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#388]
Hi,

Was trying to expose the API's/Products or create a product catalog with the Open API specification even without login. Do we have any option to do that. 

Currently we are seeing only the sample API's .Please see the screen shot below
![image](https://user-images.githubusercontent.com/56166711/86640110-022aed00-bfa8-11ea-8e45-efc0df66075a.png)

Can you please redirect me to the right place where i can get the connection and display the API's /Products under API's.
I was just going through some other developer portals and got a reference for you (developer.nationwide.com). Also attaching the screenshot below.
![image](https://user-images.githubusercontent.com/56166711/86640644-79608100-bfa8-11ea-9a11-65cb2bf2136b.png)

I went through the documentation but i don't see the products where i can see multiple proxies under it
https://www.drupal.org/docs/8/modules/apigee-api-catalog/install-the-api-catalog-module

Any help and direction would be very much appreciated.

Thanks.,

**Comment by cnovak** [comment]
I am not sure if I understand what you are asking, but I think you are saying the API Catalog is not populating from your proxies that you have in your org. The API Catalog does not get populated automatically from your proxies or API Products in Apigee, you need to manually create and upload the specs (or automate the process) when you [add an API Doc to your site](https://www.drupal.org/docs/8/modules/apigee-api-catalog/document-your-apis#s-add-a-new-api-doc).

**Comment by pradeepgorle13** [comment]
> I am not sure if I understand what you are asking, but I think you are saying the API Catalog is not populating from your proxies that you have in your org. The API Catalog does not get populated automatically from your proxies or API Products in Apigee, you need to manually create and upload the specs (or automate the process) when you [add an API Doc to your site](https://www.drupal.org/docs/8/modules/apigee-api-catalog/document-your-apis#s-add-a-new-api-doc).

Thanks Chris, That will help
