### ISSUE TITLE
Media doesn't Render on Pages, when browsed Anonymously

### ISSUE THREAD

**Issue by samhaldia** [apigee/apigee-devportal-kickstart-drupal#389]
## Description
When the Apigee Kickstart demo Content Installation is viewed Anonymously, Images doesn't appear to load, its visible only when a user is logged in

## Steps to Reproduce
1. Go to 'http://localhost/my_project/web/' and browse as anonymous user
2. Hero Images at Header, Cards Images are not rendering
3. Login as authenticated user those demo content images are visible

## Expected Behavior
The Images or media should be rendered to users in any situation (Anonymously or Authenticated)

## Screenshots
Anonymous
![image](https://user-images.githubusercontent.com/11740959/87054877-4248d480-c221-11ea-92fe-4f3f4de9eb01.png)

Authenticated
![image](https://user-images.githubusercontent.com/11740959/87056407-3231f480-c223-11ea-9e6d-1ea488b54fa1.png)

## Version Info

drupal/core                                               8.9.1
apigee/apigee-client-php                         2.0.5
apigee/apigee_devportal_kickstart           1.14.0
drupal/apigee_api_catalog                        1.2.0
drupal/apigee_edge                                  1.11.0

**Comment by arunz6161** [comment]
@samhaldia Looks like you have a local install of the portal. Are you using Nginx ? If yes, can you share the nginx config file here?

**Comment by samhaldia** [comment]
@arunz6161 yes its a local instance but of XAMPP, and i observed this issue comes after following Drupal Migration from 7 to 8 using DRUPAL MIGRATE UI module and  seems to be fine on fresh install though.

**Comment by samhaldia** [comment]
@arunz6161 I also setup a local fresh instance on nginx server , and i see the same issue, is there something specific related to nginx conf, it would be nice if you could share

**Comment by samhaldia** [comment]
I have observed, Its permissions to Anonymous users which gets overridden after Migration, it seems to be fine on allowing  Anonymous users for permissions: Use the Restricted HTML text format, View media
