### ISSUE TITLE
`npm audit` reports security vulnerabilities

### ISSUE THREAD

**Issue by zakiya** [apigee/apigee-devportal-kickstart-drupal#400]
## Description
`npm audi`t reports security vulnerabilities

## Steps to Reproduce
1. run `npm install` from the project root. 

## Actual Behavior
Terminal reports:
`found 302 vulnerabilities (299 low, 3 high) in 1301 scanned packages
  run `npm audit fix` to fix 301 of them.
  1 vulnerability requires manual review. See the full report for details.
`
Full report:
[audit_report.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/5003686/audit_report.txt)

**Comment by arlina-espinoza** [comment]
Fixed by #405 .
