### ISSUE TITLE
Not able to install Drupal8 using composer

### ISSUE THREAD

**Issue by Ramadevi-cts** [apigee/apigee-devportal-kickstart-drupal#401]
Getting below error while trying to download Drupal8.
[devportal@CTSINAZNPAPI04 www]$ composer create-project apigee/devportal-kickstart-project:8.x-dev devportal --no-interaction
Creating a "apigee/devportal-kickstart-project:8.x-dev" project at "./devportal"
Installing apigee/devportal-kickstart-project (8.x-dev 0a6aab5540df75136af4f5ef7dc7358ef1b3e199)
  - Installing apigee/devportal-kickstart-project (8.x-dev 0a6aab5): Cloning 0a6aab5540
Created project in /var/www/devportal
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
 
  Problem 1
    - drupal/commerce 2.20.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - drupal/commerce 2.19.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - drupal/commerce 2.18.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - drupal/commerce 2.17.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - drupal/commerce 2.16.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - drupal/commerce 2.x-dev requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for drupal/commerce ^2.16 -> satisfiable by drupal/commerce[2.x-dev, 2.16.0, 2.17.0, 2.18.0, 2.19.0, 2.20.0].
 
  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/20-bz2.ini
    - /etc/php.d/20-calendar.ini
    - /etc/php.d/20-ctype.ini
    - /etc/php.d/20-curl.ini
    - /etc/php.d/20-dom.ini
    - /etc/php.d/20-exif.ini
    - /etc/php.d/20-fileinfo.ini
    - /etc/php.d/20-ftp.ini
    - /etc/php.d/20-gd.ini
    - /etc/php.d/20-gettext.ini
    - /etc/php.d/20-iconv.ini
    - /etc/php.d/20-json.ini
    - /etc/php.d/20-ldap.ini
    - /etc/php.d/20-mbstring.ini
    - /etc/php.d/20-mysqlnd.ini
    - /etc/php.d/20-pdo.ini
    - /etc/php.d/20-pgsql.ini
    - /etc/php.d/20-phar.ini
    - /etc/php.d/20-posix.ini
    - /etc/php.d/20-shmop.ini
    - /etc/php.d/20-simplexml.ini
    - /etc/php.d/20-sockets.ini
    - /etc/php.d/20-sqlite3.ini
    - /etc/php.d/20-sysvmsg.ini
    - /etc/php.d/20-sysvsem.ini
    - /etc/php.d/20-sysvshm.ini
    - /etc/php.d/20-tokenizer.ini
    - /etc/php.d/20-xml.ini
    - /etc/php.d/20-xmlwriter.ini
    - /etc/php.d/20-xsl.ini
    - /etc/php.d/20-zip.ini
    - /etc/php.d/30-mysqli.ini
    - /etc/php.d/30-pdo_mysql.ini
    - /etc/php.d/30-pdo_pgsql.ini
    - /etc/php.d/30-pdo_sqlite.ini
    - /etc/php.d/30-wddx.ini
    - /etc/php.d/30-xmlreader.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by arlina-espinoza** [comment]
Hi @Ramadevi-cts ,

It looks like bcmath isn't installed for PHP on your system. On Linux and Mac, you would usually need to use your OS package manager to install it. If you specify what OS you are on we should be able to point you to more specific docs.

**Comment by Ramadevi-cts** [comment]
Hi Arlina,
Please find below details

Operating System: Red Hat Enterprise Linux Server 7.8 (Maipo)
               CPE OS Name: cpe:/o:redhat:enterprise_linux:7.8:GA:server
               Kernel: Linux 3.10.0-1127.13.1.el7.x86_64
               Architecture: x86-64

Thanks&Regards,
Ramadevi K.

**Comment by arlina-espinoza** [comment]
I believe something like this would work: `yum install php-bcmath`, and then you might need to restart your webserver: `service httpd restart` (if using apache)

**Comment by Ramadevi-cts** [comment]
Now getting below error:
Problem 1
    - drupal/commerce 2.x-dev requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
    - drupal/commerce 2.19.0 requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
    - drupal/commerce 2.20.0 requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
    - drupal/commerce 2.17.0 requires drupal/core ^8.7.7 || ^9 -> satisfiable by drupal/core[8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
    - drupal/commerce 2.18.0 requires drupal/core ^8.7.7 || ^9 -> satisfiable by drupal/core[8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
    - drupal/commerce 2.16.0 requires drupal/core ^8.7 -> satisfiable by drupal/core[8.7.0, 8.7.0-alpha1, 8.7.0-alpha2, 8.7.0-beta1, 8.7.0-beta2, 8.7.0-rc1, 8.7.1, 8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.2, 8.7.3, 8.7.4, 8.7.5, 8.7.6, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev].

**Comment by Ramadevi-cts** [comment]
Hi Team,

After doing configure changes for PHP FastCGI Process Manager (PHP-FPM) to run as user “nginx” instead of “apache.” , the nginx test page is not loading upon navigating to the server’s hostname or IP in a browser. Please provide the solution.

**Comment by arlina-espinoza** [comment]
> Now getting below error:
> Problem 1
> - drupal/commerce 2.x-dev requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
> - drupal/commerce 2.19.0 requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
> - drupal/commerce 2.20.0 requires drupal/core ^8.8 || ^9 -> satisfiable by drupal/core[8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
> - drupal/commerce 2.17.0 requires drupal/core ^8.7.7 || ^9 -> satisfiable by drupal/core[8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
> - drupal/commerce 2.18.0 requires drupal/core ^8.7.7 || ^9 -> satisfiable by drupal/core[8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev, 9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.2, 9.0.3, 9.0.x-dev, 9.1.x-dev].
> - drupal/commerce 2.16.0 requires drupal/core ^8.7 -> satisfiable by drupal/core[8.7.0, 8.7.0-alpha1, 8.7.0-alpha2, 8.7.0-beta1, 8.7.0-beta2, 8.7.0-rc1, 8.7.1, 8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.2, 8.7.3, 8.7.4, 8.7.5, 8.7.6, 8.7.7, 8.7.8, 8.7.9, 8.7.x-dev, 8.8.0, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.2, 8.9.3, 8.9.x-dev].

@Ramadevi-cts Could you post your complete `composer.json` file? And also what version of PHP you are on.

**Comment by Ramadevi-cts** [comment]
Attached composer file.

PHP version:
PHP 7.4.8 (cli) (built: Jul 23 2020 02:48:26) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

Thanks&Regards,
Ramadevi K.

**Comment by arunz6161** [comment]
Apigee support to follow up
