### ISSUE TITLE
Unable to connect to the Remote Database (when the Devportal app is on one linux Server and MariaDB on the other)

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#402]
I have two Linux Servers 
 1. Installed the Devportal on Server 1
 2. Installed the MariaDB on the Server 2
    
![image](https://user-images.githubusercontent.com/56166711/89339293-e7619c00-d66b-11ea-8a5d-cf5025ae4262.png)
By default the server is running on the port 3306.

So changed the file  "/var/www/devportal/web/sites/default/settings.php" as mentioned below
![image](https://user-images.githubusercontent.com/56166711/89339659-8ab2b100-d66c-11ea-9ef1-b3a808662ead.png)

 And when i restarted the server and tried to access the drupal site, I am getting the following error
![image](https://user-images.githubusercontent.com/56166711/89339985-0f053400-d66d-11ea-9e65-bce797548da9.png)

I even tried with http and https too.
Can you please let me know where are i am going wrong and I tried to look for the documentation and i didn't find any for the remote install of DB. 

Do I need to do any changes to the my.conf file, If so what would be the change.

================================================================
Updating after the above

Also, Please find the following Screenshot for 
![image](https://user-images.githubusercontent.com/56166711/89369129-367af180-d6ab-11ea-81d4-0e90433c88a3.png)

I tried some more uses cases and found that 
   Step 1. Called the command "mysql -u devportal -h DatabaseServerIP –p " from the server where Developer portal is installed.
   Step 2. It asked for a password since i haven't mentioned any password  in the above command.
   Step 3. After entering the correct password, I was able to see the following
               
![image](https://user-images.githubusercontent.com/56166711/89368451-940e3e80-d6a9-11ea-86d4-318943d10038.png)

Does that mean, I am able to get the remote connection of the Database but I am unable to connect to the Server after giving the correct credentials.

Please advise.

Thanks.

**Comment by pradeepgorle13** [comment]
@arlina-espinoza @minnur Can you suggest any options?

**Comment by pradeepgorle13** [comment]
@minnur if possible can we have a Webex so that I can share my screen to show where i am facing the issue.

**Comment by minnur** [comment]
Hi @pradeepgorle13 are you able to try install Kickstarter using local database (code and db on the same server) ? I would like to make sure this issue is relevant to the kickstarter.

**Comment by pradeepgorle13** [comment]
> Hi @pradeepgorle13 are you able to try install Kickstarter using local database (code and db on the same server) ? I would like to make sure this issue is relevant to the kickstarter.

@minnur When I installed using the kickstarter with the local Database(Code and db on the same server), It is working fine. But when i installed the DB on the other server and changing the settings.php, The error mentioned previously is being displayed.

**Comment by minnur** [comment]
@pradeepgorle13  From the errors I see in the screenshots you provided it looks like your DB is not accessible from remote. Yes most likely your server is not properly configured. Take a look here https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/ for my.cnf configuration.

**Comment by pradeepgorle13** [comment]
> @pradeepgorle13 From the errors I see in the screenshots you provided it looks like your DB is not accessible from remote. Yes most likely your server is not properly configured. Take a look here https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/ for my.cnf configuration.

Hi @minnur , I verified if you see my last point in the above 
I tried some more uses cases and found that
Step 1. Called the command "mysql -u devportal -h DatabaseServerIP –p " from the server where Developer portal is installed.
Step 2. It asked for a password since i haven't mentioned any password in the above command.
Step 3. After entering the correct password, I was able to connect to the remote DB server
![image](https://user-images.githubusercontent.com/56166711/89804195-d5677980-db01-11ea-985d-a2a5116e261c.png)


I called the server2(db server) from Server1(Devportal install location). I was able to access the Server2(db server) remotely from Server1.

**Comment by minnur** [comment]
This is a documentation page for the database configuration of Drupal https://www.drupal.org/docs/8/api/database-api/database-configuration

**Comment by pradeepgorle13** [comment]
> This is a documentation page for the database configuration of Drupal https://www.drupal.org/docs/8/api/database-api/database-configuration

Sure, Will let you know once i go through

**Comment by Shanli-Yu** [comment]
Is there any logs from the remote server where mariaDB is installed that indicates connection attempts from devportal?

**Comment by pradeepgorle13** [comment]
I

> Is there any logs from the remote server where mariaDB is installed that indicates connection attempts from devportal?

Hi @Shanli-Yu  I haven;t seen any logs in the dbserver regarding the connection. Now it just changed my view
  When i used the page and refreshed it, it isn't connecting to the dbserver and ai am not seeing any logs 

Even When i am connecting to the server with the devportal server to remote DBserver in the command line, I can see the success but not the logs updated
![image](https://user-images.githubusercontent.com/56166711/89816987-701d8380-db15-11ea-9778-a17cbb1982a1.png)

Logs are empty

**Comment by Shanli-Yu** [comment]
From what I can see so far of that error there are two existing causes and resolutions: 

1. The database is misconfigured and could not accept connections. 
This does not seem to be the issue since you were able to connect using mysql command

2. Connection settings are not configured correctly in settings.php. 
One of the things that can cause this was that the hostname was not specified as IP address. Can you double check if the hostname can be specified as IP?

**Comment by pradeepgorle13** [comment]
> From what I can see so far of that error there are two existing causes and resolutions:
> 
> 1. The database is misconfigured and could not accept connections.
>    This does not seem to be the issue since you were able to connect using mysql command
> 2. Connection settings are not configured correctly in settings.php.
>    One of the things that can cause this was that the hostname was not specified as IP address. Can you double check if the hostname can be specified as IP?

Yeah @Shanli-Yu , I used the IP in the settings.php. If you see the below image, I have updated with ip too... I just did all the permutations and combinations here. Anyways, I am going to change the userid and password.. Was just sharing this...
![image](https://user-images.githubusercontent.com/56166711/89820721-73b40900-db1b-11ea-87f8-b560e10410f8.png)

**Comment by Shanli-Yu** [comment]
The only other thing I can think of is the port number. I see that you are using 3306 which is the number for internal connection, can you update the port number to external connection and see if it will connect?

**Comment by pradeepgorle13** [comment]
> The only other thing I can think of is the port number. I see that you are using 3306 which is the number for internal connection, can you update the port number to external connection and see if it will connect?

Hi @Shanli-Yu , I also went through that route.. Can you please let me know if i am going in the right direction. Please find the following image for the port where mysql is open
![image](https://user-images.githubusercontent.com/56166711/89828065-8849ce80-db26-11ea-9649-2d2f499a538a.png)
Also adding other image for the Status
![image](https://user-images.githubusercontent.com/56166711/89828276-d4950e80-db26-11ea-928d-957c7e8e7309.png)
...

If this is not it, How can I update the port number to external connection and see if it will connect?

**Comment by pradeepgorle13** [comment]
> This is a documentation page for the database configuration of Drupal https://www.drupal.org/docs/8/api/database-api/database-configuration

@minnur I  checked for remote connections from the Devportal server to Database server through command line and it is absolutely working fine. Me and @Shanli-Yu discussed regarding this. Please find the my.conf file contents as following

![image](https://user-images.githubusercontent.com/56166711/89829252-4457c900-db28-11ea-99cf-144d227ec03d.png)

**Comment by pradeepgorle13** [comment]
> > The only other thing I can think of is the port number. I see that you are using 3306 which is the number for internal connection, can you update the port number to external connection and see if it will connect?
> 
> Hi @Shanli-Yu , I also went through that route.. Can you please let me know if i am going in the right direction. Please find the following image for the port where mysql is open
> ![image](https://user-images.githubusercontent.com/56166711/89828065-8849ce80-db26-11ea-9649-2d2f499a538a.png)
> Also adding other image for the Status
> ![image](https://user-images.githubusercontent.com/56166711/89828276-d4950e80-db26-11ea-928d-957c7e8e7309.png)
> ...
> 
> If this is not it, How can I update the port number to external connection and see if it will connect?

Any other options @Shanli-Yu ? Any place where i am going wrong

**Comment by Shanli-Yu** [comment]
@pradeepgorle13 Seems like there is no other configurations done to mysql based on the output then 3306 should be the correct port number.

**Comment by pradeepgorle13** [comment]
> @pradeepgorle13 Seems like there is no other configurations done to mysql based on the output then 3306 should be the correct port number.

@minnur  @shanli-yu So, Can you please suggest where i am going wrong.. I can setup some webex call if required..

**Comment by Shanli-Yu** [comment]
@pradeepgorle13 Since so far I cannot see any discrepancies in devportal settings, I highly recommend to first configure the server logging threshold if possible, to view the server access logs and confirm if the devportal node is at least making connection attempts, if there are attempts and based on the error the connection was refused, then the issue can be narrowed to server configuration rather than devportal configuration.

**Comment by pradeepgorle13** [comment]
> @pradeepgorle13 Since so far I cannot see any discrepancies in devportal settings, I highly recommend to first configure the server logging threshold if possible, to view the server access logs and confirm if the devportal node is at least making connection attempts, if there are attempts and based on the error the connection was refused, then the issue can be narrowed to server configuration rather than devportal configuration.

Sure @Shanli-Yu , Will see how far i can go and will update you guys tomorrow morning.

**Comment by pradeepgorle13** [comment]
@minnur @Shanli-Yu By any chance, Is it a Selinux issue ? I tried getting the logs and i wasn't able to get the detailed logs. IF you guys point me to any Mariadb logs enabling for debug. it would be of great help.

**Comment by pradeepgorle13** [comment]
I was able to resolve the issue. There was an issue with the SELinux as expected in my previous post. So i sort of disabled it.
