### ISSUE TITLE
Wanted to provide the App Owner Role to approve the App(which has a product) request raised

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#407]
Hi,

We have a API Owner/Product Owner in the organization.
A consumer logs into Developer Portal and creates a APP and selects a Product and submit the request for the Access.
The access needs to be manually approved by the API Owner/Product Owner. Now we are currently doing in the EDGE UI.
Do we have a way to approve in the Developer Portal. Means the complete process should be done in Developer Portal from creating a APP by Consumer and Approval of the APP by Producer.
Can you please share your solution.

Thanks.,

**Comment by kiranjyoth** [comment]
@pradeepgorle13 
This will fit your use case. https://www.drupal.org/project/sm_appdashboard_apigee

**Comment by pradeepgorle13** [comment]
> @pradeepgorle13
> This will fit your use case. https://www.drupal.org/project/sm_appdashboard_apigee

Thanks Kiran, Will install this and let you know if i have any issues regarding this.

**Comment by arunz6161** [comment]
@pradeepgorle13 I am closing this out as there are no plans on adding this feature in kickstart module. Hope the solution shared by @kiranjyoth works for you.
