### ISSUE TITLE
Remove secret fix once edge PR is accepted.

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-devportal-kickstart-drupal#411]
Secret in broken in https://github.com/apigee/apigee-edge-drupal/
https://github.com/apigee/apigee-edge-drupal/issues/467 fixes this functionality which was implemented in kickstart.

## Describe the solution you'd like 

Remove the functionality from kickstart once https://github.com/apigee/apigee-edge-drupal/pull/468 is merged.

**Comment by arlina-espinoza** [comment]
Update: We've updated the code that handles showing/hiding the secret in the `apigee_edge` module, and it essentially copies what is done in Kickstart, as it was a more robust implementation. Note that we named the secret element in apigee_edge module as `apigee_secret` not to conflict with Kickstart's `secret`. See PR https://github.com/apigee/apigee-edge-drupal/pull/496

This ticket is now basically a follow up for https://github.com/apigee/apigee-edge-drupal/pull/496 to evaluate if we can deprecate Kickstart's `secret` element, and do so if we can.
