### ISSUE TITLE
Remove app actions from kickstart once PR is merged in edge

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-devportal-kickstart-drupal#412]
There is no app actions in https://github.com/apigee/apigee-edge-drupal/
https://github.com/apigee/apigee-edge-drupal/issues/469 introduces this functionality which was implemented in kickstart.

## Describe the solution you'd like 

Remove the functionality from kickstart once https://github.com/apigee/apigee-edge-drupal/pull/470 is merged.

**Comment by arlina-espinoza** [comment]
@VladimirAus Could you take a look at my comment on https://github.com/apigee/apigee-edge-drupal/issues/469#issuecomment-708566020?

**Comment by arunz6161** [comment]
Please reopen if still an issue.
