### ISSUE TITLE
Issue with 'PDO'

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#413]
Getting this following error when trying to connect to the DB
![image](https://user-images.githubusercontent.com/56166711/90693894-a52c8300-e245-11ea-8fc6-925c9767ddd0.png)

I ran the following command for to yum install php modules (since instead of php, were asked to use rh-php)

yum install rh-php73-php.x86_64 rh-php73-php-bcmath.x86_64 rh-php73-php-common.x86_64 rh-php73-php-cli.x86_64 rh-php73-php-fpm.x86_64 rh-php73-php-gd.x86_64 	rh-php73-php-json.x86_64 rh-php73-php-mbstring.x86_64 rh-php73-php-mysql.x86_64 rh-php73-php-mysqlnd.x86_64 rh-php73-php-opcache.x86_64 rh-php73-php-pdo.x86_64  rh-php73-php-process.x86_64 rh-php73-php-xml.x86_64 rh-php73-php-xmlrpc.x86_64

**Comment by arlina-espinoza** [comment]
@pradeepgorle13  You can check if the PDO driver for MySQL is enabled: `php -i | grep -i pdo` and post the command's response here. It should specify if PDO is enabled and what drivers are available. Also make sure to restart your server after installing any PHP extension.

As another option, try the troubleshooting steps described in this page: https://www.drupal.org/docs/7/system-requirements/what-is-pdo#s-centos

**Comment by arlina-espinoza** [comment]
Marking as closed, feel free to reopen if you have further questions.
