### ISSUE TITLE
Wanted to Change the port from 80 to 8443

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#422]
Hi Guys,

When i try to login with "http://developer.abc.com:80" i am able to see the drupal page. I wanted to change to 8443 instead of 80, it means that "http://developer.adc.com:8443" should work for me. What are the file changes that are required to do that from my side. Can you please help me out.

Thanks.,

**Comment by arlina-espinoza** [comment]
Hi @pradeepgorle13,
This is not directly related to Kickstart, rather it is a configuration on your webserver, so you should check out the documentation of either apache or nginx (depending on what you are using). Here are some links that might get you started on your search:
- https://www.tecmint.com/change-apache-port-in-linux/
- https://www.tecmint.com/change-nginx-port-in-linux/

**Comment by pradeepgorle13** [comment]
> Hi @pradeepgorle13,
> This is not directly related to Kickstart, rather it is a configuration on your webserver, so you should check out the documentation of either apache or nginx (depending on what you are using). Here are some links that might get you started on your search:
> 
> * https://www.tecmint.com/change-apache-port-in-linux/
> * https://www.tecmint.com/change-nginx-port-in-linux/

Thanks @arlina-espinoza ,This helps me a lot. I was also browsing around and stumbled upon this and it worked for me. I thought that we can do something using the settings file. But thanks for correcting me. Just changed it and it is working fine for me now.
https://serverfault.com/questions/10854/nginx-https-serving-with-same-config-as-http
