### ISSUE TITLE
Pages rendering differently between IE and Chrome

### ISSUE THREAD

**Issue by BillMarx** [apigee/apigee-devportal-kickstart-drupal#427]
Hi,

   The Apigee kickstart in Drupal 8 looks good in chrome but the pages are not rendering correctly in IE.  Is a change required to fix this?

Thanks
Bill

**Comment by kscheirer** [comment]
IE can be tricky. What version are you using? Can you post a screenshot of what's incorrect?

**Comment by BillMarx** [comment]
Hi,

  We are running Version:

Thanks!!

[cid:image001.png@01D6959F.35AA72F0]

Differences:

【IE】
[cid:image002.jpg@01D6959F.35AA72F0]
[cid:image003.png@01D6959F.35AA72F0]
【Chrome】
[cid:image004.jpg@01D6959F.35AA72F0]

[cid:image009.png@01D6959F.4677E6D0]


[cid:image010.png@01D6959F.4677E6D0]
Bill Marx | Manager, IT Infrastructure
Prudential Financial | Global Technology​
30 Scranton Office Park | Scranton, PA 18507​
T 570 340 4266 | William.marx@prudential.com​
 [6170A350]

**Comment by kscheirer** [comment]
@BillMarx none of that message came through :) I think you'll have to post here on GitHub directly instead of via email.

**Comment by BillMarx** [comment]
[IEvsChrome.docx](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/5294230/IEvsChrome.docx)

**Comment by BillMarx** [comment]
Hi.. Uploaded a word doc with screen shots

Thanks
Bill

[cid:image001.png@01D695A1.CFC3D780]
Bill Marx | Manager, IT Infrastructure
Prudential Financial | Global Technology​
30 Scranton Office Park | Scranton, PA 18507​
T 570 340 4266 | William.marx@prudential.com​
 [6170A350]

**Comment by BillMarx** [comment]
Hi – Any update?

Thanks
Bill

[cid:image003.png@01D6973C.93384A20]
Bill Marx | Manager, IT Infrastructure
Prudential Financial | Global Technology​
30 Scranton Office Park | Scranton, PA 18507​
T 570 340 4266 | William.marx@prudential.com​
 [6170A350]


From: William Marx
Sent: Monday, September 28, 2020 2:15 PM
To: apigee/apigee-devportal-kickstart-drupal <reply@reply.github.com>; apigee/apigee-devportal-kickstart-drupal <apigee-devportal-kickstart-drupal@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [apigee/apigee-devportal-kickstart-drupal] Pages rendering differently between IE and Chrome (#427)

Hi.. Uploaded a word doc with screen shots

Thanks
Bill

[cid:image005.png@01D6973C.93384A20]
Bill Marx | Manager, IT Infrastructure
Prudential Financial | Global Technology​
30 Scranton Office Park | Scranton, PA 18507​
T 570 340 4266 | William.marx@prudential.com<mailto:William.marx@prudential.com>​
 [6170A350]

**Comment by zakiya** [comment]
I took a look at a fresh Apigee Kickstart install in IE 11 and was unable to find any discrepancies. I tried to reproduce the screenshots in the .docx file by logging in as different users, blocking external resources, and disabling aggregation. Next steps might be to see if there's anything telling in your console log and/or checking for user or network specific settings like Compatibility Mode. 
![IE11_-_Win7__Running_](https://user-images.githubusercontent.com/915352/94827591-7a455b00-03bd-11eb-84de-3d183eb482e4.png)

**Comment by BillMarx** [comment]
I think this may be do to the kickstart we installed (several months back).  Is there a way I can update only the kickstart and not lose all the setups we did?  I am running on RHEL

Thanks
Bill

[cid:image001.png@01D697FB.E3F925F0]
Bill Marx | Manager, IT Infrastructure
Prudential Financial | Global Technology​
30 Scranton Office Park | Scranton, PA 18507​
T 570 340 4266 | William.marx@prudential.com​
 [6170A350]

**Comment by arlina-espinoza** [comment]
@BillMarx You should be able to update as any other drupal module. There are some general instructions here: https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-upgrading-kickstart

Be sure to backup your site (database, code, files) before update, and run it against a development server before doing it on your production instance. The only tricky update might be the module `apigee_api_catalog`, so be sure to read and follow the release notes on the latest Kickstart you install (currently [8.x-1.21](https://www.drupal.org/project/apigee_devportal_kickstart/releases/8.x-1.21)).
