### ISSUE TITLE
PHP 7.3 end-of-support

### ISSUE THREAD

**Issue by rodrilapenta** [apigee/apigee-devportal-kickstart-drupal#429]
Hi,

I'm installing the Drupal 8 Develper Portal (on-prem) on RHEL 7.8 and I'm using the "Use Kickstart with Apigee Edge" tutorial, which makes me install PHP 7.3 using Remi's RPM repo. As far as I know, nowadays PHP 7.3 version's end-of-support is December 2020, so I was wondering if there's a chance that I can use a newer version (maybe 7.4), or maybe the docs are outdated.

Thanks

Rodrigo

**Comment by kscheirer** [comment]
Yeah the docs are just outdated, Drupal 8 supports PHP 7.4, https://www.drupal.org/docs/system-requirements/php-requirements.

**Comment by arunz6161** [comment]
To be discussed in deep dive.

**Comment by cnovak** [comment]
Thanks for info @rodrilapenta. I have updated the documentation to reflect 7.4 is the PHP version you should currently be using: https://www.drupal.org/node/3078995/revisions/view/12031127/12077856
