### ISSUE TITLE
Remove app warnings code from apigee_kickstart_enhancement.module

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-devportal-kickstart-drupal#431]
## Description

Warnings only present when profile is present making module is not fully functional.

<img width="1036" alt="Screen Shot 2020-09-29 at 6 30 15 pm" src="https://user-images.githubusercontent.com/1356166/94533077-0d797600-0282-11eb-912f-56684dbe15c7.png">

## Steps to Reproduce

1. Invalidate one of the APIs used by the application.
2. Warning only visible when installation profile is enable

## Proposal

Move the code from kickstart into the apigee edge module:

* https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/f1672a9822c6294f02cd87a4974aaa322e582fec/modules/custom/apigee_kickstart_enhancement/apigee_kickstart_enhancement.module#L110-L139
* https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/f1672a9822c6294f02cd87a4974aaa322e582fec/modules/custom/apigee_kickstart_enhancement/apigee_kickstart_enhancement.module#L258-L313

Apigee edge task: https://github.com/apigee/apigee-edge-drupal/issues/492

**Comment by shadcn** [comment]
@VladimirAus We're actually reworking this bit. 

In https://github.com/apigee/apigee-edge-drupal/pull/446 we removed the warning for revoked credentials. See @cnovak comment below:

> Currently the system will show a warning for apps that have revoked credentials. This should not be considered a warning state since revoking credentials is part of the maintenance of an app.

We need to update this kickstart now.

**Comment by arunz6161** [comment]
After fix in https://github.com/apigee/apigee-edge-drupal/issues/492 , remove the warnings from kickstart.

**Comment by shadcn** [comment]
@VladimirAus we are going to handle all app warnings in apigee_edge and remove the code from kickstart. I'll update the ticket to reflect this. 

Thank you for your help on this. Appreciate it.
