### ISSUE TITLE
Block related warnings in watchdog after installing with Drupal 9

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-devportal-kickstart-drupal#435]
When installing Kickstart with Drupal 9, several block related warnings are seen in watchdog.This is not blocking installation or preventing functionality from getting installed.
 
Example:
![image](https://user-images.githubusercontent.com/4062676/95525234-6f279780-0988-11eb-8f37-c8017e7e15fd.png)

## To Reproduce
1. Install latest Kickstart with Drupal 9, as described in https://github.com/apigee/devportal-kickstart-project-composer/pull/30
2. Enable demo content (not sure if this is related, though).
3. Upon installing, go to watchdog and see warnings.

## Screenshots
![image](https://user-images.githubusercontent.com/4062676/95525376-c7f73000-0988-11eb-974d-57d3ef966804.png)

## Notes
This is not happening on Drupal 8 installations.

## Version Info
drupal/core: 9.0.7
apigee/apigee_devportal_kickstart: 8.x-1.21

**Comment by cnovak** [comment]
Should the messages be blocked, or the invalid items removed so the errors are not happending?

**Comment by arlina-espinoza** [comment]
We should investigate why the block content wasn't found. I see all relevant blocks installed, so maybe there is an extra step to take for D9.
