### ISSUE TITLE
Dev Portal MySQL do not replicate	

### ISSUE THREAD

**Issue by tieudaotu90** [apigee/apigee-devportal-kickstart-drupal#445]
I'm facing a problem about replication between 2 nodes of MySQL database for Dev Portal. (Each Dev Portal site has its own DB)
Each node is replicate to other. if we disable 1 way replicate, the error still occur.

Here is an error;
Last_SQL_Error: Could not execute Delete_rows event on table mb.sessions; Can't find record in 'sessions', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000129, end_log_pos 5319037

## Version Info
Drupal 8.9.10 and MySQL 5.7.30

**Comment by cnovak** [comment]
This is not an issue with our Drupal distribution, but with the configuration/maintenance of a MySQL replication issue. A quick search brought up [this article explaining replication issues](https://severalnines.com/blog/mysql-tutorial-troubleshooting-mysql-replication-part-2) which may help. 

I am not sure how else we can help you configure and handle MySQL replication issues, maybe [MySQL documentation or support resources](https://www.mysql.com/support/) can help?
