### ISSUE TITLE
Kickstart install fails with Integrity constraint violation

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#449]
## Description
Installation fails with following error

`Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin_toolbar_tools.extra_links:node.add.forum' for key 'id': INSERT INTO {menu_tree} (id, menu_name) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array ( [:db_insert_placeholder_0] => admin_toolbar_tools.extra_links:node.add.forum [:db_insert_placeholder_1] => admin ) in Drupal\Core\Database\Connection->handleQueryException() (line 698 of core/lib/Drupal/Core/Database/Connection.php).
`
## Steps to Reproduce
 Issue was reproduced on a internal project that leverages kickstart.
Kickstart version- 8.9.6
OS: Debian (10)
PHP (7.4.9)
MySQL-Client (5.7.31)

## Actual Behavior
Install fails to complete.

## Expected Behavior
Install succeeds 

## Screenshots
![Screen Shot 2021-01-22 at 4 14 57 PM](https://user-images.githubusercontent.com/4381612/105561915-1082f100-5ccd-11eb-8995-1db6301e9410.png)

## Version Info
Kickstart version- 8.9.6
OS: Debian (10)
PHP (7.4.9)
MySQL-Client (5.7.31)

**Comment by arunz6161** [comment]
@giteshk FYI

**Comment by raakesh-blokhra** [comment]
@arunz6161 Can you please confirm whether the database you specified during installation is a new database or an existing one?

**Comment by arunz6161** [comment]
New database and not an existing one

**Comment by arunz6161** [comment]
wasn't able to reproduce the issue following the same steps. Closing this for now, will reopen if i am able to reproduce the issue consistently.
