### ISSUE TITLE
Reloading API overview screen gives error "Page Not Found"

### ISSUE THREAD

**Issue by nishasw** [apigee/apigee-devportal-kickstart-drupal#453]
When the API overview screen is reloaded, it give error **"The requested page could not be found."**. Please see the attached screenshot.

**Steps to Reproduce**
1. Go to /apis
2. Click on one of API listed 
3. After the page (API overview) has been loaded , reload the screen and you will get the error below.

![image](https://user-images.githubusercontent.com/78082773/106877353-55e9ea00-66e1-11eb-9662-cafef1c5331c.png)

Any help is appreciated. Thanks in advance.

**Comment by raakesh-blokhra** [comment]
Hi @nishasw we are not able to replicate the issue with the limited information shared above. Can you share any debug logs which we can review to get more information?
