### ISSUE TITLE
[error]  Update failed: apigee_devportal_kickstart_update_8008

### ISSUE THREAD

**Issue by sejonssonjer** [apigee/apigee-devportal-kickstart-drupal#454]
After updating to this version of kickstarter and running drush updb I am getting the following error and it fails to update the DB:
-----------------------
 Do you wish to run the specified pending updates? (yes/no) [yes]:
 > yes

>  [notice] Update started: apigee_devportal_kickstart_update_8008
>  [error]  Missing bundle entity, entity type node_type, entity id apidoc.
>  [error]  Update failed: apigee_devportal_kickstart_update_8008
 [error]  Update aborted by: apigee_devportal_kickstart_update_8008
 [error]  Finished performing updates.
-----------------------
We are on 
- Drupal Version 8.9.13
- PHP 7.4.10

**Comment by raakesh-blokhra** [comment]
@sejonssonjer Can you get us the full debug log please?

**Comment by sejonssonjer** [comment]
> @sejonssonjer Can you get us the full debug log please?

Sure, can you point me to which debug log you mean?
