### ISSUE TITLE
Error while trying to update [error]  Call to a member function getDisplay() on null

### ISSUE THREAD

**Issue by jackd12** [apigee/apigee-devportal-kickstart-drupal#455]
Trying to upgrade from drupal 8.9.3 to 8.9.13 getting the error below when running drush updb

drush updb

**_>  [notice] Update started: apigee_devportal_kickstart_update_8009
>  [error]  Call to a member function getDisplay() on null
>  [error]  Update failed: apigee_devportal_kickstart_update_8009
 [error]  Update aborted by: apigee_devportal_kickstart_update_8009_**
 [error]  Finished performing updates.

Any thoughts on how to fix this ?

**Comment by jackd12** [comment]
Here's the full error 

Error: Call to a member function getDisplay() on null in apigee_devportal_kickstart_update_8009() (line 484 of /var/www/devportal/web/profiles/contrib/apigee_devportal_kickstart/apigee_devportal_kickstart.install)
#0 /var/www/devportal/web/core/includes/update.inc(246): apigee_devportal_kickstart_update_8009(Array)
#1 /var/www/devportal/web/core/includes/batch.inc(295): update_do_one('apigee_devporta...', 8009, Array, Array)
#2 /var/www/devportal/web/core/includes/batch.inc(137): _batch_process()
#3 /var/www/devportal/web/core/includes/batch.inc(93): _batch_do()
#4 /var/www/devportal/web/core/modules/system/src/Controller/DbUpdateController.php(185): _batch_page(Object(Symfony\Component\HttpFoundation\Request))
#5 [internal function]: Drupal\system\Controller\DbUpdateController->handle('start', Object(Symfony\Component\HttpFoundation\Request))
#6 /var/www/devportal/web/core/lib/Drupal/Core/Update/UpdateKernel.php(115): call_user_func_array(Array, Array)
#7 /var/www/devportal/web/core/lib/Drupal/Core/Update/UpdateKernel.php(76): Drupal\Core\Update\UpdateKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request))
#8 /var/www/devportal/web/update.php(28): Drupal\Core\Update\UpdateKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}

**Comment by raakesh-blokhra** [comment]
Hi @jackd12 We will review the logs and revert back with the finding.
