### ISSUE TITLE
Planning to move to apigee-devportal-kickstart-drupal to AWS (Any Containerized Solution?)

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#456]
Hi Team,

It would be great if you guys provide some documentation for the "apigee-developer-portal-drupal" Containerized Solution.
- How we can set the Drupal Portal on AWS?
- Any suggestion would be greatly appreciated.

Thanks

**Comment by phdhiren** [comment]
@pradeepgorle13 , You should check [ansible installer](https://github.com/apigee/devportal-kickstart-drupal-ansible-installer)  or [docker](https://github.com/apigee/docker-apigee-drupal-kickstart)

**Comment by pradeepgorle13** [comment]
@phdhiren Thanks for the link and it is atleast a great start. Found couple of links
https://medium.com/@shubhamner21/launching-drupal-using-eks-15d933101caf
https://aws.amazon.com/marketplace/pp/Bitnami-Drupal-Container-Solution/B07KCSKPGZ
But the requirement exactly matches the first link (Launching drupal using eks). So if that is the case - Is there a way for the Drupal Kickstarter installer to be use over eks.(Can you guys provide the steps for drupal deployment file and mariadb deployment file)

**Comment by phdhiren** [comment]
@pradeepgorle13 It is a typical Drupal installation, so any document mentioned above should lead you to do the install. If you run into any issues, feel free to let us know and we can guide you accordingly. I am closing this issue, but if you have any other questions, please feel free to reopen it.
