### ISSUE TITLE
Notification of Drupal 8 EOL

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-devportal-kickstart-drupal#458]
With the upcoming EOL of Drupal 8, develop a D8-D9 migration one-pager for inclusion in the Kickstart documentation.  
 - The doc should provide steps on any changes needed to update the Composer file or any dependencies to support Drupal 9 for users currently using Drupal 8.
 - If this process is documented in Drupal.org, it is fine to link to the instructions there and not replicate.
 - I will add these docs to our Kickstart doc set and add a note to the Kickstart project page pointing to the one-pager.

**Comment by cnovak** [comment]
I also noticed that D9 is "in progress" on the project page. We should change that link to the closed ticket to the document on how to migrate from D8 to D9.

<img width="665" alt="Screen Shot 2021-03-05 at 12 39 15 PM" src="https://user-images.githubusercontent.com/613093/110172812-85f4dd80-7db2-11eb-9975-8bcfcd936acf.png">

**Comment by phdhiren** [comment]
This had been taken care
