### ISSUE TITLE
Components 8.x-1.x API deprecation notice

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-devportal-kickstart-drupal#460]
Installed Apigee Kickstart composer project for Drupal 9.
See the following deprecation notice.

![Screen Shot 2021-03-16 at 4 49 46 PM](https://user-images.githubusercontent.com/6208023/111378455-334fd700-8678-11eb-9473-185122f4cb05.png)

**Comment by raakesh-blokhra** [comment]
@phdhiren since you are looking into these updates, please look into this issue as well. Thanks.
