### ISSUE TITLE
OAuth cannot be used for connection during installation process

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#468]
## Description
The OAuth connection setting cannot be used during the installation of the system.

## Steps to Reproduce
1. Install Kickstart following instructions
2. During the web installer, connect to an Apigee Edge org (4G) and select `OAuth` instead of `Basic` for authentication type

## Actual Behavior
The error `Unable to save token Unable to save token data to private filesystem because it has not been configured yet. in ./web/modules/contrib/apigee_edge/src/OauthTokenFileStorage.php:194` is displayed

## Expected Behavior
OAuth can be used during installation.

## Screenshots
<img width="736" alt="Screen Shot 2021-04-22 at 3 00 32 PM" src="https://user-images.githubusercontent.com/613093/115794631-2dd66280-a383-11eb-9539-4bcfb7862dcb.png">

## Version Info
```
apigee/apigee-client-php                 2.0.7        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.23         A fast demo and starting point for Apigee Developer Portals.
drupal/apigee_api_catalog                2.5.0        Apigee API Catalog for Drupal
drupal/apigee_edge                       1.22.0       Apigee Edge for Drupal.
drupal/apigee_m10n                       1.10.0       Apigee Edge Monetization for Drupal
```

**Comment by phdhiren** [comment]
@cnovak 

The OAuth settings will be stored in private file system. 

> In Drupal 8, you can no longer set private file system via UI. You set it in your settings.php file. 

https://www.drupal.org/docs/8/core/modules/file/overview#private-file-system


I'm proposing to add one more step - "Verify Apigee Requirements" similar to "Verify Requirements" before "Configure Apigee Edge" where it can check for private file system and will have documentation link and option to recheck, if private file system is enabled or not. 
The same step can be skip also if someone would like to go with 'Basic' option or do not have option to set private file system, however to set private file system will be highly recommended.

**Comment by cnovak** [comment]
Thanks @phdhiren , I forgot that was the reason, I thought that the private file system could not be configured before install. That is a great suggestion - to show an error to  user explaining they need to set up private file system in order to install, and link to instructions.
