### ISSUE TITLE
While Configuring the Apigee with Drupal getting error

### ISSUE THREAD

**Issue by jyotierudkar** [apigee/apigee-devportal-kickstart-drupal#489]
$ drush create-edge-role myorg me@example.com

After Executing this command below error occurred :
Error: call to undefined method GuzzleHttp\Utils::chooseHandler() in GuzzleHttp\choose_handler()  )(line 61 of /root/.composer/global/drush/drush/vendor/
#1[internal function]: GuzzleHttp\HandlerStack::create()

**Comment by shishir-intelli** [comment]
Hi @jyotierudkar ,
Not able to replicate the issue,
Try installing drush locally  `composer require drush/drush`

Similar issue https://www.drupal.org/project/varbase/issues/3216791

**Comment by phdhiren** [comment]
@jyotierudkar 
Closing this issue for now, but if you need further assistance regarding this, please feel free to reopen it.
