### ISSUE TITLE
Unable to to connect with apigee private cloud with Oauth authentication

### ISSUE THREAD

**Issue by jyotierudkar** [apigee/apigee-devportal-kickstart-drupal#490]
Installed Apigee Edge module on Drupal 9.

When i tried to configure apigee private cloud with Oauth athentication type, I am getting Unauthorized Error.
I used the same credentials as HTTP Basic. With Http Basic I am able to establish connection with Apigee private cloud.

For Oauth getting 401: authorized

**Comment by giteshk** [comment]
@jyotierudkar What version of Apigee Private cloud are you running?

**Comment by jyotierudkar** [comment]
@giteshk 4.50

**Comment by phdhiren** [comment]
@jyotierudkar 
Basic Auth is not deprecated for OPDK yet. Please use Basic Auth for now.

Closing this ticketing, tracking the same at https://github.com/apigee/apigee-edge-drupal/issues/608

**Comment by jyotierudkar** [comment]
That is different issue. We are still not able to connect

**Comment by phdhiren** [comment]
@jyotierudkar 

You're able to connect connect using HTTP Basic authentication and you're using OPDK. right?

**Comment by phdhiren** [comment]
Closing the issue for now, fell free to reopen if require.
