### ISSUE TITLE
Logging In but with a error

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#492]
We connected our Drupal 9 to LDAP for login Validation.
When we try to login, It is logging in but with an error 
![image](https://user-images.githubusercontent.com/56166711/123034886-67920c80-d3b8-11eb-9545-8d0c321939db.png)

but when we are clicking on another tab or refresh the page it just disappears.
When ever we logout and login again - it shows the error until we click on another tab or refresh the page.

Can you guys please let me know why this weird behavior is been shown

**Comment by shishir-intelli** [comment]
Hi @pradeepgorle13 

Can you please share us the exact steps to reproduce the behavior and the error log details.

**Comment by raakesh-blokhra** [comment]
Closing this issue. Please feel free to reopen if the issue still exists. Thanks
