### ISSUE TITLE
SSO Integration(Ping Federate) with Drupal

### ISSUE THREAD

**Issue by NNV111** [apigee/apigee-devportal-kickstart-drupal#493]
We are trying to integrate SSO(Ping Federate) with Drupal. Have found a link i.e. https://simplesamlphp.org/docs/stable/simplesamlphp-sp 
Would like to you if we can go ahead with this approach
Also can anyone provide a brief elaboration on any mandatory steps for sso implementation

**Comment by shishir-intelli** [comment]
Hi NNV111,
Yes you can give simplesaml a shot and alternatively you can also try https://www.drupal.org/docs/contributed-modules/saml-sp-single-sign-on-sso-saml-service-provider/guide-for-drupal-single-8

**Comment by NNV111** [comment]
Hi @shishir-intelli  
thankyou for the info, but miniorange is a paid version and want to try out with any open source module.

**Comment by NNV111** [comment]
While trying to install with simplesamlphp (https://simplesamlphp.org/docs/stable/simplesamlphp-install). Have installed the installable as per the instructions and while trying to configure the same, facing an issue where the entire Drupal site crashes.
Has anyone faced a similar kind of an issue? If so, how was it fixed?

**Comment by shishir-intelli** [comment]
Hi,
Which version of Drupal and module are you using?
Can you please tell us more details about the error by sharing us the error logs also have you installed any module for SAML in Drupal.

**Comment by NNV111** [comment]
Drupal version 9.1.10 
I have just installed the simplesamlphp_auth installable and was trying to configure the same. Haven't installed anything else other than that. 
Error logs

**Comment by shishir-intelli** [comment]
@NNV111,
Can you please also share PHP error logs and also the configuration which you have done, the above has nothing to do with Apigee Devportal this seems some configuration issue.

For Drupal I think you should refer this document for using SAML
https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/integrate-simplesamlphp-authentication

**Comment by shishir-intelli** [comment]
I hope that information helped,
Closing this for now, feel free to reopen if in case you need any further help.
Thanks!
