### ISSUE TITLE
Not sure if bug or user issue

### ISSUE THREAD

**Issue by Stephen-lapierre-mpf** [apigee/apigee-devportal-kickstart-drupal#505]
## Description
Having upgraded Drupal, Radix and kickstart on selecting Apps with RBAC no Apps are displayed, only available via creating App and selecting from list.

## Steps to Reproduce
1. Go to Apps ( nothing listed except Add
2. Click on Add App
3. Scroll down to select app to add

## Actual Behavior
Not able to see apps with correct RBAC and role without adding

## Expected Behavior
Was able to see apps with correct RBAC and role without adding

## Notes
Unsure if this new behavior or configuration issue as RBAC set on Apigee Edge and role associated within Drupal

## Version Info
 ---------------- --------------------------------- ---------- ---------------- 
  Package          Name                              Status     Version         
 ---------------- --------------------------------- ---------- ---------------- 
  Core             Actions (action)                  Disabled   9.2.5           
  Core             Aggregator (aggregator)           Disabled   9.2.5           
  Core             Automated Cron (automated_cron)   Enabled    9.2.5           
  Core             Ban (ban)                         Disabled   9.2.5           
  Web services     HTTP Basic Authentication         Disabled   9.2.5           
                   (basic_auth)                                                 
  Core             BigPipe (big_pipe)                Enabled    9.2.5           
  Core             Block (block)                     Enabled    9.2.5           
  Core             Custom Block (block_content)      Enabled    9.2.5           
  Core             Book (book)                       Disabled   9.2.5           
  Core             Breakpoint (breakpoint)           Enabled    9.2.5           
  Core             CKEditor (ckeditor)               Enabled    9.2.5           
  Core             Color (color)                     Enabled    9.2.5           
  Core             Comment (comment)                 Enabled    9.2.5           
  Core             Configuration Manager (config)    Enabled    9.2.5           
  Multilingual     Configuration Translation         Disabled   9.2.5           
                   (config_translation)                                         
  Core             Contact (contact)                 Enabled    9.2.5           
  Core             Content Moderation                Disabled   9.2.5           
                   (content_moderation)                                         
  Multilingual     Content Translation               Disabled   9.2.5           
                   (content_translation)                                        
  Core             Contextual Links (contextual)     Enabled    9.2.5           
  Field types      Datetime (datetime)               Enabled    9.2.5           
  Field types      Datetime Range (datetime_range)   Disabled   9.2.5           
  Core             Database Logging (dblog)          Disabled   9.2.5           
  Core             Internal Dynamic Page Cache       Enabled    9.2.5           
                   (dynamic_page_cache)                                         
  Core             Text Editor (editor)              Enabled    9.2.5           
  Field types      Entity Reference                  Disabled   9.2.5           
                   (entity_reference)                                           
  Core             Field (field)                     Enabled    9.2.5           
  Core             Field Layout (field_layout)       Disabled   9.2.5           
  (Experimental)                                                                
  Core             Field UI (field_ui)               Enabled    9.2.5           
  Field types      File (file)                       Enabled    9.2.5           
  Core             Filter (filter)                   Enabled    9.2.5           
  Core             Forum (forum)                     Enabled    9.2.5           
  Web services     HAL (hal)                         Enabled    9.2.5           
  Core             Help (help)                       Enabled    9.2.5           
  Core             Help Topics (help_topics)         Disabled   9.2.5           
  (Experimental)                                                                
  Core             History (history)                 Enabled    9.2.5           
  Field types      Image (image)                     Enabled    9.2.5           
  Core             Inline Form Errors                Disabled   9.2.5           
                   (inline_form_errors)                                         
  Web services     JSON:API (jsonapi)                Disabled   9.2.5           
  Multilingual     Language (language)               Disabled   9.2.5           
  Core             Layout Builder (layout_builder)   Enabled    9.2.5           
  Core             Layout Discovery                  Enabled    9.2.5           
                   (layout_discovery)                                           
  Field types      Link (link)                       Enabled    9.2.5           
  Multilingual     Interface Translation (locale)    Disabled   9.2.5           
  Core             Media (media)                     Enabled    9.2.5           
  Core             Media Library (media_library)     Enabled    9.2.5           
  Core             Custom Menu Links                 Enabled    9.2.5           
                   (menu_link_content)                                          
  Core             Menu UI (menu_ui)                 Enabled    9.2.5           
  Migration        Migrate (migrate)                 Disabled   9.2.5           
  Migration        Migrate Drupal (migrate_drupal)   Disabled   9.2.5           
  Core             Migrate Drupal Multilingual       Disabled   9.2.5           
  (Experimental)   (migrate_drupal_multilingual)                                
  Migration        Migrate Drupal UI                 Disabled   9.2.5           
                   (migrate_drupal_ui)                                          
  Core             Node (node)                       Enabled    9.2.5           
  Field types      Options (options)                 Enabled    9.2.5           
  Core             Internal Page Cache               Enabled    9.2.5           
                   (page_cache)                                                 
  Core             Path (path)                       Enabled    9.2.5           
  Core             Path alias (path_alias)           Enabled    9.2.5           
  Core             Quick Edit (quickedit)            Enabled    9.2.5           
  Core             RDF (rdf)                         Enabled    9.2.5           
  Core             Responsive Image                  Enabled    9.2.5           
                   (responsive_image)                                           
  Web services     RESTful Web Services (rest)       Disabled   9.2.5           
  Core             Search (search)                   Enabled    9.2.5           
  Web services     Serialization (serialization)     Enabled    9.2.5           
  Core             Settings Tray (settings_tray)     Disabled   9.2.5           
  Core             Shortcut (shortcut)               Enabled    9.2.5           
  Core             Testing (simpletest)              Disabled   9.2.5           
  Core             Statistics (statistics)           Disabled   9.2.5           
  Core             Syslog (syslog)                   Enabled    9.2.5           
  Core             System (system)                   Enabled    9.2.5           
  Core             Taxonomy (taxonomy)               Enabled    9.2.5           
  Field types      Telephone (telephone)             Disabled   9.2.5           
  Field types      Text (text)                       Enabled    9.2.5           
  Core             Toolbar (toolbar)                 Enabled    9.2.5           
  Core             Tour (tour)                       Enabled    9.2.5           
  Core             Activity Tracker (tracker)        Disabled   9.2.5           
  Core             Update Manager (update)           Disabled   9.2.5           
  Core             User (user)                       Enabled    9.2.5           
  Core             Views (views)                     Enabled    9.2.5           
  Core             Views UI (views_ui)               Enabled    9.2.5           
  Core             Workflows (workflows)             Disabled   9.2.5           
  Core             Workspaces (workspaces)           Disabled   9.2.5           
  (Experimental)                                                                
  Apigee           Apigee Kickstart Content          Enabled                    
  Kickstart        (apigee_kickstart_content)                                   
  Apigee           Apigee Kickstart Customizer       Enabled                    
  Kickstart        (apigee_kickstart_customizer)                                
  Apigee           Apigee Kickstart Enhancement      Enabled                    
  Kickstart        (apigee_kickstart_enhancement)                               
  Apigee           Apigee Kickstart Monetization     Disabled                   
  Kickstart        (Deprecated)                                                 
                   (apigee_kickstart_m10n_add_cred                              
                   it)                                                          
  Apigee           Apigee Kickstart Migrate          Disabled                   
  Kickstart        (apigee_kickstart_migrate)                                   
  Examples         Apigee Kickstart Migrate          Disabled                   
                   Example                                                      
                   (apigee_kickstart_migrate_examp                              
                   le)                                                          
  Acquia Cloud     ACSF Connector (acsf)             Enabled    8.x-2.69        
  Site Factory                                                                  
  Acquia Cloud     ACSF Duplication                  Enabled    8.x-2.69        
  Site Factory     (acsf_duplication)                                           
  Acquia Cloud     ACSF Scheduled Jobs (acsf_sj)     Disabled   8.x-2.69        
  Site Factory                                                                  
  Acquia Cloud     ACSF Single Sign On (acsf_sso)    Enabled    8.x-2.69        
  Site Factory                                                                  
  Acquia Cloud     ACSF Theme (acsf_theme)           Enabled    8.x-2.69        
  Site Factory                                                                  
  Acquia Cloud     ACSF Variables (acsf_variables)   Enabled    8.x-2.69        
  Site Factory                                                                  
  Field types      Address (address)                 Disabled   8.x-1.9         
  Administration   Admin Toolbar (admin_toolbar)     Enabled    8.x-2.5         
  Administration   Admin Toolbar Links Access        Enabled    8.x-2.5         
                   Filter                                                       
                   (admin_toolbar_links_access_fil                              
                   ter)                                                         
  Administration   Admin Toolbar Search              Disabled   8.x-2.5         
                   (admin_toolbar_search)                                       
  Administration   Admin Toolbar Extra Tools         Enabled    8.x-2.5         
                   (admin_toolbar_tools)                                        
  Administration   Adminimal Admin Toolbar           Enabled    8.x-1.11        
                   (adminimal_admin_toolbar)                                    
  Apigee           Apigee API Catalog                Enabled    8.x-2.6         
                   (apigee_api_catalog)                                         
  Apigee           Apigee Edge (apigee_edge)         Enabled    8.x-1.24        
  Apigee           Apigee Edge Actions               Disabled   8.x-1.24        
  (Experimental)   (apigee_edge_actions)                                        
  Apigee           Apigee Edge Actions Debug         Disabled   8.x-1.24        
  (Experimental)   (apigee_edge_actions_debug)                                  
  Apigee           Apigee Edge Actions Examples      Disabled   8.x-1.24        
  (Experimental)   (apigee_edge_actions_examples)                               
  Apigee           Apigee Edge API product RBAC      Enabled    8.x-1.24        
                   (apigee_edge_apiproduct_rbac)                                
  Apigee           Apigee Edge Debug                 Disabled   8.x-1.24        
                   (apigee_edge_debug)                                          
  Apigee           Apigee Edge Teams                 Disabled   8.x-1.24        
                   (apigee_edge_teams)                                          
  Apigee           Apigee Monetization               Disabled   8.x-1.11        
                   (apigee_m10n)                                                
  Apigee           Apigee Monetization Add Credit    Disabled   8.x-1.11        
                   (apigee_m10n_add_credit)                                     
  Apigee           Apigee Monetization Teams         Disabled   8.x-1.11        
  (Experimental)   (apigee_m10n_teams)                                          
  Views            Better Exposed Filters            Enabled    8.x-5.0-beta3   
                   (better_exposed_filters)                                     
  Bricks           Bricks (bricks)                   Enabled    2.0.1           
  Bricks           Bricks Default (bricks_default)   Enabled    2.0.1           
  Bricks           Bricks Default Blocks             Enabled    2.0.1           
                   (bricks_default_blocks)                                      
  Bricks           Bricks Default Paragraphs         Disabled   2.0.1           
                   (bricks_default_paragraphs)                                  
  Bricks           Bricks Dynamic (bricks_dynamic)   Disabled   2.0.1           
  Bricks           Bricks Inline (bricks_inline)     Enabled    2.0.1           
  Bricks           Bricks Revisions                  Enabled    2.0.1           
                   (bricks_revisions)                                           
  Commerce         Commerce (commerce)               Disabled   8.x-2.26        
  Commerce         Commerce Cart (commerce_cart)     Disabled   8.x-2.26        
  Commerce         Commerce Checkout                 Disabled   8.x-2.26        
                   (commerce_checkout)                                          
  Commerce         Commerce Log (commerce_log)       Disabled   8.x-2.26        
  Commerce         Commerce Number Pattern           Disabled   8.x-2.26        
                   (commerce_number_pattern)                                    
  Commerce         Commerce Order (commerce_order)   Disabled   8.x-2.26        
  Commerce         Commerce Payment                  Disabled   8.x-2.26        
                   (commerce_payment)                                           
  Commerce         Commerce Payment Example          Disabled   8.x-2.26        
                   (commerce_payment_example)                                   
  Commerce         Commerce Price (commerce_price)   Disabled   8.x-2.26        
  Commerce         Commerce Product                  Disabled   8.x-2.26        
                   (commerce_product)                                           
  Commerce         Commerce Promotion                Disabled   8.x-2.26        
                   (commerce_promotion)                                         
  Commerce         Commerce Store (commerce_store)   Disabled   8.x-2.26        
  Commerce         Commerce Tax (commerce_tax)       Disabled   8.x-2.26        
  Other            Components (components)           Enabled    8.x-2.4         
  Chaos tool       Chaos Tools (ctools)              Enabled    8.x-3.7         
  suite                                                                         
  Chaos tool       Chaos Tools Blocks                Disabled   8.x-3.7         
  suite            (ctools_block)                                               
  (Experimental)                                                                
  Other            Entity Mask                       Disabled   8.x-3.7         
                   (ctools_entity_mask)                                         
  Chaos tool       Chaos Tools Views                 Disabled   8.x-3.7         
  suite            (ctools_views)                                               
  (Experimental)                                                                
  Web services     Default content                   Enabled    8.x-1.0-alpha9  
                   (default_content)                                            
  Other            Email Registration                Enabled    8.x-1.1         
                   (email_registration)                                         
  Other            Entity (entity)                   Enabled    8.x-1.2         
  Media            Entity Browser (entity_browser)   Enabled    8.x-2.6         
  Media            Entity Browser IEF                Disabled   8.x-2.6         
                   (entity_browser_entity_form)                                 
  Media            Entity Browser example            Disabled   8.x-2.6         
                   (entity_browser_example)                                     
  Field types      Entity Reference Revisions        Enabled    8.x-1.9         
                   (entity_reference_revisions)                                 
  Other            Entity Usage (entity_usage)       Disabled   8.x-2.0-beta5   
  User             External Authentication           Enabled    8.x-1.4         
  authentication   (externalauth)                                               
  Field types      File Link (file_link)             Enabled    2.0.6           
  Other            Font Awesome (fontawesome)        Enabled    8.x-2.19        
  Other            Font Awesome Iconpicker Widget    Disabled   8.x-2.19        
                   (fontawesome_iconpicker_widget)                              
  Other            Font Awesome Media Entity         Disabled   8.x-2.19        
                   (fontawesome_media)                                          
  Statistics       Google Analytics                  Disabled   8.x-3.1         
                   (google_analytics)                                           
  Fields           Inline Entity Form                Enabled    8.x-1.0-rc9     
                   (inline_entity_form)                                         
  jQuery UI        jQuery UI (jquery_ui)             Enabled    8.x-1.4         
  jQuery UI        jQuery UI Datepicker              Enabled    8.x-1.1         
                   (jquery_ui_datepicker)                                       
  jQuery UI        jQuery UI Slider                  Enabled    8.x-1.1         
                   (jquery_ui_slider)                                           
  jQuery UI        jQuery UI Touch Punch             Enabled    1.0.0           
                   (jquery_ui_touch_punch)                                      
  Web services     JSON:API Extras                   Disabled   8.x-3.19        
                   (jsonapi_extras)                                             
  Web services     JSON API Defaults                 Disabled   8.x-3.19        
                   (jsonapi_defaults)                                           
  Security         Key (key)                         Enabled    8.x-1.14        
  Paragraphs       Layout Paragraphs                 Disabled   2.0.0-alpha4    
                   (layout_paragraphs)                                          
  Other            OKTA API (okta_api)               Disabled                   
  Other            OKTA SAML Login                   Disabled                   
                   (okta_saml_login)                                            
  OpenAPI          OpenAPI UI (openapi_ui)           Enabled    8.x-1.0-rc3     
  OpenAPI          Swagger UI for OpenAPI UI         Enabled    8.x-1.0-rc4     
                   (openapi_ui_swagger)                                         
  Paragraphs       Paragraphs Demo                   Disabled   8.x-1.12        
                   (paragraphs_demo)                                            
  Paragraphs       Paragraphs Library                Disabled   8.x-1.12        
                   (paragraphs_library)                                         
  Paragraphs       Paragraphs Type Permissions       Disabled   8.x-1.12        
                   (paragraphs_type_permissions)                                
  Paragraphs       Paragraphs (paragraphs)           Enabled    8.x-1.12        
  Other            Pathauto (pathauto)               Enabled    8.x-1.8         
  Permissions by   Permissions by Entity             Disabled   3.1.16          
  Term             (permissions_by_entity)                                      
  (Experimental)                                                                
  Permissions by   Permissions by Term               Disabled   3.1.16          
  Term             (permissions_by_term)                                        
  Other            Profile (profile)                 Disabled   8.x-1.3         
  Administration   Requirement (requirement)         Disabled   8.x-1.1         
  User             SAML Auth User Fields Mapping     Disabled   8.x-3.0-rc2     
  authentication   (samlauth_user_fields)                                       
  User             SAML Auth User Role Assignment    Disabled   8.x-3.0-rc2     
  authentication   (samlauth_user_roles)                                        
  User             SAML Authentication (samlauth)    Enabled    8.x-3.0-rc2     
  authentication                                                                
  Testing          SAML Authentication Test          Disabled   8.x-3.0-rc2     
                   (samlauth_test)                                              
  Search           Database Search (search_api_db)   Disabled   8.x-1.20        
  Search           Database Search Defaults          Disabled   8.x-1.20        
                   (search_api_db_defaults)                                     
  Search           Search API (search_api)           Disabled   8.x-1.20        
  Security         Security Kit (seckit)             Enabled    2.0.0           
  Other            SimpleSAMLphp Authentication      Enabled    8.x-3.2         
                   (simplesamlphp_auth)                                         
  Mail             SMTP Authentication Support       Disabled   8.x-1.0         
                   (smtp)                                                       
  Other            State Machine (state_machine)     Disabled   8.x-1.5         
  Other            Swagger UI Field Formatter        Enabled    8.x-3.3         
                   (swagger_ui_formatter)                                       
  Other            Token (token)                     Enabled    8.x-1.9         
  Core             Bartik (bartik)                   Enabled    9.2.5           
  Core             Claro (claro)                     Disabled   9.2.5           
  Core             Classy (classy)                   Disabled   9.2.5           
  Core             Olivero (olivero)                 Disabled   9.2.5           
  Core             Seven (seven)                     Enabled    9.2.5           
  Core             Stable (stable)                   Disabled   9.2.5           
  Core             Stable 9 (stable9)                Disabled   9.2.5           
  Core             Stark (stark)                     Disabled   9.2.5           
                   Apigee Kickstart                  Enabled    9.2.5           
                   (apigee_kickstart)                                           
                   Radix (radix)                     Enabled    8.x-4.10        
 ---------------- --------------------------------- ---------- ----------------

**Comment by phdhiren** [comment]
Based on the requirement it was suggested to use Apigee Edge Teams functionality instead RBAC in this case
