### ISSUE TITLE
How to repleace "API Doc" Title with product display name?

### ISSUE THREAD

**Issue by hollyw2025** [apigee/apigee-devportal-kickstart-drupal#507]
## Description
After the products were synced from edge to portal, products show up as "API doc" content type. We noticed that product display name didn't show up, so we customized to have product displayname showed up. However, in "API doc", the product name, which is the real name of the product, still shows as Title. We would like to know how to have the product displayName shows as "API doc" Title in the portal. 

## Steps to Reproduce
1. Go to Apigee Edge, create a test product, which has different Product name and display name
![Screen Shot 2021-09-15 at 9 16 45 AM](https://user-images.githubusercontent.com/69690136/133470772-4bca6422-8d6a-48dd-9ae6-792c09611c91.png)

2. Go to Portal, the product name and displayName both synced to portal, while the displayName doesn't shows as Title
![Screen Shot 2021-09-15 at 8 35 11 PM](https://user-images.githubusercontent.com/69690136/133545290-9045e022-a63b-4c67-84ae-da2b1b3e38ce.png)

## Expected Behavior
We would like to have the product display name shows as "API Doc" title. At this moment, we have to delete the current product and create a new one, just to rename the product in portal. 

What is the original design of have the product real name sync to portal? 

## Version Info
hollywang@hollys-mbp release21 % composer show
apigee/apigee-client-php                                  2.0.10          Client library for connecting to the Apig...
apigee/apigee_devportal_kickstart                         1.23            A fast demo and starting point for Apigee...
asm89/stack-cors                                          1.3.0           Cross-origin resource sharing library and...
bower-asset/swagger-ui                                    v3.51.0        
chi-teck/drupal-code-generator                            1.33.1          Drupal code generator
clue/stream-filter                                        v1.5.0          A simple and modern approach to stream fi...
commerceguys/addressing                                   v1.2.1          Addressing library powered by CLDR and Go...
commerceguys/intl                                         v1.1.0          Internationalization library powered by C...
composer/installers                                       v1.12.0         A multi-framework Composer library installer
composer/semver                                           3.2.5           Semver library that offers utilities, ver...
consolidation/annotated-command                           4.3.1           Initialize Symfony Console commands from ...
consolidation/config                                      1.2.1           Provide configuration services for a comm...
consolidation/filter-via-dot-access-data                  1.0.0           This project uses dflydev/dot-access-data...
consolidation/log                                         2.0.2           Improved Psr-3 / Psr\Log logger based on ...
consolidation/output-formatters                           4.1.2           Format text by applying transformations p...
consolidation/robo                                        2.2.2           Modern task runner
consolidation/self-update                                 1.2.0           Provides a self:update command for Symfon...
consolidation/site-alias                                  3.1.0           Manage alias records for local and remote...
consolidation/site-process                                4.1.0           A thin wrapper around the Symfony Process...
container-interop/container-interop                       1.2.0           Promoting the interoperability of contain...
cweagans/composer-patches                                 1.7.1           Provides a way to patch Composer packages.
dflydev/dot-access-data                                   v1.1.0          Given a deep data structure, access data ...
doctrine/annotations                                      1.13.1          Docblock Annotations Parser
doctrine/cache                                            1.12.1          PHP Doctrine Cache library is a popular c...
doctrine/collections                                      1.6.8           PHP Doctrine Collections library that add...
doctrine/common                                           2.13.3          PHP Doctrine Common project is a library ...
doctrine/event-manager                                    1.1.1           The Doctrine Event Manager is a simple PH...
doctrine/inflector                                        1.4.4           PHP Doctrine Inflector is a small library...
doctrine/lexer                                            1.2.1           PHP Doctrine Lexer parser library that ca...
doctrine/persistence                                      1.3.8           The Doctrine Persistence project is a set...
doctrine/reflection                                       1.2.2           The Doctrine Reflection project is a simp...
drupal/address                                            1.9.0           Provides functionality for storing, valid...
drupal/admin_toolbar                                      2.5.0           Provides a drop-down menu interface to th...
drupal/adminimal_admin_toolbar                            1.11.0          Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                                 2.6.0           Apigee API Catalog for Drupal
drupal/apigee_edge                                        1.24.0          Apigee Edge for Drupal.
drupal/apigee_m10n                                        1.11.0          Apigee Edge Monetization for Drupal
drupal/autologout                                         1.3.0           Adds automated timed logout.
drupal/better_exposed_filters                             5.0.0-beta3     Replaces the Views default single- or mul...
drupal/commerce                                           2.26.0          Drupal Commerce is a flexible eCommerce s...
drupal/components                                         3.0.0-beta2     Registers folders of components defined b...
drupal/core                                               9.2.5           Drupal is an open source content manageme...
drupal/core-composer-scaffold                             9.2.5           A flexible Composer project scaffold buil...
drupal/core-project-message                               9.2.5           Adds a message after Composer installation.
drupal/core-recommended                                   9.2.5           Locked core dependencies; require this pr...
drupal/css_editor                                         1.3.0           Customize your CSS directly from the brow...
drupal/ctools                                             3.7.0           Provides a number of utility and helper A...
drupal/default_content                                    1.0.0-alpha9    Imports default content when a module is ...
drupal/devel                                              4.1.1           Various blocks, pages, and functions for ...
drupal/email_registration                                 1.1.0           Allows users to register with an email ad...
drupal/entity                                             1.2.0           Provides expanded entity APIs, which will...
drupal/entity_browser                                     2.6.0           Entity browsing and selecting component.
drupal/entity_reference_revisions                         1.9.0           Entity Reference Revisions
drupal/entity_update                                      2.0.0-rc2       Update Drupal 8/9 Entity schema.
drupal/externalauth                                       1.4.0           Helper module to authenticate users using...
drupal/file_link                                          2.0.6           Extends the core Link module by storing m...
drupal/fontawesome                                        2.19.0          The web's most popular icon set and toolkit.
drupal/inline_entity_form                                 1.0.0-rc9       Provides a widget for inline management (...
drupal/jquery_ui                                          1.4.0           Provides jQuery UI library.
drupal/jquery_ui_datepicker                               1.1.0           Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                                   1.1.0           Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch                              1.0.0           Provides jQuery UI Touch Punch library.
drupal/key                                                1.14.0          Provides the ability to manage site-wide ...
drupal/maxlength                                          1.0.0-rc1       Limit the number of characters in textfie...
drupal/menu_per_role                                      1.3.0           Allows restricting access to menu items p...
drupal/menu_trail_by_path                                 1.3.0           Expand menus and set active-trail accordi...
drupal/paragraphs                                         1.12.0          Enables the creation of Paragraphs entities.
drupal/pathauto                                           1.8.0           Provides a mechanism for modules to autom...
drupal/profile                                            1.3.0           Provides configurable user profiles.
drupal/radix                                              dev-4.x 80a7bd7 Radix is a base theme for Drupal. It has ...
drupal/redirect_after_logout                              1.1.0           User redirect, after logout.
drupal/requirement                                        1.1.0           A Drupal module to that gives modules a w...
drupal/seckit                                             2.0.0           SecKit provides Drupal with various secur...
drupal/simplesamlphp_auth                                 3.2.0           Allows users to authenticate to a remote ...
drupal/simplesamlphp_custom_attributes                    1.1.0           Maps custom SAML SSO attributes to user f...
drupal/smtp                                               1.0.0           Allow for site emails to be sent through ...
drupal/state_machine                                      1.5.0           Provides code-driven workflow functionality.
drupal/swagger_ui_formatter                               3.3.0           Provides a Swagger UI field formatter for...
drupal/token                                              1.9.0           Provides a user interface for the Token A...
drupal/views_bulk_operations                              3.13.0          Adds an ability to perform bulk operation...
drush/drush                                               10.6.0          Drush is a command line shell and scripti...
egulias/email-validator                                   2.1.25          A library for validating emails against s...
enlightn/security-checker                                 v1.9.0          A PHP dependency vulnerabilities scanner ...
fightbulc/moment                                          1.33.0          Parse, validate, manipulate, and display ...
firebase/php-jwt                                          v5.4.0          A simple library to encode and decode JSO...
gettext/gettext                                           v4.8.5          PHP gettext manager
gettext/languages                                         2.8.1           gettext languages with plural rules
grasmash/expander                                         1.0.0           Expands internal property references in P...
grasmash/yaml-expander                                    1.4.0           Expands internal property references in a...
guzzlehttp/guzzle                                         6.5.5           Guzzle is a PHP HTTP client library
guzzlehttp/promises                                       1.4.1           Guzzle promises library
guzzlehttp/psr7                                           1.8.2           PSR-7 message implementation that also pr...
laminas/laminas-diactoros                                 2.6.0           PSR HTTP Message implementations
laminas/laminas-escaper                                   2.7.0           Securely and safely escape HTML, HTML att...
laminas/laminas-feed                                      2.14.1          provides functionality for consuming RSS ...
laminas/laminas-stdlib                                    3.3.1           SPL extensions, array utilities, error ha...
laminas/laminas-zendframework-bridge                      1.2.0           Alias legacy ZF class names to Laminas Pr...
league/container                                          2.5.0           A fast and intuitive dependency injection...
league/period                                             3.4.0           A time range immutable value object
masterminds/html5                                         2.7.4           An HTML5 parser and serializer.
nikic/php-parser                                          v4.12.0         A PHP parser written in PHP
oomphinc/composer-installers-extender                     2.0.0           Extend the composer/installers plugin to ...
pear/archive_tar                                          1.4.14          Tar file management class with compressio...
pear/console_getopt                                       v1.4.3          More info available on: http://pear.php.n...
pear/pear-core-minimal                                    v1.10.10        Minimal set of PEAR core files to be used...
pear/pear_exception                                       v1.0.2          The PEAR Exception base class.
php-http/client-common                                    2.4.0           Common HTTP Client implementations and to...
php-http/discovery                                        1.14.0          Finds installed HTTPlug implementations a...
php-http/guzzle6-adapter                                  v2.0.2          Guzzle 6 HTTP Adapter
php-http/httplug                                          2.2.0           HTTPlug, the HTTP client abstraction for PHP
php-http/message                                          1.12.0          HTTP Message related tools
php-http/message-factory                                  v1.0.2          Factory interfaces for PSR-7 HTTP Message
php-http/promise                                          1.1.0           Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common                           2.2.0           Common reflection classes used by phpdocu...
phpdocumentor/reflection-docblock                         5.2.2           With this component, a library can provid...
phpdocumentor/type-resolver                               1.4.0           A PSR-5 based resolver of Class names, Ty...
phpfastcache/riak-client                                  3.4.3           Riak client for PHP (Fork of the official...
phpmailer/phpmailer                                       v6.5.1          PHPMailer is a full-featured email creati...
psr/cache                                                 1.0.1           Common interface for caching libraries
psr/container                                             1.1.1           Common Container Interface (PHP FIG PSR-11)
psr/http-client                                           1.0.1           Common interface for HTTP clients
psr/http-factory                                          1.0.1           Common interfaces for PSR-7 HTTP message ...
psr/http-message                                          1.0.1           Common interface for HTTP messages
psr/log                                                   1.1.4           Common interface for logging libraries
psy/psysh                                                 v0.10.8         An interactive shell for modern PHP.
ralouphie/getallheaders                                   3.0.3           A polyfill for getallheaders.
robrichards/xmlseclibs                                    3.1.1           A PHP library for XML Security
simplesamlphp/assert                                      v0.0.13         A wrapper around webmozart/assert to make...
simplesamlphp/composer-module-installer                   v1.1.8          A Composer plugin that allows installing ...
simplesamlphp/saml2                                       v4.2.4          SAML2 PHP library from SimpleSAMLphp
simplesamlphp/simplesamlphp                               v1.19.1         A PHP implementation of a SAML 2.0 servic...
simplesamlphp/simplesamlphp-module-adfs                   v0.9.8          A module that implements the WS-federatio...
simplesamlphp/simplesamlphp-module-authcrypt              v0.9.3          This module provides authentication again...
simplesamlphp/simplesamlphp-module-authfacebook           v0.9.3          A module that is able to authenticate aga...
simplesamlphp/simplesamlphp-module-authorize              v0.9.3          This module provides a user authorization...
simplesamlphp/simplesamlphp-module-authtwitter            v0.9.1          A module that is able to perform authenti...
simplesamlphp/simplesamlphp-module-authwindowslive        v0.9.1          A module that is able to perform authenti...
simplesamlphp/simplesamlphp-module-authx509               v0.9.8          A module that is able to authenticate use...
simplesamlphp/simplesamlphp-module-authyubikey            v0.9.1          A module that is able to authenticate aga...
simplesamlphp/simplesamlphp-module-cas                    v0.9.1          A module that provides CAS authentication
simplesamlphp/simplesamlphp-module-cdc                    v0.9.1          A SimpleSAMLphp module that allows integr...
simplesamlphp/simplesamlphp-module-consent                v0.9.7          A module that will ask for user consent b...
simplesamlphp/simplesamlphp-module-consentadmin           v0.9.1          A module that allows users to manage thei...
simplesamlphp/simplesamlphp-module-discopower             v0.9.1          Fancy tabbed discovery service with filte...
simplesamlphp/simplesamlphp-module-exampleattributeserver v1.0.0          An example for SAML attributes queries
simplesamlphp/simplesamlphp-module-expirycheck            v0.9.3          The expirycheck module validates user's e...
simplesamlphp/simplesamlphp-module-ldap                   v0.9.12         A module that provides authentication aga...
simplesamlphp/simplesamlphp-module-memcachemonitor        v0.9.2          A module that is able display usage stati...
simplesamlphp/simplesamlphp-module-memcookie              v1.2.2          A SimpleSAMLphp module that allows integr...
simplesamlphp/simplesamlphp-module-metarefresh            v0.9.6          The metarefresh module will download and ...
simplesamlphp/simplesamlphp-module-negotiate              v0.9.11         The Negotiate module implements Microsoft...
simplesamlphp/simplesamlphp-module-oauth                  v0.9.3          A SimpleSAMLphp module that allows integr...
simplesamlphp/simplesamlphp-module-preprodwarning         v0.9.2          Display a warning when using a pre-produc...
simplesamlphp/simplesamlphp-module-radius                 v0.9.3          A module that is able perform authenticat...
simplesamlphp/simplesamlphp-module-riak                   v0.9.1          A module that is able to store key/value ...
simplesamlphp/simplesamlphp-module-sanitycheck            v0.9.1          Perform sanity checks on configuration
simplesamlphp/simplesamlphp-module-smartattributes        v0.9.1          The SmartAttributes module provides addit...
simplesamlphp/simplesamlphp-module-sqlauth                v0.9.3          This is a authentication module for authe...
simplesamlphp/simplesamlphp-module-statistics             v0.9.6          The SimpleSAMLphp statistics module
simplesamlphp/twig-configurable-i18n                      v2.3.4          This is an extension on top of Twig's i18...
stack/builder                                             v1.0.6          Builder for stack middleware based on Htt...
symfony-cmf/routing                                       2.3.3           Extends the Symfony routing component for...
symfony/cache                                             v5.3.7          Provides an extended PSR-6, PSR-16 (and t...
symfony/cache-contracts                                   v2.4.0          Generic abstractions related to caching
symfony/config                                            v4.4.30         Helps you find, load, combine, autofill a...
symfony/console                                           v4.4.25         Eases the creation of beautiful and testa...
symfony/debug                                             v4.4.25         Provides tools to ease debugging PHP code
symfony/dependency-injection                              v4.4.25         Allows you to standardize and centralize ...
symfony/deprecation-contracts                             v2.4.0          A generic function and convention to trig...
symfony/error-handler                                     v4.4.25         Provides tools to manage errors and ease ...
symfony/event-dispatcher                                  v4.4.25         Provides tools that allow your applicatio...
symfony/event-dispatcher-contracts                        v1.1.9          Generic abstractions related to dispatchi...
symfony/filesystem                                        v4.4.27         Provides basic utilities for the filesystem
symfony/finder                                            v5.3.7          Finds files and directories via an intuit...
symfony/framework-bundle                                  v4.4.30         Provides a tight integration between Symf...
symfony/http-client-contracts                             v2.4.0          Generic abstractions related to HTTP clients
symfony/http-foundation                                   v4.4.25         Defines an object-oriented layer for the ...
symfony/http-kernel                                       v4.4.25         Provides a structured process for convert...
symfony/inflector                                         v5.3.4          Converts words between their singular and...
symfony/mime                                              v5.3.0          Allows manipulating MIME messages
symfony/options-resolver                                  v4.4.30         Provides an improved replacement for the ...
symfony/polyfill-ctype                                    v1.23.0         Symfony polyfill for ctype functions
symfony/polyfill-iconv                                    v1.23.0         Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                            v1.23.1         Symfony polyfill for intl's grapheme_* fu...
symfony/polyfill-intl-idn                                 v1.23.0         Symfony polyfill for intl's idn_to_ascii ...
symfony/polyfill-intl-normalizer                          v1.23.0         Symfony polyfill for intl's Normalizer cl...
symfony/polyfill-mbstring                                 v1.23.0         Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                                    v1.23.0         Symfony polyfill backporting some PHP 7.2...
symfony/polyfill-php73                                    v1.23.0         Symfony polyfill backporting some PHP 7.3...
symfony/polyfill-php80                                    v1.23.0         Symfony polyfill backporting some PHP 8.0...
symfony/polyfill-php81                                    v1.23.0         Symfony polyfill backporting some PHP 8.1...
symfony/process                                           v4.4.25         Executes commands in sub-processes
symfony/property-access                                   v4.4.30         Provides functions to read and write from...
symfony/property-info                                     v4.4.30         Extracts information about PHP class' pro...
symfony/psr-http-message-bridge                           v2.1.0          PSR HTTP message bridge
symfony/routing                                           v4.4.25         Maps an HTTP request to a set of configur...
symfony/serializer                                        v4.4.25         Handles serializing and deserializing dat...
symfony/service-contracts                                 v2.4.0          Generic abstractions related to writing s...
symfony/string                                            v5.3.7          Provides an object-oriented API to string...
symfony/translation                                       v4.4.25         Provides tools to internationalize your a...
symfony/translation-contracts                             v2.4.0          Generic abstractions related to translation
symfony/validator                                         v4.4.25         Provides tools to validate values
symfony/var-dumper                                        v5.3.0          Provides mechanisms for walking through a...
symfony/var-exporter                                      v5.3.7          Allows exporting any serializable PHP dat...
symfony/yaml                                              v4.4.25         Loads and dumps YAML files
twig/extensions                                           v1.5.4          Common additional features for Twig that ...
twig/twig                                                 v2.14.6         Twig, the flexible, fast, and secure temp...
typo3/phar-stream-wrapper                                 v3.1.6          Interceptors for PHP's native phar:// str...
webflo/drupal-finder                                      1.2.2           Helper class to locate a Drupal installat...
webmozart/assert                                          1.10.0          Assertions to validate method input/outpu...
webmozart/path-util                                       2.3.0           A robust cross-platform utility for norma...
whitehat101/apr1-md5                                      v1.0.0          Apache's APR1-MD5 algorithm in pure PHP
hollywang@hollys-mbp release21 %

**Comment by shishir-intelli** [comment]
Hi @hollyhw15 ,

`2. Go to Portal, the product name and displayName both synced to portal, while the displayName doesn't shows as Title`
Can you tell us which page it is in the Drupal portal or the URL. Is this `/apis/##/#/overview` 
If yes, how did you manage to pull the Apigee Edge Api Product details over here, is there any customization done here?

**Comment by shishir-intelli** [comment]
Closing this for now, Feel free to reopen if in case you need further help.
