### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#516]
Hi Team,

We are upgrading Drupal from 8 to 9. The requirement is like - We don't want to use the composer file in the higher environments.
So we used the composer in one lower environment and copying the whole Developer Portal folder to the higher environments through CI/CD. But the Issue is - We don't know 
    -  What are the files specific to that environment?
    -  How can we protect the data like OAS documents which we uploaded?
    -  Where will be the files (like OAS documents, Environment specific files)?

And what is the process you normally suggest for the teams to upgrade. This upgrade is taking too much of time. Any help would be highly appreciated.

Thanks.,

**Comment by pradeepgorle13** [comment]
Can anyone help us out in this. We are planning to upgrade the api-devportal-Kickstart from 8 .8 to 9.x

**Comment by raakesh-blokhra** [comment]
@pradeepgorle13 I apologize for not responding earlier. We were in the process of D8 EOL so forgot to respond to this ticket. Can you please tell us if you are still having an issue and need help?

**Comment by phdhiren** [comment]
@pradeepgorle13 Closing this issue after inactivity. Feel free to reopen, if requires.
