### ISSUE TITLE
Access Denied installing a Module

### ISSUE THREAD

**Issue by BillMarx** [apigee/apigee-devportal-kickstart-drupal#520]
Hi,

   I am running Drupal 8.9.6 with the Apigee kickstart.  I am trying to install a module and I get Access denied
You are not allowed to access this page.  No reason for the error.  I am administrator and have full permissions.  I changed the settings.php and tried both TRUE and FALSE for the setting $settings['allow_authorize_operations' and still no luck.  Any help would be appreciated.

I should have mentioned,  I can get to the install module page.  It is after I choose the file and hit install that I get the access denied from authorize php

Thanks
Bill

**Comment by raakesh-blokhra** [comment]
@BillMarx Do you have anything in the logs that show you what the reason might be?

**Comment by BillMarx** [comment]
I see the below message in the log even though I am logged in as me and I have administrator rights

<html>
<body>


Type | access denied
-- | --
Monday, October 25, 2021 - 10:15
Anonymous (not verified)
http://apistoreappsjl-dev.prudential.com/core/authorize.php/?batch=1&id=80&op=start
https://apistoreappsjl-dev.prudential.com/admin/modules/install
authorize.php
Warning


</body>
</html>

**Comment by shishir-intelli** [comment]
@BillMarx ,

There may be something wrong with security on the file system. 
Where is the site hosted?

Set `$settings['allow_authorize_operations'] = TRUE;` and try installing with Composer or Drush.

**Comment by BillMarx** [comment]
I did this and the install failed 

 composer require drupal/content_templates
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Using version ^1.0@alpha for drupal/content_templates
./composer.json has been updated
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (8.9.6)
Deleting web/core - deleted
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/core (8.9.6): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download drupal/core from dist: The "https://api.github.com/repos/drupal/core/zipball/caf4e756d31dfb0c2e52cd0748e900efe4b57766" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
failed to open stream: Cannot connect to HTTPS server through proxy
    Now trying to download from source
  - Installing drupal/core (8.9.6): Cloning caf4e756d3
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+car038j1aa007+2021-10-26+1801
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden):

Installation failed, reverting ./composer.json to its original content.


  [Composer\Downloader\TransportException]
  The "https://api.github.com/" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
  failed to open stream: Cannot connect to HTTPS server through proxy

**Comment by shishir-intelli** [comment]
@BillMarx 
These seems to be your system requirement issues and not related to Apigee or Apigee Kickstart.

I will suggest you to:
1. Upgrade composer to version 2, you are using composer 1.
2. There is some issue with your 'Openssl ca-certificates' please reinstall it.
Refer : https://www.drupal.org/forum/support/post-installation/2020-06-17/ssl-cert-error-when-using-composer-to-install-modules-on

**Comment by shishir-intelli** [comment]
Hope this issue is resolved.
Closing this for now, feel free to reopen if in case you need any further help.
Thanks!
