### ISSUE TITLE
Unable to install Drupal9 Apigee Kickstart

### ISSUE THREAD

**Issue by pcrtx** [apigee/apigee-devportal-kickstart-drupal#523]
## Description
while trying to install Kickstart for Drupal 9, we have come across  "ext-bcmath missing error"

## Steps to Reproduce
[apigee@xyzhost ~]$ /opt/apigee-devportal-kickstart/bin/composer create-project apigee/devportal-kickstart-project:9.x-dev /opt/apigee-devportal-kickstart-drupal --no-interaction
Creating a "apigee/devportal-kickstart-project:9.x-dev" project at "/opt/apigee-devportal-kickstart-drupal"
Installing apigee/devportal-kickstart-project (9.x-dev 2a0e974f5f9d54f5faf4e5201f49b2a9b665eeb2)
  - Downloading apigee/devportal-kickstart-project (9.x-dev 2a0e974)
  - Installing apigee/devportal-kickstart-project (9.x-dev 2a0e974): Extracting archive
Created project in /opt/apigee-devportal-kickstart-drupal
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/apigee_m10n ^2 -> satisfiable by drupal/apigee_m10n[2.0.0].
    - drupal/apigee_m10n 2.0.0 requires ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
  Problem 2
    - drupal/commerce[dev-2.x, 2.21.0, ..., 2.27.0] require ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
    - drupal/commerce 2.x-dev is an alias of drupal/commerce dev-2.x and thus requires it to be installed too.
    - Root composer.json requires drupal/commerce ^2.21 -> satisfiable by drupal/commerce[2.21.0, ..., 2.x-dev (alias of dev-2.x)].

Please Help

## Notes
The current php that is installed came along from apigee 
[apigee@xyzhost ~]$ yum list installed  | grep -i php
apigee-php.noarch               7.4.20-0.0.405          @apigee-release
php74-cli.x86_64                7.4.20-1.el7.ius        @apigee-thirdparty
php74-common.x86_64             7.4.20-1.el7.ius        @apigee-thirdparty
php74-fpm.x86_64                7.4.20-1.el7.ius        @apigee-thirdparty
php74-gd.x86_64                 7.4.20-1.el7.ius        @apigee-thirdparty
php74-json.x86_64               7.4.20-1.el7.ius        @apigee-thirdparty
php74-ldap.x86_64               7.4.20-1.el7.ius        @apigee-thirdparty
php74-mbstring.x86_64           7.4.20-1.el7.ius        @apigee-thirdparty
php74-mysqlnd.x86_64            7.4.20-1.el7.ius        @apigee-thirdparty
php74-pdo.x86_64                7.4.20-1.el7.ius        @apigee-thirdparty
php74-pgsql.x86_64              7.4.20-1.el7.ius        @apigee-thirdparty
php74-process.x86_64            7.4.20-1.el7.ius        @apigee-thirdparty
php74-xml.x86_64                7.4.20-1.el7.ius        @apigee-thirdparty

[apigee@xyzhost apigee-devportal-kickstart]$ php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
zlib

The available bcmath packages on the system  are 
[root@xyzhost ~]# yum list | grep bcmath
php-bcmath.x86_64               5.4.16-48.el7   q4_rhel-x86_64-server-optional-7
php54-php-bcmath.x86_64         5.4.40-4.el7    q4_rhel-x86_64-server-7-rhscl-1
php55-php-bcmath.x86_64         5.5.21-5.el7    q4_rhel-x86_64-server-7-rhscl-1
rh-php56-php-bcmath.x86_64      5.6.25-1.el7    q4_rhel-x86_64-server-7-rhscl-1
rh-php70-php-bcmath.x86_64      7.0.27-2.el7    q4_rhel-x86_64-server-7-rhscl-1
rh-php71-php-bcmath.x86_64      7.1.30-2.el7    q4_rhel-x86_64-server-7-rhscl-1
rh-php72-php-bcmath.x86_64      7.2.24-1.el7    q4_rhel-x86_64-server-7-rhscl-1
rh-php73-php-bcmath.x86_64      7.3.29-1.el7    q4_rhel-x86_64-server-7-rhscl-1

Can we install rh-php73-php-bcmath.x86_64 which is different from apigee which is on 7.4?  The following dependencies also get installed when rh-php73-php-bcmath.x86_64 is installed.

[root@xyzhost ~]# yum install rh-php73-php-bcmath.x86_64
Loaded plugins: aliases, changelog, langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager, tmprepo, verify, versionlock
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package rh-php73-php-bcmath.x86_64 0:7.3.29-1.el7 will be installed
--> Processing Dependency: rh-php73-php-common(x86-64) = 7.3.29-1.el7 for package: rh-php73-php-bcmath-7.3.29-1.el7.x86_64
--> Running transaction check
---> Package rh-php73-php-common.x86_64 0:7.3.29-1.el7 will be installed
--> Processing Dependency: rh-php73-php-zip(x86-64) = 7.3.29-1.el7 for package: rh-php73-php-common-7.3.29-1.el7.x86_64
--> Processing Dependency: rh-php73-php-json(x86-64) = 7.3.29-1.el7 for package: rh-php73-php-common-7.3.29-1.el7.x86_64
--> Processing Dependency: rh-php73-runtime for package: rh-php73-php-common-7.3.29-1.el7.x86_64
--> Running transaction check
---> Package rh-php73-php-json.x86_64 0:7.3.29-1.el7 will be installed
---> Package rh-php73-php-zip.x86_64 0:7.3.29-1.el7 will be installed
---> Package rh-php73-runtime.x86_64 0:1-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================================================================
 Package                                                    Arch                                          Version                                               Repository                                                              Size
=============================================================================================================================================================================================================================================
Installing:
 rh-php73-php-bcmath                                        x86_64                                        7.3.29-1.el7                                          q4_rhel-x86_64-server-7-rhscl-1                                         61 k
Installing for dependencies:
 rh-php73-php-common                                        x86_64                                        7.3.29-1.el7                                          q4_rhel-x86_64-server-7-rhscl-1                                        689 k
 rh-php73-php-json                                          x86_64                                        7.3.29-1.el7                                          q4_rhel-x86_64-server-7-rhscl-1                                         55 k
 rh-php73-php-zip                                           x86_64                                        7.3.29-1.el7                                          q4_rhel-x86_64-server-7-rhscl-1                                         91 k
 rh-php73-runtime                                           x86_64                                        1-1.el7                                               q4_rhel-x86_64-server-7-rhscl-1                                        1.1 M

Transaction Summary
=============================================================================================================================================================================================================================================
Install  1 Package (+4 Dependent packages)

## Version Info
Composer version 2.1.11 2021-11-02 12:10:25

The php version installed is 
[apigee@xyzhost apigee-devportal-kickstart]$ php -v
PHP 7.4.20 (cli) (built: Jun  7 2021 17:22:38) ( NTS )

**Comment by raakesh-blokhra** [comment]
@pcrtx Did/Can you try the following command?

yum install bcmath

AND

yum install php-bcmath

Please try deleting composer.lock file and run `composer install`, after you run the commands and let us know if still running into issues.

**Comment by giteshk** [comment]
You may need to install the bc-math rpm from : https://repo.ius.io/7/x86_64/packages/p/

**Comment by pcrtx** [comment]
I have tried all the suggested options  and we are running into dependency conflicts -  since apigee php is of version 7.4.20,  how can I get a compatible version of bcmath for 7.4.20?  


[root@somehostname ~]# **yum install bcmath**
Loaded plugins: aliases, changelog, langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager, tmprepo, verify, versionlock
This system is receiving updates from RHN Classic or Red Hat Satellite.
**No package bcmath available.**
Error: Nothing to do


[root@somehostname ~]# **yum install php-bcmath**
Loaded plugins: aliases, changelog, langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager, tmprepo, verify, versionlock
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package php-bcmath.x86_64 0:5.4.16-48.el7 will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.16-48.el7 for package: php-bcmath-5.4.16-48.el7.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:5.4.16-48.el7 will be installed
--> Processing Dependency: libzip.so.2()(64bit) for package: php-common-5.4.16-48.el7.x86_64
--> Running transaction check
---> Package libzip.x86_64 0:0.10.1-8.el7 will be installed
--> Processing Conflict: php74-common-7.4.20-1.el7.ius.x86_64 conflicts php-common < 7.4.20-1.el7.ius
--> Processing Conflict: php74-json-7.4.20-1.el7.ius.x86_64 conflicts php-json < 7.4.20-1.el7.ius
--> Finished Dependency Resolution
**Error: php74-json conflicts with php-common-5.4.16-48.el7.x86_64
Error: php74-common conflicts with php-common-5.4.16-48.el7.x86_64**
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


[root@somehostname ~]# rpm -i **/var/tmp/php-bcmath-7.4.25-1.el7.remi.x86_64.rpm**
warning: /var/tmp/php-bcmath-7.4.25-1.el7.remi.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 00f97f56: NOKEY
error: Failed dependencies:
        **php-common(x86-64) = 7.4.25-1.el7.remi is needed by php-bcmath-7.4.25-1.el7.remi.x86_64**

**Comment by phdhiren** [comment]
@pcrtx 

Looks like there are conflicts with PHP version. If PHP 5.4 and 7.4 both are installed?

Try following command for PHP 7.4 bcmath extension.
`yum install php7.4-bcmath`

**Comment by pcrtx** [comment]
[root@xxxxxxxx~]# yum install php7.4-bcmath
Loaded plugins: aliases, changelog, langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager, tmprepo, verify, versionlock
This system is receiving updates from RHN Classic or Red Hat Satellite.
**No package php7.4-bcmath available**.
Error: Nothing to do

**Comment by phdhiren** [comment]
@pcrtx 

Please help me understand which PHP version you're using, as there are reference of 5.4, 7.3 and 7.4 in your logs.

You should be using PHP 7.4, You should remove other versions. Even PHP 7.3 security support also ending soon - https://www.php.net/supported-versions.php

**Comment by pcrtx** [comment]
was able to resolve the issue after installing packages from ius as pointed by giteshk.

Thank You all for the support.
