### ISSUE TITLE
Best practice for managing customized Apigee Kickstart module

### ISSUE THREAD

**Issue by huilinks** [apigee/apigee-devportal-kickstart-drupal#525]
I have a Drupal Dev Portal site with Apigee Kickstart managed by composer. If I have customized codes of the Apigee Kickstart module, when I update the Kickstart module with command “composer update apigee/devportal-kickstart-project”, my customizations might be overwritten by the update. Does Apigee have/know the best practice guideline of updating customized Kickstart module?

Thanks

**Comment by phdhiren** [comment]
@huilinks 

IMO, You should watch this repository ( https://github.com/apigee/devportal-kickstart-project-composer ), if you're planning to change composer.json and manage your project by composer.

**Comment by phdhiren** [comment]
I hope above link was helpful.
Closing the ticket now, feel free to reopen, if require.
