### ISSUE TITLE
Kickstart install version clarification 

### ISSUE THREAD

**Issue by pcrtx** [apigee/apigee-devportal-kickstart-drupal#526]
## Description
as referred in the documentation https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart,  we have followed all of the steps/pre-requisites.

core/install.php shows page with Apigee Developer Portal Kickstart **8.9.1**.  Please confirm that version 8.9.1 is the intended version for this install.

## Screenshots
![image](https://user-images.githubusercontent.com/94010640/142434218-b057282f-0c99-436f-a3e2-43700800e113.png)

**Comment by shishir-intelli** [comment]
Hi @pcrtx 
Which command you ran to install Drupal Apigee Developer Portal kickstart installation? We have already removed the references to Drupal 8 from https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart.

We recommend Drupal 9, please refer this link https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/get-started-with-kickstart for Apigee Developer Portal kickstart installation

**Comment by pcrtx** [comment]
/opt/apigee-devportal-kickstart/bin/composer create-project apigee/devportal-kickstart-project:9.x-dev /opt/apigee-devportal-kickstart-drupal --no-interaction

**Comment by pcrtx** [comment]
issue is caused by composer.json file,  it has references to durpal 8

{
  "name": "apigee/devportal-kickstart-project",
  "description": "Composer project template for the Apigee Developer Portal Drupal distribution.",
  "type": "project",
  "license": "GPL-2.0-or-later",
  "homepage": "https://www.drupal.org/project/apigee_devportal_kickstart",
  "support": {
    "docs": "https://www.drupal.org/docs/**8**/modules/apigee-developer-portal-kickstart"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.drupal.org/**8**"
    },

**Comment by shishir-intelli** [comment]
@pcrtx  No, its not an issue, 
https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg

Instead check Drupal core version in composer.json, it should be 9.
I ran the same command which you shared and which is there in the doc as well and this is what I see while installation
![Screenshot 2021-11-19 12 36 21 PM](https://user-images.githubusercontent.com/75600200/142581669-c71aff3e-e43b-469b-82b7-7f5edbbda318.png)

Can you please confirm which version is there in your composer file for 
```
  "drupal/core-composer-scaffold"
  "drupal/core-project-message"
  "drupal/core-recommended"
```

**Comment by pcrtx** [comment]
@shishir-intelli, Thank You for checking.

The following are the contents of composer.json

    "drupal/core-composer-scaffold": "^9",
    "drupal/core-project-message": "^9",
    "drupal/core-recommended": "^9",
[Apigee-Drupal-9-Install-RunningNotes.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/7584484/Apigee-Drupal-9-Install-RunningNotes.txt)

Also composer.json is attached here
[composer.json.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/7584485/composer.json.txt)

**Comment by pcrtx** [comment]
ngnix was pointing to the drupal 8 conf directories.  it is working now

![image](https://user-images.githubusercontent.com/94010640/143042787-5c9f52fb-14ff-4d67-8fa5-92a86e02968b.png)

**Comment by raakesh-blokhra** [comment]
@pcrtx Thanks for the update. Closing this issue now since it is working. If you run into any issues, please feel free to reopen it.
