### ISSUE TITLE
Facing an issue while trying to configure Apigee module

### ISSUE THREAD

**Issue by NNV111** [apigee/apigee-devportal-kickstart-drupal#543]
We have Drupal set up and Apigee module installed in AWS workspace. Apigee also runs on private cloud. 
While trying to configure the details to establish the connection, facing the following error -- 
![image](https://user-images.githubusercontent.com/87411570/157813594-69bde8f5-b750-437f-99c1-9fd64e883470.png)

![image](https://user-images.githubusercontent.com/87411570/157814602-f1042107-8511-4b50-bf20-3b1633601c9d.png)

Could you please let me know what configuration details I've missed

**Comment by shishir-intelli** [comment]
@NNV111 
Can you make sure you have correctly configured the private file settings.
See https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee#configure-private-file

**Comment by NNV111** [comment]
@shishir-intelli 
 I have configured the path in settings.php and the path is reflecting under the file system in the UI as well
 Cleared the cache, changed the permissions for this file (chmod -R 775 '../private';)
I get the above error when this path has been provided.

![image](https://user-images.githubusercontent.com/87411570/158157022-eece9aef-6ecc-40a2-b96c-29499624d6ba.png)


Fetched this path using the command "find / -name private" 

I have created a private directory in the drupal folder and gave that path, but that didn't work either.
Have gotten the same error.
Could you let me know if there's something I am doing wrong.

**Comment by shishir-intelli** [comment]
@NNV111  
It seems like the private file system path which you have set is incorrect.
I will suggest you create the private folder on `/www `and not inside Drupal and should not accessible over the web and also set the absolute path in `setting.php` .
So IMO the path should look like `/var/www/private` in **`Private file system path`** and set the access permission for that folder.

**Comment by NNV111** [comment]
@shishir-intelli 
Have tried as you've suggested, created a private folder and placed it outside the Drupal i.e. (/var/www/private), set the absolute path in settings.php, gave recursive permissions by using the command chmod -R 775 and chmod -R 777
Still facing the exact same error. The OauthTokenFileStorage.php file at line 200 is pointing out to this if block that's raising the error
![image](https://user-images.githubusercontent.com/87411570/158752828-894613e6-7888-4665-b127-870aa24717b3.png)


If possible, could you please let me know what else I could be missing out for the drupal-apigee connection establishment?
Also, while running the curl command in Drupal server instance, we are getting the response when hitting the apigee management server.

**Comment by shishir-intelli** [comment]
@NNV111 
No, you are not missing out anything, its just that your private directory is not set properly.
The `OauthTokenFileStorage.php` checkRequirements method prepares the directory, either the path is incorrect or you are missing out of some permission on that directory.

Can you share me the screenshot of `/admin/config/media/file-system` page.

Meanwhile, you can checkout 
https://www.drupal.org/docs/8/core/modules/file/overview#s-private-file-system-settings-in-drupal-8 
or 
https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for-private-cloud#s-secure-edge-connection-settings
and try it out.

_Note: Caches need to be cleared when this value is changed to make the private:// stream wrapper available to the system._

**Comment by phdhiren** [comment]
@NNV111 

Hope the solution worked for you.
Closing the issue for now, feel free to reopen if required.
