### ISSUE TITLE
Error occured during portal setup

### ISSUE THREAD

**Issue by AyoSal** [apigee/apigee-devportal-kickstart-drupal#557]
## Description
Error occured when setting up apigee developer portal after launch from marketplace.

error screen is attached.
was fixed by deleting devportal database in cloudsql and restarting the setup process at the url ![image](https://user-images.githubusercontent.com/27664278/161067843-dc73b7cf-d921-4a92-80e5-ca41b0c5e7ff.png)

**Comment by raakesh-blokhra** [comment]
@AyoSal I was told that this issue was resolved by deleting DB tables and re-initiating the installation, and this can be closed now. If that is not the case and you need help please reopen this issue. Thank you
