### ISSUE TITLE
Applying patch fails at the end of installation

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-devportal-kickstart-drupal#568]
Some patches fail to apply while installing via composer.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/30699044/176722080-48ede535-0fda-484b-a2e6-cc323e3bcef8.png)

**Comment by shishir-intelli** [comment]
Hi @simantstha 
Can you share the `composer.json` file which is causing this issue.

Also, some of the time problems maybe OS does not have patch module install.
Try this `patch --version` to check the version
or 
`sudo yum install patch` to install if missing.

**Comment by simantstha** [comment]
{
  "name": "apigee/devportal-kickstart-project",
  "description": "Composer project template for the Apigee Developer Portal Drupal distribution.",
  "type": "project",
  "license": "GPL-2.0-or-later",
  "homepage": "https://www.drupal.org/project/apigee_devportal_kickstart",
  "support": {
    "docs": "https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    },
    {
      "type": "package",
      "package": {
        "name": "furf/jquery-ui-touch-punch",
        "version": "dev-master",
        "type": "drupal-library",
        "dist": {
          "url": "https://github.com/furf/jquery-ui-touch-punch/archive/master.zip",
          "type": "zip"
        }
      }
    }
  ],
  "require": {
    "php": "^7.4 || ^8.0",
    "apigee/apigee_devportal_kickstart": "^2",
    "composer/installers": "^1.9",
    "drupal/apigee_m10n": "^2",
    "drupal/commerce": "^2.21",
    "drupal/core-composer-scaffold": "^9",
    "drupal/core-project-message": "^9",
    "drupal/core-recommended": "^9",
    "drupal/google_analytics": "^3.1",
    "drupal/jsonapi_extras": "^3.17",
    "drupal/smtp": "^1.0",
    "furf/jquery-ui-touch-punch": "dev-master"
  },
  "require-dev": {
    "apigee/apigee-mock-client-php": "^1.1",
    "drupal/core-dev": "^9",
    "drush/drush": "^11"
  },
  "conflict": {
    "drupal/drupal": "*"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "sort-packages": true,
    "process-timeout": 0,
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true,
      "cweagans/composer-patches": true,
      "composer/installers": true,
      "drupal/core-composer-scaffold": true,
      "drupal/core-project-message": true
    }
  },
  "extra": {
    "drupal-scaffold": {
      "locations": {
        "web-root": "web/"
      }
    },
    "installer-paths": {
      "web/core": ["type:drupal-core"],
      "web/libraries/{$name}": ["type:drupal-library"],
      "web/modules/contrib/{$name}": ["type:drupal-module"],
      "web/profiles/contrib/{$name}": ["type:drupal-profile"],
      "web/themes/contrib/{$name}": ["type:drupal-theme"],
      "drush/Commands/contrib/{$name}": ["type:drupal-drush"],
      "web/modules/custom/{$name}": ["type:drupal-custom-module"],
      "web/themes/custom/{$name}": ["type:drupal-custom-theme"]
    },
    "drupal-core-project-message": {
      "include-keys": ["homepage", "support"],
      "post-create-project-cmd-message": [
        "<bg=blue;fg=white>                                                                                 </>",
        "<bg=blue;fg=white>  Congratulations, you’ve installed the Apigee Developer Portal Drupal codebase  </>",
        "<bg=blue;fg=white>  from the apigee/devportal-kickstart-project template!                          </>",
        "<bg=blue;fg=white>                                                                                 </>",
        "",
        "<bg=yellow;fg=black>Next steps</>:",
        "  * Install the site: https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/get-started-with-kickstart",
        "  * Read the guide: https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart",
        "  * Report issues : https://github.com/apigee/apigee-devportal-kickstart-drupal/issues"
      ]
    },
    "enable-patching": true,
    "patches": {
      "drupal/core": {
          "Support entities that are neither content nor config entities":"https://www.drupal.org/files/issues/2020-12-02/3042467-50.patch"
      },
      "drupal/jsonapi_extras":{
          "JSON APIS EXTRAS BULK PATCH": "https://www.drupal.org/files/issues/2020-02-20/add-enable-disable-all-buttons--2896799--10.patch"
      }
    },
    "patchLevel": {
      "drupal/core": "-p2"
    }
  },
  "scripts": {
    "quick-start": [
      "composer install",
      "php web/core/scripts/drupal quick-start apigee_devportal_kickstart"
    ]
  }
}

**Comment by shishir-intelli** [comment]
Hi @simantstha 
`Composer.json` looks good
What is the patch version on your system?

To debug the issue further can you try `composer install -vvv` or `composer update -vvv` and share the error message, so we can see the exact error.

**Comment by simantstha** [comment]
![image](https://user-images.githubusercontent.com/30699044/177362079-7169faff-1e42-48b0-a0bd-9210578fd8a1.png)
This is the message for composer update -vvv
also i am working on windows can you tell me the best way to install patch ? I researched online they dont seem to work

**Comment by shishir-intelli** [comment]
Hi @simantstha
The composer and patch module on the windows system doesn't seem to be configured properly.
IMO in windows you need to add the patch.exe path to the Environment Variables -> System variables -> Path
Check out this link https://www.drupal.org/project/wxt/issues/3035117
and for composer check out https://getcomposer.org/doc/01-basic-usage.md

**Comment by shishir-intelli** [comment]
Hi @simantstha 
We hope your issue has been resolved.
Closing this issue for now, Please feel free to re-open this issue if you need any further help related to Apigee.
