### ISSUE TITLE
Installing File_entity module gives me unexpected error

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-devportal-kickstart-drupal#571]
## Description
Installing file_entity module bugs the whole portal.

## Steps to Reproduce
1. Go to extend
2. Click on file_entity module
3. Install 

## Actual Behavior
![image](https://user-images.githubusercontent.com/30699044/181603453-dce9eb77-c337-4a94-a89c-041d8496ca0a.png)

## Expected Behavior
Should have been installed

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.
apigee/apigee-client-php                       2.0.16       Client library for connecting to the Apigee Edge API.
apigee/apigee-mock-client-php                  1.1.1        To be used for queueing mock API responses for the `ap...
apigee/apigee_devportal_kickstart              2.1.0        A fast demo and starting point for Apigee Developer Po...
asm89/stack-cors                               1.3.0        Cross-origin resource sharing library and stack middle...
behat/mink                                     v1.10.0      Browser controller/emulator abstraction for PHP
behat/mink-selenium2-driver                    v1.6.0       Selenium2 (WebDriver) driver for Mink framework
chi-teck/drupal-code-generator                 2.5.3        Drupal code generator
clue/stream-filter                             v1.6.0       A simple and modern approach to stream filtering in PHP
commerceguys/addressing                        v1.3.0       Addressing library powered by CLDR and Google's addres...
commerceguys/intl                              v1.1.1       Internationalization library powered by CLDR data.
composer/ca-bundle                             1.3.3        Lets you find a path to the system CA bundle, and incl...
composer/composer                              2.2.17       Composer helps you declare, manage and install depende...
composer/installers                            v1.12.0      A multi-framework Composer library installer
composer/metadata-minifier                     1.0.0        Small utility library that handles metadata minificati...
composer/pcre                                  1.0.1        PCRE wrapping library that offers type-safe preg_* rep...
composer/semver                                3.3.2        Semver library that offers utilities, version constrai...
composer/spdx-licenses                         1.5.7        SPDX licenses list and validation library.
composer/xdebug-handler                        3.0.3        Restarts a process without Xdebug.
consolidation/annotated-command                4.5.6        Initialize Symfony Console commands from annotated com...
consolidation/config                           2.1.1        Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data       2.0.2        This project uses dflydev/dot-access-data to provide s...
consolidation/log                              2.1.1        Improved Psr-3 / Psr\Log logger based on Symfony Conso...
consolidation/output-formatters                4.2.2        Format text by applying transformations provided by pl...
consolidation/robo                             3.0.10       Modern task runner
consolidation/self-update                      2.0.5        Provides a self:update command for Symfony Console app...
consolidation/site-alias                       3.1.5        Manage alias records for local and remote sites.
consolidation/site-process                     4.2.0        A thin wrapper around the Symfony Process Component th...
cweagans/composer-patches                      1.7.2        Provides a way to patch Composer packages.
dealerdirect/phpcodesniffer-composer-installer v0.7.2       PHP_CodeSniffer Standards Composer Installer Plugin
dflydev/dot-access-data                        v3.0.1       Given a deep data structure, access data by dot notation.
doctrine/annotations                           1.13.3       Docblock Annotations Parser
doctrine/collections                           1.6.8        PHP Doctrine Collections library that adds additional ...
doctrine/instantiator                          1.4.1        A small, lightweight utility to instantiate objects in...
doctrine/lexer                                 1.2.3        PHP Doctrine Lexer parser library that can be used in ...
doctrine/reflection                            1.2.3        The Doctrine Reflection project is a simple library us...
drupal/address                                 1.10.0       Provides functionality for storing, validating and dis...
drupal/admin_toolbar                           3.1.0        Provides a drop-down menu interface to the core Drupal...
drupal/adminimal_admin_toolbar                 1.11.0       Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                      3.0.2        Apigee API Catalog for Drupal
drupal/apigee_edge                             2.0.5        Apigee Edge for Drupal.
drupal/apigee_m10n                             2.0.2        Apigee Edge Monetization for Drupal
drupal/better_exposed_filters                  5.2.0        Replaces the Views default single- or multi-select box...
drupal/coder                                   8.3.15       Coder is a library to review Drupal code.
drupal/commerce                                2.30.0       Drupal Commerce is a flexible eCommerce solution.
drupal/components                              2.4.0        Registers folders of components defined by your theme ...
drupal/core                                    9.4.3        Drupal is an open source content management platform p...
drupal/core-composer-scaffold                  9.4.3        A flexible Composer project scaffold builder.
drupal/core-dev                                9.4.3        require-dev dependencies from drupal/drupal; use in ad...
drupal/core-project-message                    9.4.3        Adds a message after Composer installation.
drupal/core-recommended                        9.4.3        Core and its dependencies with known-compatible minor ...
drupal/ctools                                  4.0.0        Provides a number of utility and helper APIs for Drupa...
drupal/default_content                         1.0.0-alpha9 Imports default content when a module is enabled
drupal/email_registration                      1.1.0        Allows users to register with an email address as thei...
drupal/entity                                  1.3.0        Provides expanded entity APIs, which will be moved to ...
drupal/entity_reference_revisions              1.9.0        Entity Reference Revisions
drupal/file_entity                             2.0.0-beta9  Extends Drupal file entities to be fieldable and viewa...
drupal/file_link                               2.0.6        Extends the core Link module by storing metadata about...
drupal/file_upload_options                     1.0.0-beta1  Specify what should happen when uploaded files have th...
drupal/fontawesome                             2.23.0       The web's most popular icon set and toolkit.
drupal/google_analytics                        3.1.0        Allows your site to be tracked by Google Analytics by ...
drupal/inline_entity_form                      1.0.0-rc12   Provides a widget for inline management (creation, mod...
drupal/jquery_ui                               1.4.0        Provides jQuery UI library.
drupal/jquery_ui_datepicker                    1.2.0        Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                        1.1.0        Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch                   1.0.1        Provides jQuery UI Touch Punch library.
drupal/jsonapi_extras                          3.20.0       JSON:API Extras provides a means to override and provi...
drupal/key                                     1.15.0       Provides the ability to manage site-wide keys
drupal/paragraphs                              1.14.0       Enables the creation of Paragraphs entities.
drupal/pathauto                                1.10.0       Provides a mechanism for modules to automatically gene...
drupal/profile                                 1.4.0        Provides configurable user profiles.
drupal/radix                                   4.11.0       Radix is a base theme for Drupal. It has Bootstrap, Sa...
drupal/requirement                             1.1.0        A Drupal module to that gives modules a way to declare...
drupal/restui                                  1.20.0       Provides a user interface to manage REST resources.
drupal/smtp                                    1.0.0        Allow for site emails to be sent through an SMTP serve...
drupal/state_machine                           1.6.0        Provides code-driven workflow functionality.
drupal/token                                   1.10.0       Provides a user interface for the Token API, some miss...
drush/drush                                    11.1.1       Drush is a command line shell and scripting interface ...
e0ipso/shaper                                  1.2.4        Lightweight library to handle in and out transformatio...
easyrdf/easyrdf                                1.1.1        EasyRdf is a PHP library designed to make it easy to c...
egulias/email-validator                        3.2.1        A library for validating emails against several RFCs
enlightn/security-checker                      v1.10.0      A PHP dependency vulnerabilities scanner based on the ...
fightbulc/moment                               1.33.0       Parse, validate, manipulate, and display dates in PHP ...
firebase/php-jwt                               v5.5.1       A simple library to encode and decode JSON Web Tokens ...
friends-of-behat/mink-browserkit-driver        v1.6.1       Symfony2 BrowserKit driver for Mink framework
furf/jquery-ui-touch-punch                     dev-master
grasmash/expander                              2.0.3        Expands internal property references in PHP arrays file.
guzzlehttp/guzzle                              6.5.8        Guzzle is a PHP HTTP client library
guzzlehttp/promises                            1.5.1        Guzzle promises library
guzzlehttp/psr7                                1.9.0        PSR-7 message implementation that also provides common...
instaclick/php-webdriver                       1.4.14       PHP WebDriver for Selenium 2
jeremeamia/superclosure                        2.4.0        Serialize Closure objects, including their context and...
justinrainbow/json-schema                      5.2.12       A library to validate a json schema.
laminas/laminas-diactoros                      2.11.3       PSR HTTP Message implementations
laminas/laminas-escaper                        2.9.0        Securely and safely escape HTML, HTML attributes, Java...
laminas/laminas-feed                           2.17.0       provides functionality for consuming RSS and Atom feeds
laminas/laminas-stdlib                         3.7.1        SPL extensions, array utilities, error handlers, and more
league/container                               4.2.0        A fast and intuitive dependency injection container.
league/period                                  4.12.0       Time range API for PHP
masterminds/html5                              2.7.5        An HTML5 parser and serializer.
mikey179/vfsstream                             v1.6.10      Virtual file system to mock the real file system in un...
myclabs/deep-copy                              1.11.0       Create deep copies (clones) of your objects
nikic/php-parser                               v4.14.0      A PHP parser written in PHP
pear/archive_tar                               1.4.14       Tar file management class with compression support (gz...
pear/console_getopt                            v1.4.3       More info available on: http://pear.php.net/package/Co...
pear/pear-core-minimal                         v1.10.11     Minimal set of PEAR core files to be used as composer ...
pear/pear_exception                            v1.0.2       The PEAR Exception base class.
phar-io/manifest                               2.0.3        Component for reading phar.io manifest information fro...
phar-io/version                                3.2.1        Library for handling version information and constraints
php-http/client-common                         2.5.0        Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                             1.14.3       Finds installed HTTPlug implementations and PSR-7 mess...
php-http/guzzle6-adapter                       v2.0.2       Guzzle 6 HTTP Adapter
php-http/httplug                               2.3.0        HTTPlug, the HTTP client abstraction for PHP
php-http/message                               1.13.0       HTTP Message related tools
php-http/message-factory                       v1.0.2       Factory interfaces for PSR-7 HTTP Message
php-http/promise                               1.1.0        Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common                2.2.0        Common reflection classes used by phpdocumentor to ref...
phpdocumentor/reflection-docblock              5.3.0        With this component, a library can provide support for...
phpdocumentor/type-resolver                    1.6.1        A PSR-5 based resolver of Class names, Types and Struc...
phpmailer/phpmailer                            v6.6.3       PHPMailer is a full-featured email creation and transf...
phpspec/prophecy                               v1.15.0      Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser                          1.6.4        PHPDoc parser with support for nullable, intersection ...
phpunit/php-code-coverage                      9.2.15       Library that provides collection, processing, and rend...
phpunit/php-file-iterator                      3.0.6        FilterIterator implementation that filters files based...
phpunit/php-invoker                            3.1.1        Invoke callables with a timeout
phpunit/php-text-template                      2.0.4        Simple template engine.
phpunit/php-timer                              5.0.3        Utility class for timing
phpunit/phpunit                                9.5.21       The PHP Unit Testing framework.
politsin/jquery-ui-touch-punch                 1.0          Extension to jQuery UI for mobile touch event support.
psr/cache                                      1.0.1        Common interface for caching libraries
psr/container                                  1.1.2        Common Container Interface (PHP FIG PSR-11)
psr/http-client                                1.0.1        Common interface for HTTP clients
psr/http-factory                               1.0.1        Common interfaces for PSR-7 HTTP message factories
psr/http-message                               1.0.1        Common interface for HTTP messages
psr/log                                        1.1.4        Common interface for logging libraries
psy/psysh                                      v0.11.7      An interactive shell for modern PHP.
ralouphie/getallheaders                        3.0.3        A polyfill for getallheaders.
react/promise                                  v2.9.0       A lightweight implementation of CommonJS Promises/A fo...
sebastian/cli-parser                           1.0.1        Library for parsing CLI options
sebastian/code-unit                            1.0.8        Collection of value objects that represent the PHP cod...
sebastian/code-unit-reverse-lookup             2.0.3        Looks up which function or method a line of code belon...
sebastian/comparator                           4.0.6        Provides the functionality to compare PHP values for e...
sebastian/complexity                           2.0.2        Library for calculating the complexity of PHP code units
sebastian/diff                                 4.0.4        Diff implementation
sebastian/environment                          5.1.4        Provides functionality to handle HHVM/PHP environments
sebastian/exporter                             4.0.4        Provides the functionality to export PHP variables for...
sebastian/global-state                         5.0.5        Snapshotting of global state
sebastian/lines-of-code                        1.0.3        Library for counting the lines of code in PHP source code
sebastian/object-enumerator                    4.0.4        Traverses array structures and object graphs to enumer...
sebastian/object-reflector                     2.0.4        Allows reflection of object attributes, including inhe...
sebastian/recursion-context                    4.0.4        Provides functionality to recursively process PHP vari...
sebastian/resource-operations                  3.0.3        Provides a list of PHP built-in functions that operate...
sebastian/type                                 3.0.0        Collection of value objects that represent the types o...
sebastian/version                              3.0.2        Library that helps with managing the version number of...
seld/jsonlint                                  1.9.0        JSON Linter
seld/phar-utils                                1.2.0        PHAR file format utilities, for when PHP phars you up
sirbrillig/phpcs-variable-analysis             v2.11.3      A PHPCS sniff to detect problems with variables.
slevomat/coding-standard                       7.2.1        Slevomat Coding Standard for PHP_CodeSniffer complemen...
squizlabs/php_codesniffer                      3.7.1        PHP_CodeSniffer tokenizes PHP, JavaScript and CSS file...
stack/builder                                  v1.0.6       Builder for stack middleware based on HttpKernelInterf...
symfony-cmf/routing                            2.3.4        Extends the Symfony routing component for dynamic rout...
symfony/browser-kit                            v4.4.37      Simulates the behavior of a web browser, allowing you ...
symfony/console                                v4.4.43      Eases the creation of beautiful and testable command l...
symfony/css-selector                           v4.4.37      Converts CSS selectors to XPath expressions
symfony/debug                                  v4.4.41      Provides tools to ease debugging PHP code
symfony/dependency-injection                   v4.4.43      Allows you to standardize and centralize the way objec...
symfony/deprecation-contracts                  v2.5.2       A generic function and convention to trigger deprecati...
symfony/dom-crawler                            v4.4.42      Eases DOM navigation for HTML and XML documents
symfony/error-handler                          v4.4.41      Provides tools to manage errors and ease debugging PHP...
symfony/event-dispatcher                       v4.4.42      Provides tools that allow your application components ...
symfony/event-dispatcher-contracts             v1.1.13      Generic abstractions related to dispatching event
symfony/filesystem                             v4.4.42      Provides basic utilities for the filesystem
symfony/finder                                 v4.4.41      Finds files and directories via an intuitive fluent in...
symfony/http-client-contracts                  v2.5.2       Generic abstractions related to HTTP clients
symfony/http-foundation                        v4.4.43      Defines an object-oriented layer for the HTTP specific...
symfony/http-kernel                            v4.4.43      Provides a structured process for converting a Request...
symfony/inflector                              v5.4.3       Converts words between their singular and plural forms...
symfony/lock                                   v4.4.40      Creates and manages locks, a mechanism to provide excl...
symfony/mime                                   v5.4.10      Allows manipulating MIME messages
symfony/options-resolver                       v4.4.37      Provides an improved replacement for the array_replace...
symfony/phpunit-bridge                         v5.4.10      Provides utilities for PHPUnit, especially user deprec...
symfony/polyfill-ctype                         v1.25.0      Symfony polyfill for ctype functions
symfony/polyfill-iconv                         v1.25.0      Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                 v1.26.0      Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                      v1.25.0      Symfony polyfill for intl's idn_to_ascii and idn_to_ut...
symfony/polyfill-intl-normalizer               v1.25.0      Symfony polyfill for intl's Normalizer class and relat...
symfony/polyfill-mbstring                      v1.25.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                         v1.20.0      Symfony polyfill backporting some PHP 5.6+ features to...
symfony/polyfill-php72                         v1.26.0      Symfony polyfill backporting some PHP 7.2+ features to...
symfony/polyfill-php73                         v1.26.0      Symfony polyfill backporting some PHP 7.3+ features to...
symfony/polyfill-php80                         v1.25.0      Symfony polyfill backporting some PHP 8.0+ features to...
symfony/process                                v4.4.41      Executes commands in sub-processes
symfony/property-access                        v4.4.41      Provides functions to read and write from/to an object...
symfony/property-info                          v4.4.42      Extracts information about PHP class' properties using...
symfony/psr-http-message-bridge                v2.1.2       PSR HTTP message bridge
symfony/routing                                v4.4.41      Maps an HTTP request to a set of configuration variables
symfony/serializer                             v4.4.43      Handles serializing and deserializing data structures,...
symfony/service-contracts                      v2.5.2       Generic abstractions related to writing services
symfony/string                                 v5.4.10      Provides an object-oriented API to strings and deals w...
symfony/translation                            v4.4.41      Provides tools to internationalize your application
symfony/translation-contracts                  v2.5.2       Generic abstractions related to translation
symfony/validator                              v4.4.43      Provides tools to validate values
symfony/var-dumper                             v5.4.9       Provides mechanisms for walking through any arbitrary ...
symfony/yaml                                   v4.4.43      Loads and dumps YAML files
theseer/tokenizer                              1.2.1        A small library for converting tokenized PHP source co...
twig/twig                                      v2.15.1      Twig, the flexible, fast, and secure template language...
typo3/phar-stream-wrapper                      v3.1.7       Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                           1.2.2        Helper class to locate a Drupal installation from a gi...
webmozart/assert                               1.11.0       Assertions to validate method input/output with nice e...
webmozart/path-util                            2.3.0        A robust cross-platform utility for normalizing, compa...
webonyx/graphql-php                            v14.11.6     A PHP port of GraphQL reference implementation

**Comment by shishir-intelli** [comment]
Hi @simantstha 
We are not able to reproduce this issue, could you please share with us the Drupal error log (`/admin/reports/dblog`)

**Comment by simantstha** [comment]
![image](https://user-images.githubusercontent.com/30699044/181784841-e239ecda-dce0-4bf6-ab30-ff7696825862.png)

**Comment by shishir-intelli** [comment]
Hi @simantstha,
We are not able to reproduce this issue.
Could you check and make sure the `FieldableEntityDenormalizerImpostor` file exists in the `jsonapi_extra/src-impostor-normalizers/` module.

Have you applied the `jsonapi_extra` module patch (issue 569) ? or added the changes and files manually?

**Comment by simantstha** [comment]
![image](https://user-images.githubusercontent.com/30699044/182657760-12fdb569-78c4-4e7e-8c23-2194850f68c6.png)

**Comment by simantstha** [comment]
I did the patching again and 
![image](https://user-images.githubusercontent.com/30699044/182658988-70f4096e-9751-48ac-8cda-83cc10c1df4f.png)
![image](https://user-images.githubusercontent.com/30699044/182659323-b2a8c9f8-e5e4-4f48-8465-ef5f9df9440b.png)

**Comment by shishir-intelli** [comment]
Checkout  https://www.drupal.org/project/file_entity/issues/3174449
This issue is not related to Apigee so closing this issue for now, please feel free to re-open if you need any further help.
