### ISSUE TITLE
New Update of kickstart is getting error while installing.

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-devportal-kickstart-drupal#572]
![image](https://user-images.githubusercontent.com/30699044/182695884-0c1b7360-2cdc-47ef-94c6-c3def69f9fa7.png)

**Comment by shishir-intelli** [comment]
Hi @simantstha 

There seems to be some issue with `pathauto` latest modules released on 3rd Aug 2022 with Apigee Drupal Kickstart, 
You can downgrade both modules `pathauto` to v1.10 and `ctools` to v4.0.0 to make it work for now.

Pathauto - ( `composer require 'drupal/pathauto:1.10'` )
Ctools ( `composer require 'drupal/ctools:4.0.0'` )

We are working on this issue, soon we will update regarding the solution here.
