### ISSUE TITLE
Automated Swagger upload through CI/CD Pipelines

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#600]
I was told that this feature exists - Where an API spec is uploaded in GIT and it automatically pushes that API to API catalog. Basically, we need to call that API Doc service through CI/CD. Can you please mention the steps of how we can do that?

**Comment by phdhiren** [comment]
@pradeepgorle13 

This [documentation](https://www.drupal.org/docs/contributed-modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs) should be helpful for your need.

**Comment by giteshk** [comment]
Please feel free to re-open, if you have additional questions.
