### ISSUE TITLE
Admin unable to perform tasks

### ISSUE THREAD

**Issue by davidlara-abb** [apigee/apigee-devportal-kickstart-drupal#607]
## Description
Login as Admin, i cannot install a new module or update a module

## Steps to Reproduce
1. pull the image of ghcr.io/apigee/docker-apigee-drupal-kickstart:latest
2. once is the image is running login with the default admin credentials 
3. navigate to extend 
4. click on install new module or update

## Actual Behavior
the page show: You are not authorized to access this page.
in the console we can read: Failed to load resource: the server responded with a status of 403 (Forbidden)
be able to install a module, in my use case the google social api

## Expected Behavior
be able to extend the functionality installing, uninstalling and updated packages

## Screenshots
none

## Notes
i'm new in drupal
i already set the `setting allow_authorize_operations`  to TRUE in settings.php

## Version Info
the hash of the image i'm running is: c39c4199d4f9

**Comment by giteshk** [comment]
@davidlara-abb that docker image is a reference of how you can setup your own container.

In Drupal, You typically add your module as a dependency in the composer.json file. 

Here is what I would recommend you try:
1. Clone the repository https://github.com/apigee/docker-apigee-drupal-kickstart
2. Copy an initial version of [default](https://raw.githubusercontent.com/apigee/devportal-kickstart-project-composer/9.x/composer.json) kickstart composer file to the **code** directory.
3. Add you dependency of the module you want to the composer.json file using 'composer require drupal/<module_name>' 
4. Now when you build your own container it should have the new module. 
5. Use your own container image in the deployment.

If using docker-compose to test, comment out this [line](https://github.com/apigee/docker-apigee-drupal-kickstart/blob/main/docker-compose.yml#L18)  from docker-compose.yml to build your container locally.

Hope this helps.

**Comment by davidlara-abb** [comment]
Thanks for the response!
I'm still working on this. I have no experience on Drupal. 
I'm facing other issues following your response.
But I trust in your solution!
