### ISSUE TITLE
Drupal Dev Portal Installation Error

### ISSUE THREAD

**Issue by Gitanjali-Osttra** [apigee/apigee-devportal-kickstart-drupal#645]
## Description
I am following the https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart page to kickstart with Apigee-Drupal-Dev Portal but getting few issues.

## Steps to Reproduce
1. Go to https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart To install/setup Drupal Dev Portal.

## Actual Behavior
Getting DB error.
## Expected Behavior
A UI Screen to showcase the Drupal Dev Portal.

## Screenshots
![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/137279682/76b71544-e330-406b-b47b-df5a78ccf284)

## Version Info
I am using Drupal 10. and php-8.1.21

**Comment by divya-intelli** [comment]
Hi @Gitanjali-Osttra , 
Please post what error are you getting while installing Developer Portal Kickstart.
The screenshot that you have added says that you have already installed Drupal. If it is a new setup, please empty the database before installing Developer Portal Kickstart.

**Comment by Gitanjali-Osttra** [comment]
@divya-intelli  : How to empty database as i am not having idea on this. I am accessing the db via Visual Studio. It will be very helpful if you give a solution step by step.
![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/137279682/98120b0a-d4a5-4e86-8d23-0873ed806f4e)

**Comment by divya-intelli** [comment]
Hi @Gitanjali-Osttra ,
Please click on 'existing site' (shown in the screenshot you have attached). The page says that Drupal is already installed.
Please post error that you are getting.

**Comment by shishir-intelli** [comment]
@Gitanjali-Osttra ,
To empty or drop a specific Database, 
Right click on the db name -> Click on Truncate Database to empty the selected database.
and to completely drop the database
Right click on the db name -> Click on Drop to delete the database completely.
<img width="219" alt="Screenshot 2023-08-07 at 10 52 36 AM" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/75600200/557ec249-fbbf-4708-9eeb-10342bb3745e">


NOTE: Make sure you have already backed-up the database if required before exceuting the above commands.

**Comment by Gitanjali-Osttra** [comment]
@shishir-intelli 
I am using SQLite as database for Drupal 10.
the database file look like below.
![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/137279682/668e2f7b-4515-4b38-9010-ccdb60891d62)
I have deleted the database file and did the setup again but still getting same error.

**Comment by divya-intelli** [comment]
@Gitanjali-Osttra Please post the error that you are getting on install.

**Comment by Gitanjali-Osttra** [comment]
@divya-intelli It is mentioned in the Error thread/Problem statement.

**Comment by shishir-intelli** [comment]
@Gitanjali-Osttra ,
Try this command,
`drush sql-drop -y` 
or 
`vendor/bin/drush sql-drop -y` in your project directory. 
This will drop the DB and then start you Drupal installation again by running `/core/install.php`.

Hope this will help you.

**Comment by divya-intelli** [comment]
Closing this issue for now. Please free to reopen if the issue still exist.
