### ISSUE TITLE
possible javascript dropdown-toggle issue

### ISSUE THREAD

**Issue by hollyw2025** [apigee/apigee-devportal-kickstart-drupal#648]
## Description
hi, we have upgraded to kickstart 2.1.5 within our drupal 9 project. Our goal is to upgrade to drupal 10 but we would like to deploy kickstart 2.1.5 within drupal core 9 at this moment. 

We noticed this javascript problem and would like to report. 

1. Our current user interface theme is a custom theme and it is based on kickstart. We have a dropdown list stopped working after the kickstart upgrade.  Here is the drop down menu html code: 

<li class="navbar-text nav-item dropdown">
    <span class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Apps</span>
        <div class="dropdown-menu">
        <a href="/user/apps" class="dropdown-item" data-drupal-link-system-path="user/apps">My Apps</a>
        <a href="/myteams_apps" class="dropdown-item" data-drupal-link-system-path="myteams_apps">Team Apps</a>
  </div>
</li>

2. I switched the default theme from custom theme to Apigee Kickstart 9.5.10, same result, dropdown doesn't work
with Apigee Kickstart 9.5.10 as the default theme, the html code is the same as our local custom theme. 
<li class="navbar-text nav-item dropdown">
                      <span class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Apps</span>
                          <div class="dropdown-menu">
              <a href="/user/apps" class="dropdown-item" data-drupal-link-system-path="user/apps">My Apps</a>
              <a href="/myteams_apps" class="dropdown-item" data-drupal-link-system-path="myteams_apps">Team Apps</a>
  </div>
                              </li>
                              
                              
3.    with Apigee Kickstart 9.5.10 as the default theme, I found out that the Apps dropdown works with mouse over  before any user login, there are a series of div on top of this li class, not sure if any of the div javascript will work on this piece

<li class="nav-item dropdown">
                        <a href="/unauthorized" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" data-drupal-link-system-path="node/6">Apps</a>
                            <div class="dropdown-menu">
                <a href="/unauthorized" class="dropdown-item" data-drupal-link-system-path="node/6">My Apps</a>
                <a href="/unauthorizedta" class="dropdown-item" data-drupal-link-system-path="node/26">Team Apps</a>
    </div>
 </li>
                         
                              
4. I switched the default theme to Olivero 9.5.10, dropdown worked.  Seems like Olivero use different class to handle dropdown 
<li class="primary-nav__menu-item primary-nav__menu-item--nolink primary-nav__menu-item--level-1 primary-nav__menu-item--has-children" 
data-drupal-selector="primary-nav-menu-item-has-children">
                              <span class="primary-nav__menu-link primary-nav__menu-link--nolink primary-nav__menu-link--level-1 primary-nav__menu-link--has-children" 
  data-drupal-selector="primary-nav-menu-link-has-children">Apps</span>
  
5. I test over Chrome and firefox browser, same result. I compared with another site which has kickstart 2.1.0, the problem is the mouse click. with 2.1.0, mouse click over the Apps, the dropdown items will show up. while with 2.1.5, nothing displayed with mouse click.  

 Hope to get some advice from you at the same time.  Thank you for your help.

**Comment by divya-intelli** [comment]
Hi @HollyWangUCLA ,

This seems to be caching issue.
Can you flush the cache of Drupal project and check. 
If it still doesn't work, 
1. Go to `/admin/config/development/performance` and check if `Bandwidth optimization` is enabled. 
2. If enabled , try once disabling `Bandwidth optimization (both the checkbox)`.
3. Flush the cache.
4. Enable again `Bandwidth optimization` in `/admin/config/development/performance`

**Comment by hollyw2025** [comment]
I I switched the default theme from custom theme to Apigee Kickstart 9.5.10 and did above steps, flush the cache a couple of times before and after enable and disable Bandwidth optimization, still not working. I attached the screenshot

![Screenshot 2023-08-24 at 9 00 38 AM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/ff89f08e-906f-47a5-b513-338873a9cdd4)

**Comment by hollyw2025** [comment]
Divya
I updated the original post, added item 3. Hope you can view the html code there.

**Comment by divya-intelli** [comment]
> Divya I updated the original post, added item 3. Hope you can view the html code there.

Not able to view the html code.

> I I switched the default theme from custom theme to Apigee Kickstart 9.5.10 and did above steps, flush the cache a couple of times before and after enable and disable Bandwidth optimization, still not working. I attached the screenshot
> 
> ![Screenshot 2023-08-24 at 9 00 38 AM](https://user-images.githubusercontent.com/69690136/263034210-ff89f08e-906f-47a5-b513-338873a9cdd4.png)

@HollyWangUCLA ,

Looking at the screenshot attached of Kickstart Devportal, it looks like there is some custom code / css that is applied. Check the screen short of actual Kickstart Devportal.

![Screenshot 2023-08-25 at 2 38 12 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/75604843/0236c5a0-a011-4ef0-bc7a-b33794d6a8b2)

Can you try disabling any custom module or css.
Also please provide the output of `composer show`. There could be some other module that is affecting the css.

**Comment by hollyw2025** [comment]
Hi, Divya

I am checking to see where to disable local modules, at this moment, the default theme is Apigee Kickstart 9.5.10, and administration theme is Claro. Composer show list is as following



hollywang@ITS-HWANG release32_d10 % composer show
apigee/apigee-client-php                                  2.1.0           Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart                         2.1.5           A fast demo and starting point for Apigee Developer Po...
asm89/stack-cors                                          1.3.0           Cross-origin resource sharing library and stack middle...
bower-asset/swagger-ui                                    v3.52.5        
chi-teck/drupal-code-generator                            1.33.1          Drupal code generator
clue/stream-filter                                        v1.6.0          A simple and modern approach to stream filtering in PHP
commerceguys/addressing                                   v1.4.2          Addressing library powered by CLDR and Google's addres...
commerceguys/intl                                         v2.0.4          Internationalization library powered by CLDR data.
composer/installers                                       v1.12.0         A multi-framework Composer library installer
composer/semver                                           3.3.2           Semver library that offers utilities, version constrai...
consolidation/annotated-command                           4.9.1           Initialize Symfony Console commands from annotated com...
consolidation/config                                      1.2.1           Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data                  1.0.0           This project uses dflydev/dot-access-data to provide s...
consolidation/log                                         2.1.1           Improved Psr-3 / Psr\Log logger based on Symfony Conso...
consolidation/output-formatters                           4.3.2           Format text by applying transformations provided by pl...
consolidation/robo                                        3.0.12          Modern task runner
consolidation/self-update                                 2.2.0           Provides a self:update command for Symfony Console app...
consolidation/site-alias                                  3.1.7           Manage alias records for local and remote sites.
consolidation/site-process                                4.2.1           A thin wrapper around the Symfony Process Component th...
cweagans/composer-patches                                 1.7.3           Provides a way to patch Composer packages.
dflydev/dot-access-data                                   v1.1.0          Given a deep data structure, access data by dot notation.
doctrine/annotations                                      1.13.3          Docblock Annotations Parser
doctrine/collections                                      2.1.3           PHP Doctrine Collections library that adds additional ...
doctrine/deprecations                                     v1.1.1          A small layer on top of trigger_error(E_USER_DEPRECATE...
doctrine/lexer                                            1.2.3           PHP Doctrine Lexer parser library that can be used in ...
doctrine/reflection                                       1.2.4           The Doctrine Reflection project is a simple library us...
drupal/address                                            1.12.0          Provides functionality for storing, validating and dis...
drupal/admin_toolbar                                      3.4.1           Provides a drop-down menu interface to the core Drupal...
drupal/adminimal_admin_toolbar                            1.11.0          Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                                 3.0.4           Apigee API Catalog for Drupal
drupal/apigee_edge                                        2.1.1           Apigee Edge for Drupal.
drupal/autologout                                         1.4.0           Adds automated timed logout.
drupal/better_exposed_filters                             6.0.3           Replaces the Views default single- or multi-select box...
drupal/color                                              1.0.3           Allows users to change the color scheme of compatible ...
drupal/commerce                                           2.36.0          Drupal Commerce is a flexible eCommerce solution.
drupal/components                                         3.0.0-beta3     Registers folders of components defined by your theme ...
drupal/core                                               9.5.10          Drupal is an open source content management platform p...
drupal/core-composer-scaffold                             9.5.10          A flexible Composer project scaffold builder.
drupal/core-project-message                               9.5.10          Adds a message after Composer installation.
drupal/core-recommended                                   9.5.10          Core and its dependencies with known-compatible minor ...
drupal/css_editor                                         2.0.2           Customize your CSS directly from the browser.
drupal/ctools                                             3.14.0          Provides a number of utility and helper APIs for Drupa...
drupal/default_content                                    2.0.0-alpha2    Imports default content when a module is enabled
drupal/email_registration                                 1.2.0           Allows users to register with an email address as thei...
drupal/entity                                             1.4.0           Provides expanded entity APIs, which will be moved to ...
drupal/entity_browser                                     2.9.0           Entity browsing and selecting component.
drupal/entity_reference_revisions                         1.10.0          Entity Reference Revisions
drupal/externalauth                                       2.0.3           Helper module to authenticate users using an external ...
drupal/file_link                                          2.1.0           Extends the core Link module by storing metadata about...
drupal/fontawesome                                        2.26.0          The web's most popular icon set and toolkit.
drupal/hal                                                1.0.0           Serializes entities using Hypertext Application Language.
drupal/inline_entity_form                                 1.0.0-rc15      Provides a widget for inline management (creation, mod...
drupal/jquery_ui                                          1.6.0           Provides jQuery UI library.
drupal/jquery_ui_datepicker                               2.0.0           Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                                   2.0.0           Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch                              1.1.0           Provides jQuery UI Touch Punch library.
drupal/key                                                1.17.0          Provides the ability to manage site-wide keys
drupal/maxlength                                          2.1.2           MaxLength allows a soft or hard character limit to be ...
drupal/menu_per_role                                      1.5.0           Allows restricting access to menu items per role.
drupal/menu_trail_by_path                                 2.0.0           Expand menus and set active-trail according to the cur...
drupal/pantheon_advanced_page_cache                       2.1.2           Advanced page cache capabilities for Pantheon.
drupal/paragraphs                                         1.15.0          Enables the creation of Paragraphs entities.
drupal/pathauto                                           1.11.0          Provides a mechanism for modules to automatically gene...
drupal/profile                                            1.7.0           Provides configurable user profiles.
drupal/quickedit                                          1.0.3           In-place content editing (contrib).
drupal/radix                                              5.0.11          Responsive Bootstrap 5 base theme for Drupal.
drupal/rdf                                                2.1.1           Enriches your content with metadata to let other appli...
drupal/redirect_after_logout                              1.3.0           User redirect, after logout.
drupal/reroute_email                                      2.2.0           Reroutes emails send from the site to a predefined ema...
drupal/seckit                                             2.0.1           SecKit provides Drupal with various security-hardening...
drupal/simplesamlphp_auth                                 dev-4.x c97611b Allows users to authenticate to a remote SAML identity...
drupal/simplesamlphp_custom_attributes                    2.0.0           Maps custom SAML SSO attributes to user fields.
drupal/smtp                                               1.2.0           Allow for site emails to be sent through an SMTP serve...
drupal/state_machine                                      1.8.0           Provides code-driven workflow functionality.
drupal/swagger_ui_formatter                               3.5.0           Provides a Swagger UI field formatter for File and Lin...
drupal/token                                              1.12.0          Provides a user interface for the Token API, some miss...
drupal/upgrade_status                                     4.0.0           Review Drupal major upgrade readiness of the environme...
drupal/views_bulk_edit                                    2.9.0           Allows bulk edition of entity field values.
drupal/views_bulk_operations                              4.2.5           Adds an ability to perform bulk operations on selected...
drush/drush                                               10.6.2          Drush is a command line shell and scripting interface ...
easyrdf/easyrdf                                           1.1.1           EasyRdf is a PHP library designed to make it easy to c...
egulias/email-validator                                   3.2.6           A library for validating emails against several RFCs
enlightn/security-checker                                 v1.10.0         A PHP dependency vulnerabilities scanner based on the ...
fightbulc/moment                                          1.34            Parse, validate, manipulate, and display dates in PHP ...
firebase/php-jwt                                          v6.8.1          A simple library to encode and decode JSON Web Tokens ...
gettext/gettext                                           v4.8.11         PHP gettext manager
gettext/languages                                         2.10.0          gettext languages with plural rules
grasmash/expander                                         1.0.0           Expands internal property references in PHP arrays file.
grasmash/yaml-expander                                    1.4.0           Expands internal property references in a yaml file.
guzzlehttp/guzzle                                         6.5.8           Guzzle is a PHP HTTP client library
guzzlehttp/promises                                       1.5.3           Guzzle promises library
guzzlehttp/psr7                                           1.9.1           PSR-7 message implementation that also provides common...
laminas/laminas-escaper                                   2.12.0          Securely and safely escape HTML, HTML attributes, Java...
laminas/laminas-feed                                      2.21.0          provides functionality for creating and consuming RSS ...
laminas/laminas-servicemanager                            3.21.0          Factory-Driven Dependency Injection Container
laminas/laminas-stdlib                                    3.17.0          SPL extensions, array utilities, error handlers, and more
laminas/laminas-text                                      2.10.0          Create FIGlets and text-based tables
league/container                                          3.4.1           A fast and intuitive dependency injection container.
league/period                                             4.12.0          Time range API for PHP
longwave/laminas-diactoros                                2.14.2          PSR HTTP Message implementations
masterminds/html5                                         2.7.6           An HTML5 parser and serializer.
mathieuviossat/arraytotexttable                           v1.0.9          Display arrays in terminal
mglaman/phpstan-drupal                                    1.1.37          Drupal extension and rules for PHPStan
nikic/php-parser                                          v4.17.1         A PHP parser written in PHP
oomphinc/composer-installers-extender                     2.0.1           Extend the composer/installers plugin to accept any ar...
pantheon-systems/drupal-integrations                      9.0.5           Add this project to any Drupal distribution based on d...
pantheon-upstreams/upstream-configuration                 dev-release3.2 
pear/archive_tar                                          1.4.14          Tar file management class with compression support (gz...
pear/console_getopt                                       v1.4.3          More info available on: http://pear.php.net/package/Co...
pear/pear-core-minimal                                    v1.10.13        Minimal set of PEAR core files to be used as composer ...
pear/pear_exception                                       v1.0.2          The PEAR Exception base class.
php-http/client-common                                    2.7.0           Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                                        1.19.1          Finds and installs PSR-7, PSR-17, PSR-18 and HTTPlug i...
php-http/guzzle6-adapter                                  v2.0.2          Guzzle 6 HTTP Adapter
php-http/httplug                                          2.4.0           HTTPlug, the HTTP client abstraction for PHP
php-http/message                                          1.14.0          HTTP Message related tools
php-http/message-factory                                  1.1.0           Factory interfaces for PSR-7 HTTP Message
php-http/promise                                          1.1.0           Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common                           2.2.0           Common reflection classes used by phpdocumentor to ref...
phpdocumentor/reflection-docblock                         5.3.0           With this component, a library can provide support for...
phpdocumentor/type-resolver                               1.7.3           A PSR-5 based resolver of Class names, Types and Struc...
phpfastcache/riak-client                                  3.4.3           Riak client for PHP (Fork of the official basho/riak d...
phpmailer/phpmailer                                       v6.8.0          PHPMailer is a full-featured email creation and transf...
phpstan/phpdoc-parser                                     1.23.1          PHPDoc parser with support for nullable, intersection ...
phpstan/phpstan                                           1.10.29         PHPStan - PHP Static Analysis Tool
phpstan/phpstan-deprecation-rules                         1.1.4           PHPStan rules for detecting usage of deprecated classe...
politsin/jquery-ui-touch-punch                            1.0             Extension to jQuery UI for mobile touch event support.
psr/cache                                                 1.0.1           Common interface for caching libraries
psr/container                                             1.1.2           Common Container Interface (PHP FIG PSR-11)
psr/http-client                                           1.0.2           Common interface for HTTP clients
psr/http-factory                                          1.0.2           Common interfaces for PSR-7 HTTP message factories
psr/http-message                                          1.0.1           Common interface for HTTP messages
psr/log                                                   1.1.4           Common interface for logging libraries
psy/psysh                                                 v0.10.12        An interactive shell for modern PHP.
ralouphie/getallheaders                                   3.0.3           A polyfill for getallheaders.
robrichards/xmlseclibs                                    3.1.1           A PHP library for XML Security
simplesamlphp/assert                                      v0.0.13         A wrapper around webmozart/assert to make it useful be...
simplesamlphp/composer-module-installer                   v1.2.0          A Composer plugin that allows installing SimpleSAMLphp...
simplesamlphp/saml2                                       v4.6.10         SAML2 PHP library from SimpleSAMLphp
simplesamlphp/simplesamlphp                               1.19.8          A PHP implementation of a SAML 2.0 service provider an...
simplesamlphp/simplesamlphp-module-adfs                   v1.0.9          A module that implements the WS-federation IDP
simplesamlphp/simplesamlphp-module-authcrypt              v0.9.4          This module provides authentication against password h...
simplesamlphp/simplesamlphp-module-authfacebook           v0.9.3          A module that is able to authenticate against Facebook
simplesamlphp/simplesamlphp-module-authorize              v0.9.4          This module provides a user authorization filter based...
simplesamlphp/simplesamlphp-module-authtwitter            v0.9.3          A module that is able to perform authentication agains...
simplesamlphp/simplesamlphp-module-authwindowslive        v0.9.1          A module that is able to perform authentication agains...
simplesamlphp/simplesamlphp-module-authx509               v0.9.9          A module that is able to authenticate users based on X...
simplesamlphp/simplesamlphp-module-authyubikey            v0.9.3          A module that is able to authenticate against YubiKey
simplesamlphp/simplesamlphp-module-cas                    v0.9.1          A module that provides CAS authentication
simplesamlphp/simplesamlphp-module-cdc                    v0.9.2          A SimpleSAMLphp module that allows integration with CDC
simplesamlphp/simplesamlphp-module-consent                v0.9.8          A module that will ask for user consent before releasi...
simplesamlphp/simplesamlphp-module-consentadmin           v0.9.2          A module that allows users to manage their consent
simplesamlphp/simplesamlphp-module-discopower             v0.10.1         Fancy tabbed discovery service with filtering capabili...
simplesamlphp/simplesamlphp-module-exampleattributeserver v1.0.0          An example for SAML attributes queries
simplesamlphp/simplesamlphp-module-expirycheck            v0.9.4          The expirycheck module validates user's expiry date
simplesamlphp/simplesamlphp-module-ldap                   v0.9.17         A module that provides authentication against LDAP stores
simplesamlphp/simplesamlphp-module-memcachemonitor        v0.9.3          A module that is able display usage statistics of a me...
simplesamlphp/simplesamlphp-module-memcookie              v1.2.2          A SimpleSAMLphp module that allows integration with Au...
simplesamlphp/simplesamlphp-module-metarefresh            v0.10.0         The metarefresh module will download and parse metadat...
simplesamlphp/simplesamlphp-module-negotiate              v0.9.12         The Negotiate module implements Microsofts Kerberos SP...
simplesamlphp/simplesamlphp-module-oauth                  v0.9.3          A SimpleSAMLphp module that allows integration with OA...
simplesamlphp/simplesamlphp-module-preprodwarning         v0.9.3          Display a warning when using a pre-production environment
simplesamlphp/simplesamlphp-module-radius                 v0.9.4          A module that is able perform authentication against a...
simplesamlphp/simplesamlphp-module-riak                   v0.9.1          A module that is able to store key/value pairs in a Ri...
simplesamlphp/simplesamlphp-module-sanitycheck            v0.9.1          Perform sanity checks on configuration
simplesamlphp/simplesamlphp-module-smartattributes        v0.9.2          The SmartAttributes module provides additional authent...
simplesamlphp/simplesamlphp-module-sqlauth                v0.9.4          This is a authentication module for authenticating a u...
simplesamlphp/simplesamlphp-module-statistics             v0.9.6          The SimpleSAMLphp statistics module
simplesamlphp/twig-configurable-i18n                      v2.3.5          This is an extension on top of Twig's i18n extension, ...
stack/builder                                             v1.0.6          Builder for stack middleware based on HttpKernelInterf...
symfony-cmf/routing                                       2.3.4           Extends the Symfony routing component for dynamic rout...
symfony/cache                                             v5.4.25         Provides extended PSR-6, PSR-16 (and tags) implementat...
symfony/cache-contracts                                   v2.5.2          Generic abstractions related to caching
symfony/config                                            v4.4.44         Helps you find, load, combine, autofill and validate c...
symfony/console                                           v4.4.49         Eases the creation of beautiful and testable command l...
symfony/debug                                             v4.4.44         Provides tools to ease debugging PHP code
symfony/dependency-injection                              v4.4.49         Allows you to standardize and centralize the way objec...
symfony/deprecation-contracts                             v2.5.2          A generic function and convention to trigger deprecati...
symfony/error-handler                                     v4.4.44         Provides tools to manage errors and ease debugging PHP...
symfony/event-dispatcher                                  v4.4.44         Provides tools that allow your application components ...
symfony/event-dispatcher-contracts                        v1.1.13         Generic abstractions related to dispatching event
symfony/filesystem                                        v4.4.42         Provides basic utilities for the filesystem
symfony/finder                                            v5.4.27         Finds files and directories via an intuitive fluent in...
symfony/framework-bundle                                  v4.4.49         Provides a tight integration between Symfony component...
symfony/http-client-contracts                             v2.5.2          Generic abstractions related to HTTP clients
symfony/http-foundation                                   v4.4.49         Defines an object-oriented layer for the HTTP specific...
symfony/http-kernel                                       v4.4.50         Provides a structured process for converting a Request...
symfony/inflector                                         v5.4.21         Converts words between their singular and plural forms...
symfony/mime                                              v5.4.13         Allows manipulating MIME messages
symfony/options-resolver                                  v4.4.44         Provides an improved replacement for the array_replace...
symfony/polyfill-ctype                                    v1.27.0         Symfony polyfill for ctype functions
symfony/polyfill-iconv                                    v1.27.0         Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                            v1.27.0         Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                                 v1.27.0         Symfony polyfill for intl's idn_to_ascii and idn_to_ut...
symfony/polyfill-intl-normalizer                          v1.27.0         Symfony polyfill for intl's Normalizer class and relat...
symfony/polyfill-mbstring                                 v1.27.0         Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                                    v1.27.0         Symfony polyfill backporting some PHP 7.2+ features to...
symfony/polyfill-php73                                    v1.27.0         Symfony polyfill backporting some PHP 7.3+ features to...
symfony/polyfill-php80                                    v1.27.0         Symfony polyfill backporting some PHP 8.0+ features to...
symfony/polyfill-php81                                    v1.27.0         Symfony polyfill backporting some PHP 8.1+ features to...
symfony/process                                           v4.4.44         Executes commands in sub-processes
symfony/property-access                                   v4.4.44         Provides functions to read and write from/to an object...
symfony/property-info                                     v4.4.49         Extracts information about PHP class' properties using...
symfony/psr-http-message-bridge                           v2.1.4          PSR HTTP message bridge
symfony/routing                                           v4.4.44         Maps an HTTP request to a set of configuration variables
symfony/serializer                                        v4.4.47         Handles serializing and deserializing data structures,...
symfony/service-contracts                                 v2.5.2          Generic abstractions related to writing services
symfony/string                                            v6.3.2          Provides an object-oriented API to strings and deals w...
symfony/translation                                       v4.4.47         Provides tools to internationalize your application
symfony/translation-contracts                             v2.5.2          Generic abstractions related to translation
symfony/validator                                         v4.4.48         Provides tools to validate values
symfony/var-dumper                                        v5.4.26         Provides mechanisms for walking through any arbitrary ...
symfony/var-exporter                                      v5.4.26         Allows exporting any serializable PHP data structure t...
symfony/yaml                                              v4.4.45         Loads and dumps YAML files
twig/extensions                                           v1.5.4          Common additional features for Twig that do not direct...
twig/twig                                                 v2.15.5         Twig, the flexible, fast, and secure template language...
typo3/phar-stream-wrapper                                 v3.1.7          Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                                      1.2.2           Helper class to locate a Drupal installation from a gi...
webmozart/assert                                          1.11.0          Assertions to validate method input/output with nice e...
webmozart/path-util                                       2.3.0           A robust cross-platform utility for normalizing, compa...
webonyx/graphql-php                                       v14.11.10       A PHP port of GraphQL reference implementation
whitehat101/apr1-md5                                      v1.0.0          Apache's APR1-MD5 algorithm in pure PHP
zaporylie/composer-drupal-optimizations                   1.2.0           Composer plugin to improve composer performance for Dr...
hollywang@ITS-HWANG release32_d10 %

**Comment by divya-intelli** [comment]
@HollyWangUCLA , please disable custom module / css and check.

**Comment by hollyw2025** [comment]
Hi, Divya, 
I totally uninstalled the our local custom theme, and the problem still can't be fixed. 
Here is the steps for you to test, and hope you can replicate it on your side

1. in  /admin/appearance , set  Apigee Kickstart 9.5.10 (default theme), I uninstall our own theme here

2.  go to <yourside>/admin/structure/menu/manage/main , add a link, 
![Screenshot 2023-08-29 at 5 05 17 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/060efb61-74ce-4e52-8d3e-ed801bbe6fb9)

3. add a child links under above link
![Screenshot 2023-08-29 at 5 06 15 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/261053b7-7440-4c85-b83b-5c7c3d21a7cc)

4. after save the main menu, the pulldown menu still not showing up
![Screenshot 2023-08-29 at 5 08 01 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/7714517b-eae6-4e26-86ae-6fe2c1efc9e4)


Do you mind to test from your side to see if you can see the pull down menu with mouse over action? 

Thank you

Holly

**Comment by divya-intelli** [comment]
@HollyWangUCLA ,

Thank you for attaching the steps to replicate. Was able to replicate.
Compared with earlier version of Apigee Kickstart, mouse click doesn't work in 2.1.5
It seems to because of class change from Radix theme. 
Will create a PR as soon as a fix is ready.

**Comment by hollyw2025** [comment]
Divya
Thank you so much! Looking forward for PR

Have a great day

Holly

**Comment by divya-intelli** [comment]
Hi @HollyWangUCLA , can apply the PR #651 and check if it fixes the issue.

**Comment by HollyWangUCLA** [comment]
Divya
please advice how can I apply PR #651, should I manually modify local css with following change to test locally? Or should I do composer update kickstart one more time?
"Data attribute data-toggle is replaced with data-bs-toggle"

**Comment by hollyw2025** [comment]
Hi, Divya,
Thank you for your hardwork, this is what I did
1. copy two files from github to my local 
themes/custom/apigee_kickstart/assets/css/apigee-kickstart.style.css
themes/custom/apigee_kickstart/assets/js/apigee-kickstart.script.js 

2. in my local, I set Apigee Kickstart 9.5.10 as default theme, 
I flashed site caches and also rebuild all local containers. 

3. result
seems like unauthorized user interface has been fixed (interface for public user)

![Screenshot 2023-09-05 at 2 30 48 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/807263e4-4d6f-4594-8bb9-8c07ad0f82e0)

After administrator log in, I can see partial pulldown menu, but seems like it is behind the main window

![Screenshot 2023-09-05 at 2 40 02 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/046ae9e9-0683-4199-aee2-b6804ab9f765)

And also, you can see that Apps not line up with other text , which is also something that I want to report. We don't have this line up issue before this deployment

Thank you again

Holly

**Comment by divya-intelli** [comment]
@HollyWangUCLA ,

It seems that the css is cached for logged in user.
Can you try once again clearing the cache.
1. Go to `/admin/config/development/performance` and check if `Bandwidth optimization` is enabled.
2. If enabled , try once disabling `Bandwidth optimization` (both the checkbox).
3. Flush the cache.
4. Enable again `Bandwidth optimization in /admin/config/development/performance`

**Comment by hollyw2025** [comment]
Divya

1. in my site, Bandwidth optimization (both the checkbox) are not checked. Even they are not checked, I still tried enable and disable and flush cache, I don't see any change with interface 

2. I created two top menu, one with <nolink>, one linked to a valid page, both has two children menus under them 
![Screenshot 2023-09-06 at 12 15 38 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/758a284c-1271-4a95-a4c4-05819a225eb1)

![Screenshot 2023-09-06 at 12 19 38 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/545863fa-7366-401b-a743-feaf869e98f7)

3. In the public index page, both top menu can display the children menu, while you can see the one with <nolink> doesn't line up with another one 
![Screenshot 2023-09-06 at 12 23 04 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/ed9bae98-4bdc-404b-99ad-8d4d3dd98b9c)

4. in the admin interface, popup seems show up but it is behind the bottom window block. you can see a little bit of the white box of the popup 
You can also see that the top menu with <nolink> doesn't line up with the other one
![Screenshot 2023-09-06 at 12 25 22 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/e805124b-83a4-4544-80c0-74befdf8e7cb)

5. in admin interface, popup show up partially on top of the team bar, so seems like the blue bar of team page handles popup while by display it in front.  

![Screenshot 2023-09-06 at 12 27 12 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/4a36c277-972b-4461-a0b5-b78be2106c21)

Please help. 

Thank you

Holly

**Comment by divya-intelli** [comment]
@HollyWangUCLA , 

I have done some changes to PR https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/651. Please re-apply the PR and check if it resolves the issue. Clear the cache after applying the PR and check.

**Comment by hollyw2025** [comment]
Divya
Here is the recent test result, with PR 651.

1. menu with < nolink > and with children popup works fine now. 
2. line up: menu with < nolink > line up with other menus 
Thank you for fixing these problems. 

Here are the problems I noticed: 
1. menu with a solid link and with children pop up still have problem. I attached the screenshot 
"My Teams" is the menu with a child and link to a real page
![Screenshot 2023-09-07 at 2 53 38 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/a3f8b8b6-dae6-4e74-8a5d-add181d0e660)

The child for "My Teams" doesn't show up in the index page under admin login 
![Screenshot 2023-09-07 at 2 55 01 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/9ae1e149-851a-404a-be16-58420e914748)

The child for "My Teams" showup on top of the blue bar after click on any valid page
![Screenshot 2023-09-07 at 2 56 14 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/24504232-043a-46d9-aaa2-aed40b55a45f)

For public user, child of "My Teams" doesn't showup at all: in index page or after click on any solid link
![Screenshot 2023-09-07 at 2 57 49 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/780c64f9-d7b1-4d4a-801a-b01bf9dff3cc)

at the same time, the children for a < nolink > menu works fine. 

Thank you again

Holly

**Comment by divya-intelli** [comment]
@HollyWangUCLA ,

Seems to be the initial issue was resolved by the PR https://github.com/apigee/apigee-devportal-kickstart-drupal/pull/651.
For other issues please create a separate issue for better tracking.

**Comment by hollyw2025** [comment]
ok will do

**Comment by hollyw2025** [comment]
Divya

I noticed that the current js and css change which contains bug fixing haven't be included in the 2.1.5 deployment. I wonder when will they be included, as I currently manually copy these two files into my project to avoid interface problem. Our current platform, pantheon, doesn't allow me to deploy the folders which can be created during composer update step. 

Thank you for taking care of this issue. 

Holly

**Comment by divya-intelli** [comment]
Hi @HollyWangUCLA , 

We will be releasing a new version next week which will have this fix. 
Thank you for your patience.
