### ISSUE TITLE
CSS issue: admin pulldown menu hide behind bar

### ISSUE THREAD

**Issue by hollyw2025** [apigee/apigee-devportal-kickstart-drupal#652]
## Description
Hi, we use a custom theme which is based on kickstart. After upgrade kickstart to the recent deployment (2.1.5), we noticed admin pull down menu when we set our local theme as default theme. We don't have such problem before upgrade kickstart to the recent deployment. 

here is the screenshot 
![Screenshot 2023-09-08 at 2 16 45 PM](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/69690136/752d2d6f-0cda-4a99-83ff-35dcaedc3685)

will you please add following Style zIndex Property to the css class for admin pulldown menu? I can't find it in the kickstart css file 
< li class="menu-item menu-item--expanded"
z-index: 1000

Thank you so much

Holly

**Comment by divya-intelli** [comment]
@HollyWangUCLA 

This is not a kickstart issue as the admin dropdown works fine in Kickstart, the css changes needs to be added in custom theme css file.
