### ISSUE TITLE
Unable to see/allow JSON API's configurations even after enabling JSON API extensions

### ISSUE THREAD

**Issue by aravind16108** [apigee/apigee-devportal-kickstart-drupal#653]
## Description
 I have installed the latest version of Apigee Developer Portal Kickstart in our Organisations EC2 instance using the link [get-started-with-kicks](https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/get-started-with-kickstart).
     I have also enabled the JSON API extensions as per the documentation in [Expose REST APIs to interact with API Docs](https://www.drupal.org/docs/contributed-modules/apigee-api-catalog/expose-rest-apis-to-interact-with-api-docs).
      However, I am unable to see the options to enable rest api's under the webservices configuration menu. Attached are the screenshots for reference.

## Steps to Reproduce
1. Create an  EC2 instance
2. Install PHP, composer, Apache HTTPD & Apigee Developer Portal Kickstart
3. Run HTTPD -> Access the portal and perform the initial configuration of connecting Amazon RDS and also create an Admin User.
4. log in as an admin user -> Enable the JSON API extras and Basic Auth Modules -> Go to the web services configuration page
5. Unable to find the options to enable REST/JSON API's.

## Actual Behavior
Unable to find the option to enable rest APIs under web services configuration.

![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/2b0572bb-8139-4388-a14b-d6c071d59b45)

## Expected Behavior
As an admin, I should be able to navigate to Configuration > Web services > JSON:API. Enable Accept all JSON: API create, read, update, and delete operations, as per the screenshot below.

![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/4a58f165-9a97-4709-903a-09f87041b3fb) 

## Screenshots
Screenshot of modules that are enabled for JSON APIs

![image](https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/abd11b4b-8eed-4c31-b23e-ce9a06021ec6)

## Version Info
The output of the command `composer show`

[composer-version.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/12733815/composer-version.txt)

**Comment by shishir-intelli** [comment]
@aravind16108 ,
I followed the above steps with same version, however I was not able to reproduce this issue, I can see the JSONAPI under web services tab.
<img width="1015" alt="Screenshot 2023-09-27 at 11 30 46 AM" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/75600200/5504606a-1869-4e95-a982-1ec5982e82ac">

Could you please re-install the Drupal instance if it is a fresh installation or rebuild the cache and try again.

Also please check if both this below patch's are applied durning installation (_you can find this script inside Drupal's root composer.json file_)
```
"drupal/jsonapi_extras":{
          "JSON APIS EXTRAS BULK PATCH": "https://www.drupal.org/files/issues/2020-02-20/add-enable-disable-all-buttons--2896799--10.patch",
          "Jsonapi_extra installation issue due to 3042467-50.patch": "https://github.com/apigee/apigee-devportal-kickstart-drupal/files/9189452/patch.569-1.txt"
      }
```

**Comment by aravind16108** [comment]
Hi @shishir-intelli ,
    Thanks for the quick response. I could see the entry in the composer.json file.
     However, when I did the reinstallation of drupal-instance, I found the below errors. 

<img width="1432" alt="image" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/ca803e55-ec69-48e4-9f30-c2d296ca87bb">

     So, I enabled verbose mode and retried another installation and got the below log with 304 & 404 errors.
        
404
<img width="1432" alt="image" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/8e683bdb-d1ec-45db-9491-88806b6edff5">

304
<img width="1432" alt="image" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/117416603/46c14a32-217d-41a4-9015-1e4ec22a29bc">


Looks like the 404 and 304 errors are the culprit here. Can you advise how to mitigate these issues.

I have attached the drupal installation log below for your reference.

[drupal-installation-log.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/12735413/drupal-installation-log.txt)

**Comment by shishir-intelli** [comment]
@aravind16108 ,
Your verbose mode log is saying that `sh: patch: command not found`, which means `patch` command not found. 

Install patch and then re-install the Drupal instance.
(If you are using Windows, it won't be installed unless you install it yourself. )
(_Or try running patch command in your GitBash._)

**Comment by aravind16108** [comment]
Hi @shishir-intelli ,
  I have installed the patch as advised and performed an re-installation.
  Attached the logs for reference. Still I could see 404 errors.
  
[drupal-installation-log.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/12745585/drupal-installation-log.txt)

  
`[304] https://repo.packagist.org/p2/drupal/default_content.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_datepicker.json
[404] https://repo.packagist.org/p2/drupal/components.json
Downloading https://repo.packagist.org/p2/drupal/color.json
[404] https://repo.packagist.org/p2/drupal/quickedit.json
Downloading https://repo.packagist.org/p2/drupal/ctools.json
[404] https://repo.packagist.org/p2/drupal/fontawesome.json
Downloading https://repo.packagist.org/p2/drupal/radix.json
[404] https://repo.packagist.org/p2/drupal/rdf.json
Downloading https://repo.packagist.org/p2/drupal/hal.json
[404] https://repo.packagist.org/p2/drupal/token.json
Downloading https://repo.packagist.org/p2/drupal/better_exposed_filters.json
[404] https://repo.packagist.org/p2/drupal/pathauto.json
Downloading https://repo.packagist.org/p2/drupal/key.json
[404] https://repo.packagist.org/p2/drupal/color.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui.json
[404] https://repo.packagist.org/p2/drupal/ctools.json
Downloading https://repo.packagist.org/p2/drupal/entity.json
[404] https://repo.packagist.org/p2/drupal/radix.json
Downloading https://repo.packagist.org/p2/drupal/paragraphs.json
[404] https://repo.packagist.org/p2/drupal/hal.json
Downloading https://repo.packagist.org/p2/drupal/file_link.json
[404] https://repo.packagist.org/p2/drupal/key.json
Downloading https://repo.packagist.org/p2/drupal/admin_toolbar.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_slider.json
Downloading https://repo.packagist.org/p2/drupal/apigee_api_catalog.json
[404] https://repo.packagist.org/p2/drupal/email_registration.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_resizable.json
[404] https://repo.packagist.org/p2/drupal/entity_reference_revisions.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_draggable.json
[404] https://repo.packagist.org/p2/drupal/entity.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_controlgroup.json
[404] https://repo.packagist.org/p2/drupal/paragraphs.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_checkboxradio.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_datepicker.json
Downloading https://repo.packagist.org/p2/drupal/requirement.json
[404] https://repo.packagist.org/p2/drupal/better_exposed_filters.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_button.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui.json
Downloading https://repo.packagist.org/p2/drupal/jquery_ui_dialog.json
[404] https://repo.packagist.org/p2/drupal/requirement.json
Downloading https://repo.packagist.org/p2/drupal/state_machine.json
[404] https://repo.packagist.org/p2/drupal/admin_toolbar.json
Downloading https://repo.packagist.org/p2/drupal/profile.json
[404] https://repo.packagist.org/p2/drupal/file_link.json
Downloading https://repo.packagist.org/p2/drupal/inline_entity_form.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_resizable.json
Downloading https://repo.packagist.org/p2/drupal/address.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_touch_punch.json
Downloading https://repo.packagist.org/p2/drupal/apigee_edge.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_checkboxradio.json
Downloading https://repo.packagist.org/p2/drupal/apigee_m10n.json
[404] https://repo.packagist.org/p2/drupal/profile.json
Downloading https://repo.packagist.org/p2/drupal/google_analytics.json
[404] https://repo.packagist.org/p2/drupal/adminimal_admin_toolbar.json
Downloading https://repo.packagist.org/p2/drupal/smtp.json
[404] https://repo.packagist.org/p2/drupal/address.json
Downloading https://repo.packagist.org/p2/drupal/jsonapi_extras.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_button.json
Downloading https://repo.packagist.org/p2/furf/jquery-ui-touch-punch.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_dialog.json
Downloading https://repo.packagist.org/p2/drupal/commerce.json
[404] https://repo.packagist.org/p2/drupal/state_machine.json
[404] https://repo.packagist.org/p2/drupal/inline_entity_form.json
[404] https://repo.packagist.org/p2/drupal/smtp.json
[404] https://repo.packagist.org/p2/furf/jquery-ui-touch-punch.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_draggable.json
[404] https://repo.packagist.org/p2/drupal/apigee_edge.json
[404] https://repo.packagist.org/p2/drupal/commerce.json
[404] https://repo.packagist.org/p2/drupal/apigee_m10n.json
[404] https://repo.packagist.org/p2/drupal/jquery_ui_controlgroup.json
[404] https://repo.packagist.org/p2/drupal/apigee_api_catalog.json
[404] https://repo.packagist.org/p2/drupal/google_analytics.json
[404] https://repo.packagist.org/p2/drupal/jsonapi_extras.json`

**Comment by shishir-intelli** [comment]
It re-tries after 404 (example `jquery_ui_datepicker.json` later it installed it), may be some network issue, this has nothing to do with Apigee modules.
Are you able to install and run Drupal instance successfully including JSON:API module or facing any issue in the Drupal instance after re-installation?

**Comment by aravind16108** [comment]
Hi @shishir-intelli ,
   The issue got resolved when I reinstalled Drupal apigee quick start in a fresh EC2 instance and new database instance.
   Thanks for your help.
