### ISSUE TITLE
collapse function with Taxonomy vocabulary 

### ISSUE THREAD

**Issue by hollyhw99** [apigee/apigee-devportal-kickstart-drupal#689]
## Is your feature request related to a problem? Please describe
Hi, we have a Taxonomy vocabulary: Api Categories with our project. On the portal side, we pull out the Api Categories from Apigee Edge, and we feed the data to a tree structure so that the Api Categories can be displayed. As our categories are increasing, we would like to request a collapse display function with Taxonomy vocabulary 

## Additional context
 screenshots 
 <our site>/admin/structure/taxonomy/manage/api_category/overview 
 Api category data are pulling off from Apigee Edge side (Product Custom attributes value)
<img width="867" alt="Screenshot 2024-04-16 at 1 34 53 PM" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/36746092/1d3596b9-e600-413d-9647-7990089c579c">

api_category display in a tree structure
<img width="415" alt="Screenshot 2024-04-16 at 1 43 12 PM" src="https://github.com/apigee/apigee-devportal-kickstart-drupal/assets/36746092/9be87a56-f2b6-4cb8-b466-97af8a028540">

would like to have a clickable option so that the category tree can collapse as our categories are growing. 

any advice will be highly appreciated. 

Thank you so much

**Comment by kedarkhaire** [comment]
Hi @hollyhw99 

[Simple hierarchical select](https://www.drupal.org/project/shs) or [Client-side Hierarchical Select](https://www.drupal.org/project/cshs) modules will be helpful to complete your request as they maintain the hierarchy of taxonomy terms defined.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @hollyhw99 
Seems the above comment helped you to achieve the result, closing the ticket.
Thanks!
