### ISSUE TITLE
how can I install kickstart without monetization

### ISSUE THREAD

**Issue by mert2m** [apigee/apigee-devportal-kickstart-drupal#700]
I want to install Apigee without the monetization module, as described in the documentation. 

https://github.com/apigee/docker-apigee-drupal-kickstart/blob/main/README.md

[](https://github.com/apigee/docker-apigee-drupal-kickstart/blob/main/README.md)

However, how can I disable monetization after the installation? Could you please assist with this?

**Comment by kedarkhaire** [comment]
Hi @mert2m 
Please login as a Site Admin user.
Visit the Uninstall page via Admin Menu -> Extend> Uninstall Module
Check the Apigee Monetization option/row and hit the  Uninstall button at the bottom of the page.
It will ask you to confirm and then again select Uninstall button to uninstall the module.

Thanks!

**Comment by mert2m** [comment]
Hi,

Thank you for the information. I followed these steps:

docker-compose up drupal.
Logged into the site and completed the installation.
Disabled the monetization module.
