### ISSUE TITLE
When "Enable demo content" is not selected during installation, associated custom blocks are still placed.

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-devportal-kickstart-drupal#72]
When the content associated with these blocks is not installed, the blocks contain references to content that does not exist.  The following message appears, in place of those blocks:

> This block is broken or missing. You may be missing content or you might need to enable the original module.

## Workaround

1. Visit the "Block Layout" page at `/admin/structure/block`.
2. Delete the following blocks:
    - Title bar: APIs 
    - Title bar: Blog 
    - Title bar: Contact Us 
    - Title bar: FAQs 
    - Title bar: Forum
    - CTA: Article
    - CTA: Blog
    - CTA: Create developer account
    - Social links
3. Visit the "Page title" block configuration at `/admin/structure/block/manage/apigee_kickstart_title`, click the "Pages" vertical tab, and change the path exclusions listed to include only: `/apis` and click "Save".

**Comment by cnovak** [comment]
Instead of having this issue, we decided to remove the option of not installing default content.
