### ISSUE TITLE
Apigee demo content gone?

### ISSUE THREAD

**Issue by laughingbiscuit** [apigee/apigee-devportal-kickstart-drupal#75]
Hi all,

When I ran this over a week ago, the installation wizard had a page for Apigee credentials and org details. Once the installation was complete, the default theme was an Apigee theme with the nice background with 3 people.

When running this today, the Apigee page has gone from the wizard and the default theme is the Acme theme. Has something changed?

> Apigee Developer Portal Kickstart 8.6.14

**Comment by laughingbiscuit** [comment]
theme: confirmed with @cnovak that the Acme portal is the new design
apigee wizard missing: possibly still a bug

**Comment by kiranjyoth** [comment]
@laughingbiscuit yes, ACME portal will be the new theme on bootstrap as per @giteshk too. After apigee wizard is added, one feature pending as referred in #10 , is to set a private file system using config or set a default private file system - if it's executed using quick-start script.

**Comment by laughingbiscuit** [comment]
exciting! ill keep an eye on the changes. thanks

**Comment by jacine** [comment]
Hello! The demo content and Apigee credentials are back, along with the new theme, so I think we can close this.  Feel free to re-open, or create a new issue if there are any problems.  Thanks!
