### ISSUE TITLE
Migration from D7 Apigee developer portal

### ISSUE THREAD

**Issue by nextagencyio** [apigee/apigee-devportal-kickstart-drupal#83]
Curious if there is any migration path from the D7 distribution.

**Comment by cnovak** [comment]
@drupalninja we have not spent any time yet working through a guide with info/tips on how to migrate over. However, the goal of this project was to cover all the functionality that existed in Drupal 7. Most of the Apigee Edge data such as apps, API products,  and developers will already be in Edge org, but I am sure results will vary depending on how much customization was done.  Let us know if you run into any specific issues for now.

**Comment by nextagencyio** [comment]
<img width="789" alt="Screen Shot 2019-09-24 at 1 56 35 PM" src="https://user-images.githubusercontent.com/1112449/65541548-2c0c9a80-ded3-11e9-9d0d-95293c71fed1.png">

I am working on mapping out the D7 fields to their D8 counterpart and it looks pretty straightforward. The D7 site is overall much simpler so really the only task would be to remap fields as needed to their D8 counterpart. The standard D7 upgrade would do a lot of this for you but I can see an advantage to having a more focused migration feature that just pulls in what you might want and maps it to the appropriate spot. The mapping of image, audio and video nodes to the corresponding D8 media types, for example, would be helpful. I picture someone enabling the feature and running the migrations they are interested in or the developer just borrowing some of the mapping syntax for their own custom migration.

**Comment by shadcn** [comment]
I created PR #269 with migrations for the entity types that ship with devportal. This should take care of migrating most devportal content.

I'm now looking into a way to allow developers to easily extend these migrations and add custom fields.

**Comment by nextagencyio** [comment]
Awesome @arshad! I had created a Drupal.org module here but your PR is probably better. This is the code I came up with in case you want to cross-reference: https://git.drupalcode.org/project/migrate_apigee

**Comment by shadcn** [comment]
@drupalninja Woah nice! I'll take a look at migrate_apigee. Thanks

**Comment by nextagencyio** [comment]
I think your solution makes sense, if there is anything you can borrow from my module that's helpful great. I plan on deprecating that module in favor of the solution that will eventually get merged into this project. I will have the project page point to the main Apigee Kickstart project.

**Comment by shadcn** [comment]
@drupalninja Thank you. The PR is ready for review.

I added an example module to the PR. A developer could use this example module as a template on how the default migrations can be extended and how to add custom fields.
