### ISSUE TITLE
navbar.twig error

### ISSUE THREAD

**Issue by kscheirer** [apigee/apigee-devportal-kickstart-drupal#94]
When I install Kickstart on pantheon, I always end up with this fatal error causing a 503.
`Template "@apigee-kickstart/icons/navbar-toggle.svg" is not defined in "@apigee-kickstart/navbar/navbar.twig" at line 36.`

Deleting this line does not seem to cause any problems. I noticed apigee-kickstart-style.scss does not @import components/icons, could this be the problem?

**Comment by jacine** [comment]
Hi @kscheirer,

Ah, I've run into similar issues with anything containing `icon` in the name, on Pantheon too.  Check your `.gitignore` file.  I'm not sure how you installed (via Dashboard or Terminus), but either way you probably have an entry for `Icon` that's being ignored.  It's safe to remove it.  Once you commit that removal, you should see the source for this and be able to commit it and push it to Pantheon.

https://github.com/pantheon-systems/drops-8/blob/default/.gitignore#L48
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.gitignore#L92

Let me know how it goes.

Thanks!
Jacine

**Comment by cnovak** [comment]
Will close ticket, but reopen if still fix above does not work @kscheirer

**Comment by kscheirer** [comment]
Thanks @jacine this was the problem. Removing from gitignore cleared that up, and also surfaced a bunch more places where icons from contrib modules were being ignored.
