### ISSUE TITLE
Installation error on Drupal 8.7

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#96]
Getting the error below when using the apigee_devportal_kickstart.  I ran the composer command:

composer create-project apigee/devportal-kickstart-project:8.x-dev portal --stability dev --no-interaction

I also ran the composer command:
composer.phar create-project apigee/devportal-kickstart-project:8.x-dev portal --stability dev --no-interaction

Got the same error below:

<img width="800" alt="Screen Shot 2019-05-06 at 11 32 27 AM" src="https://user-images.githubusercontent.com/7342666/57239972-fda92400-6ff2-11e9-914a-1f5d8b45c679.png">

-Edgar

_Originally posted by @epowelljr in https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/1#issuecomment-489688819_

Stacktrace: 
```
TypeError: Argument 3 passed to Drupal\apigee_edge\Entity\Controller\Cache\DeveloperAppCacheFactory::__construct() must be an instance of Egulias\EmailValidator\EmailValidatorInterface, instance of Drupal\Component\Utility\EmailValidator given in DeveloperAppCacheFactory.php on line 67 
```

**Comment by cnovak** [comment]
@epowelljr I created a new issue for your comment on issue #1 since this is a different problem.  There are changes in Drupal core 8.7 that are not compatible with our current codebase.  We are preparing a release to address this issue.

**Comment by cnovak** [comment]
This is fixed in [8.x-1.0-beta2 ](https://www.drupal.org/project/apigee_devportal_kickstart/releases/8.x-1.0-beta2) which was just released.  You can run `composer update --optimize-autoloader --with-dependencies` to grab this release.

**Comment by epowelljr** [comment]
Hi Chris,

Updated the Drupal site and it crashed. Got the error below.

How can I restore the site?

Fatal error: Interface 'Apigee\Edge\Entity\EntityInterface' not found in /app/web/modules/contrib/apigee_edge/src/Entity/EdgeEntityInterface.php on line 32


-Edgar

**Comment by cnovak** [comment]
@epowelljr I moved your message above to a new issue.
